	--停催案件
	--前置協商
 
	SELECT M.CHK_TAG,M.IDNO,M.IFLEAD,M.LEAD_BNK_N, M.LEAD_BANK, M.REQ_DEBT_D, M.DOCU_D, M.SIGN_D, M.FAIL_D, M.FAIL_RESN,B.ACCTNMBR,B.CARDNMBR, B.RMS_STATUS AS RMS_STATUS, SPACE(3) AS CACS_STATE, SPACE(3) AS TO_STATE , ROW_NUMBER() OVER (PARTITION BY B.CARDNMBR ORDER BY M.IDNO DESC) AS SEQNO 	
	INTO #CHK_STATE FROM 
	(
		SELECT 'STOP COLL'AS CHK_TAG, IDNO, IFLEAD, LEAD_BNK_N, LEAD_BANK, REQ_DEBT_D, DOCU_D, SIGN_D, FAIL_D, FAIL_RESN 	 
		FROM UIDRP_IDRP_FULL_BASE_VW 
		WHERE FAIL_D IS NULL 
		AND REQ_DOC1_D IS NULL 
		AND ISNULL(LEAD_BANK,'') <> '' 
		AND (IDNO IN (SELECT IDNO FROM UIDRP_Z92_ZZM200 WHERE [dbo].TRANS_YMD(JC40_DATE) < CAST(DATEADD(Day, -3,GETDATE()) AS DATE))  OR CAST(RECEIVE_D AS DATE) >= CAST(DATEADD(DAY,-30,GETDATE()) AS DATE) )

		UNION ALL

		SELECT 'TKD' AS CHK_TAG, IDNO, IFLEAD, LEAD_BNK_N, LEAD_BANK, REQ_DEBT_D, DOCU_D, SIGN_D, FAIL_D, FAIL_RESN  
		FROM UIDRP_IDRP_FULL_BASE_VW 
		WHERE IDNO IN (SELECT CUSTID FROM UIDRP_CUS_IDRP_CUSTINFO)
		 AND FAIL_D IS NULL 
		 AND REQ_DOC1_D IS NULL 
		 AND ISNULL(RW_ACCTBR,'')<>'' 
 
		UNION ALL

		SELECT 'FAIL' AS CHK_TAG, IDNO, IFLEAD, LEAD_BNK_N, LEAD_BANK, REQ_DEBT_D, DOCU_D, SIGN_D, FAIL_D, FAIL_RESN 
		FROM UIDRP_IDRP_FULL_BASE_VW 
		WHERE (FAIL_D IS NOT NULL OR REQ_DOC1_D IS NOT NULL) 
		AND REQ_DEBT_D IS NOT NULL 
		AND FAIL_RESN <> '99' 
		AND ( IDNO IN (SELECT IDNO FROM UIDRP_Z92_ZZM203 WHERE PROCDATE < DATEADD(day,-3,GETDATE()))  OR  CAST(FAIL_D AS DATE) >= CAST(DATEADD(DAY,-3,GETDATE()) AS DATE) )
		--ZZM203 結案通知
	) M
	INNER JOIN COGDB3.dbo.IDRP_BASE B ON M.IDNO=B.ID_TAG  --UIDRP_IDRP_BASE
	WHERE ISNULL(B.CARDNMBR,'') <> ''   
   
    DELETE FROM #CHK_STATE WHERE SEQNO > 1
	--OR CARDNMBR IN (SELECT CARDNMBR FROM UIDRP_DO_NOT_STATE)
	-- GROUP BY CARDNMBR 

	CREATE INDEX IDX_CHK_STATE_CARDNMBR ON #CHK_STATE(CARDNMBR)
 

	UPDATE A SET A.RMS_STATUS = B.STATUS1, A.CACS_STATE = B.CACS_STATE
	FROM #CHK_STATE A
	INNER JOIN dbo.DS_REC_COMBO_VW B ON B.cardnmbr = A.CARDNMBR	 
 			 
	UPDATE A SET A.CACS_STATE = B.CACS_STATE
	FROM #CHK_STATE A
	INNER JOIN dbo.DS_CARDS_VW  B ON B.cardnmbr = A.CARDNMBR 

	UPDATE A SET A.CACS_STATE= B.CACS_STATE
	FROM #CHK_STATE A
	INNER JOIN dbo.DS_BUDTRAN_VW B On B.cardnmbr = A.CARDNMBR 

 
  	DELETE FROM #CHK_STATE
	WHERE (CHK_TAG='STOP COLL' AND ( SUBSTRING(CACS_STATE,1,1) IN ('Y','N') OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8') OR CACS_STATE IN ('G99','S97','S98')  OR (SUBSTRING(RMS_STATUS,1,1)='9' AND SUBSTRING(RMS_STATUS,1,2) NOT IN ('96','98')) ) )	 
	   OR (CHK_TAG='FAIL' AND ( SUBSTRING(CACS_STATE,1,1) IN ('Y','N') OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8')  OR CACS_STATE ='G99' ) )
	   OR (CHK_TAG='TKD' AND ( SUBSTRING(CACS_STATE,1,1) IN ('Y','N') OR CACS_STATE IN ('S97','S98') ) )



	--FAIL
	UPDATE #CHK_STATE SET TO_STATE='G76' WHERE SUBSTRING(CACS_STATE,1,2)='G7' AND CHK_TAG='FAIL'
	UPDATE #CHK_STATE SET TO_STATE='G74' WHERE SUBSTRING(CACS_STATE,1,2)='G7' AND CHK_TAG='FAIL' AND FAIL_RESN IN ('11','12','13','14','15','16','17','18','19','21','49')
	UPDATE #CHK_STATE SET TO_STATE='G86' WHERE SUBSTRING(CACS_STATE,1,2)='G8' AND CHK_TAG='FAIL'
	UPDATE #CHK_STATE SET TO_STATE='N41' WHERE SUBSTRING(CACS_STATE,1,1)='N' AND CHK_TAG='FAIL'
	
	INSERT INTO @FF
	SELECT 'WCHK_RESUME_COLL' AS PRG, GETDATE() AS PROCDATE, IDNO, CARDNMBR, TO_STATE AS CACS_STATE, CACS_STATE AS ORI_STATE  
	FROM #CHK_STATE
	WHERE CHK_TAG='FAIL' 	

	--STOPCOLL
	INSERT INTO @FF
	SELECT 'WCHK_STOP_COLL' AS PRG, GETDATE() AS PROCDATE, IDNO, CARDNMBR, IIF(LEAD_BNK_N='021','G71','G81') AS CACS_STATE,CACS_STATE AS ORI_STATE
	FROM #CHK_STATE
	WHERE CHK_TAG='STOP COLL'    

	--TKD 	
	INSERT INTO @FF
	SELECT 'WCHK_TKD' AS PRG, GETDATE() AS PRCDATE,IDNO,CARDNMBR,TO_STATE AS CACS_STATE, CACS_STATE AS ORI_STATE
	FROM #CHK_STATE 
	WHERE ISNULL(CACS_STATE,'') <> '' 
	AND CHK_TAG ='TKD'  
 
