SELECT SUBSTRING(RTRIM(NATNID_REGNNUMB) + SPACE(11),1,11) +  SUBSTRING(convert(text, CUST_TITL_LINE1 + SPACE(60)),1,60)+ SUBSTRING(RTRIM(BIZ_TYPE)+ SPACE(6),1,6)+CAST(CAST(CAST(CAST(RIGHT(RTRIM(NATNID_REGNNUMB),7) AS INT)/3 as float) * RAND() AS DECIMAL(15,2)) AS VARCHAR) FROM BUS
WHERE ISNUMERIC(RIGHT(RTRIM(NATNID_REGNNUMB),7)) =1 AND LTRIM(BIZ_TYPE) !=''
