SELECT SUBSTRING(RTRIM(NATNID_REGNNUMB) + SPACE(11),1,11) +  SUBSTRING(convert(text, CUST_TITL_LINE1 + SPACE(60)),1,60)+ SUBSTRING(RTRIM(BIZ_TYPE)+ SPACE(6),1,6)+CAST(CAST(CAST(CAST(RIGHT(RTRIM(NATNID_REGNNUMB),7) AS INT)/3 as float) * RAND() AS DECIMAL(15,2)) AS VARCHAR) FROM BUS
WHERE ISNUMERIC(RIGHT(RTRIM(NATNID_REGNNUMB),7)) =1 AND LTRIM(BIZ_TYPE) !=''
                      
                      
                      
SELECT  SUBSTRING([PBUNIT]+SPACE(3),1,3) + 
       SUBSTRING([PBBRNO]+SPACE(4),1,4) + 
      SUBSTRING([PBSRNO]+SPACE(30),1,30) + 
      SUBSTRING([PBAPNO]+SPACE(24),1,24) + 
	    SUBSTRING([PBCHARCODE]+SPACE(8),1,8) + 
      SUBSTRING([PBSTATUS]+SPACE(4),1,4) + 
      SUBSTRING([PBCUSTID]+SPACE(11),1,11) + 
      SUBSTRING([CUSTIDNO]+SPACE(3),1,3) + 
      SUBSTRING([PBCUSTTYPE]+SPACE(3),1,3) + 
     SUBSTRING([PBOPENDATE]+SPACE(8),1,8) + 
	  SUBSTRING([PBCNAME]+SPACE(60),1,60) + 
     SUBSTRING([PBCURCODE]+SPACE(3),1,3) + 
     SUBSTRING(CAST([PBACTBAL] AS VARCHAR)+SPACE(16),1,16) + 
    SUBSTRING(CAST([PBBAL] AS VARCHAR)+SPACE(16),1,16) + 
    SUBSTRING(CAST([PBSTOPPAYAMT] AS VARCHAR)+SPACE(15),1,15) + 
   SUBSTRING(CAST([PBCARDAMT] AS VARCHAR)+SPACE(15),1,15) + 
    SUBSTRING([PBGSACTCODE],1,1) +
     SUBSTRING([PBJOINTCODE],1,1)+
      SUBSTRING([PBRATETYPE]+SPACE(16),1,16) + 
      SUBSTRING(CAST([PBINTRATE] AS VARCHAR)+SPACE(9),1,9) + 
     SUBSTRING(CAST([PBINTPAYABLE] AS VARCHAR)+SPACE(15),1,15) + 
   SUBSTRING([PBOVRSTATUS],1,1) +
     SUBSTRING([PBPGKIND],1,1) + 
	 SUBSTRING(CAST([PBPGAMT] AS VARCHAR)+SPACE(15),1,15) + 	    
   
      SUBSTRING([PBPGSETDATE]+SPACE(8),1,8) + 
	   SUBSTRING([PBTAXCODE],1,1) +
     SUBSTRING(CAST([PBGROSSINT] AS VARCHAR)+SPACE(15),1,15) + 
     SUBSTRING(CAST([PBGROSSTAX] AS VARCHAR)+SPACE(15),1,15) +  
	  SUBSTRING([PBINSURCODE],1,1) +
	  SUBSTRING([PBNHICODE],1,1) +
	   SUBSTRING([PBTAXPAYERID]+SPACE(11),1,11) + 
	     SUBSTRING([PBSECCODE],1,1)+
    SUBSTRING([PBLASTTXDATE]+SPACE(8),1,8)  
    
     
  FROM [CBCDIC].[dbo].[A21]                      
