USE [COGDB1]
GO

/****** Object:  Index [IX_SCHEDULE_TASKLOGTB_MIS_DATE]    Script Date: 2019/11/20 ¤W¤È 10:48:59 ******/
CREATE NONCLUSTERED INDEX [IX_SCHEDULE_TASKLOGTB_MIS_DATE] ON [dbo].[SCHEDULE_TASKLOGTB]
(
	[MIS_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/*
ALTER TABLE  [dbo].[SCHEDULE_TASKLOGTB]
ADD CONSTRAINT PK_SCHEDULE_TASKLOGTB PRIMARY KEY (SEQNO); 
*/