USE [COGDB1]
GO

/****** Object:  Index [IX_SCHEDULE_TASKTB]    Script Date: 2019/11/20 ¤W¤È 10:56:19 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_SCHEDULE_TASKTB] ON [dbo].[SCHEDULE_TASKTB]
(
	[SEQNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


