USE [COGDB1]
GO

/****** Object:  Index [IX_TaskScriptTB_StepNO]    Script Date: 2019/11/20 ¤W¤È 10:52:36 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_TaskScriptTB_StepNO] ON [dbo].[TaskScriptTB]
(
	[StepNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


ALTER TABLE  [dbo].[TaskScriptTB]
ADD CONSTRAINT PK_TaskScriptTB PRIMARY KEY (SEQNO); 
