USE [COGDB2]
GO
/****** Object:  StoredProcedure [dbo].[UIDRP_CA_MISRPT10300_SP1]    Script Date: 2019/5/13 上午 09:29:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		Frank
-- Create date: 2017/05/11
-- Description:	1.3	IDRP Nonleading CA Form(CA/MISRPT10300)
-- GET_CAFORM_NONLEADING_V10.PRG FoxPro程式原始碼
-- =============================================
ALTER PROCEDURE [dbo].[UIDRP_CA_MISRPT10300_SP]

----------------------------------------------
-- 以下的變數是由外面的程式傳進來的
----------------------------------------------
@THIS_DATE VARCHAR(10)

AS
BEGIN
SET NOCOUNT ON;
----------------------------------------------
-- 變數區//宣告在這個SP中會用到的變數
----------------------------------------------
DECLARE @MESSAGE Varchar(500)= '', @STATUS bit= 1
--DECLARE @M_SOEID VARCHAR(7) = 'am21679'
DECLARE @THEDATE DATE, @RW_FLAG VARCHAR(1) = ''

DECLARE @AD as INT,@STOP as INT
DECLARE @B1 as INT, @B2 as INT, @B3 as INT,@RTN as INT, @UTAG as Varchar(1)
DECLARE @S_RW as INT,@END_TIME as DateTime,@DateTimeValue as Varchar(30),@DateTimeCHK as Datetime

--for CSR_CAFORM1
DECLARE @CSR1_CASENO varchar(20), @CSR1_IDNO varchar(10)
,@CSR1_REQ_DEBT_D varchar(10), @CSR1_LEAD_BNK_N varchar(3)

--for ACCTTYPE1
DECLARE @G1 INT, @G2 INT
DECLARE @NA_DQ INT, @CTL_DQ INT, @NA1_OS1 INT, @CTL1_OS1 INT

--for CSR_CHK_IFRW
--DECLARE @CSR_CYCLEID_2 TINYINT, @CSR_CDC_2 TINYINT, @CSR_ACCOUNTTYPE VARCHAR(3), @CSR_CYCDATE DATE, @CSR_WO_FLAG_2 VARCHAR(1)
--DECLARE @CSR_DPD INT, @CSR_IFREWRITE VARCHAR, @CSR_STAGE_NOTE VARCHAR(1), @CSR_CARDNMBR VARCHAR

----------------------------------------------
-- TEMP TABLE 管理
----------------------------------------------
IF(OBJECT_ID('TEMPDB..#TEMP1')IS NOT NULL) BEGIN DROP TABLE #TEMP1 END
--IF(OBJECT_ID('TEMPDB..#TEMP3')IS NOT NULL) BEGIN DROP TABLE #TEMP3 END
--IF(OBJECT_ID('TEMPDB..#CARDS_NAME')IS NOT NULL) BEGIN DROP TABLE #CARDS_NAME END
--IF(OBJECT_ID('TEMPDB..#BUDTRAN_NAME')IS NOT NULL) BEGIN DROP TABLE #BUDTRAN_NAME END
IF(OBJECT_ID('TEMPDB..#SYS_NAME')IS NOT NULL) BEGIN DROP TABLE #SYS_NAME END
IF(OBJECT_ID('TEMPDB..#CURRENT_CDC1')IS NOT NULL) BEGIN DROP TABLE #CURRENT_CDC1 END
--IF(OBJECT_ID('TEMPDB..#CURRENT_CDC2')IS NOT NULL) BEGIN DROP TABLE #CURRENT_CDC2 END
--IF(OBJECT_ID('TEMPDB..#CURRENT_CDC3')IS NOT NULL) BEGIN DROP TABLE #CURRENT_CDC3 END
--IF(OBJECT_ID('TEMPDB..#CARD_LOAN')IS NOT NULL) BEGIN DROP TABLE #CARD_LOAN END
IF(OBJECT_ID('TEMPDB..#NONLEAD_BOOC')IS NOT NULL) BEGIN DROP TABLE #NONLEAD_BOOC END
IF(OBJECT_ID('TEMPDB..#CTL_NONRW')IS NOT NULL) BEGIN DROP TABLE #CTL_NONRW END
IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_BASE_1')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_BASE_1 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_BASE_2')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_BASE_2 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_BASE_3')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_BASE_3 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_BASE_4')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_BASE_4 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_COMPARE')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_COMPARE END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZS240')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZS240 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZS262')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZS262 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZS241')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZS241 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZM260_1')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZM260_1 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZM260_N')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZM260_N END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZM260_2_1')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZM260_2_1 END
--IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_MAPZZM260_2')IS NOT NULL) BEGIN DROP TABLE #IDRP_CAFORM_NONLEADING_MAPZZM260_2 END
IF(OBJECT_ID('TEMPDB..#NONLEADING_CAFORM1')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_CAFORM1 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_CAFORM2')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_CAFORM2 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_CAFORM3')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_CAFORM3 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_CAFORM11')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_CAFORM11 END
--IF(OBJECT_ID('TEMPDB..#DEL_MAPBTODAY')IS NOT NULL) BEGIN DROP TABLE #DEL_MAPBTODAY END
--IF(OBJECT_ID('TEMPDB..#DEL_NONLEADING_IFWOFLG')IS NOT NULL) BEGIN DROP TABLE #DEL_NONLEADING_IFWOFLG END
IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_TODAY1')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_TODAY1 END
IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_TODAY')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_TODAY END
--IF(OBJECT_ID('TEMPDB..#CAFORM_CHECKDEBT_1')IS NOT NULL) BEGIN DROP TABLE #CAFORM_CHECKDEBT_1 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_CHECKDEBT_2')IS NOT NULL) BEGIN DROP TABLE #CAFORM_CHECKDEBT_2 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_CHECKDEBT_3')IS NOT NULL) BEGIN DROP TABLE #CAFORM_CHECKDEBT_3 END
IF(OBJECT_ID('TEMPDB..#CAFORM_DATA4')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA4 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_DATA60')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA60 END
IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6_1')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6_1 END
IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6_2')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6_2 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6_3')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6_3 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6_4')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6_4 END
IF(OBJECT_ID('TEMPDB..#CAFORM_DATA5')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA5 END
IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA6 END
--IF(OBJECT_ID('TEMPDB..#CAFORM_DATA7')IS NOT NULL) BEGIN DROP TABLE #CAFORM_DATA7 END
--IF(OBJECT_ID('TEMPDB..#RW_TYPE')IS NOT NULL) BEGIN DROP TABLE #RW_TYPE END
IF(OBJECT_ID('TEMPDB..#RW_TYPE1')IS NOT NULL) BEGIN DROP TABLE #RW_TYPE1 END
--IF(OBJECT_ID('TEMPDB..#RW_TYPE2')IS NOT NULL) BEGIN DROP TABLE #RW_TYPE2 END
--IF(OBJECT_ID('TEMPDB..#CHK_BAL')IS NOT NULL) BEGIN DROP TABLE #CHK_BAL END
--IF(OBJECT_ID('TEMPDB..#CHK_BAL1')IS NOT NULL) BEGIN DROP TABLE #CHK_BAL1 END
--IF(OBJECT_ID('TEMPDB..#TEMP_RW')IS NOT NULL) BEGIN DROP TABLE #TEMP_RW END
--IF(OBJECT_ID('TEMPDB..#TEMP_RW_1')IS NOT NULL) BEGIN DROP TABLE #TEMP_RW_1 END

--IF(OBJECT_ID('TEMPDB..#CHK_IFRW0')IS NOT NULL) BEGIN DROP TABLE #CHK_IFRW0 END
IF(OBJECT_ID('TEMPDB..#CHK_IFRW')IS NOT NULL) BEGIN DROP TABLE #CHK_IFRW END
--IF(OBJECT_ID('TEMPDB..#CHK_IFRW2')IS NOT NULL) BEGIN DROP TABLE #CHK_IFRW2 END

IF(OBJECT_ID('TEMPDB..#MAX_CAFORM_CDC')IS NOT NULL) BEGIN DROP TABLE #MAX_CAFORM_CDC END
--IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA1')IS NOT NULL) BEGIN DROP TABLE #CURSOR_CAFORM_DATA1 END
--IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA100')IS NOT NULL) BEGIN DROP TABLE #CURSOR_CAFORM_DATA100 END
--IF(OBJECT_ID('TEMPDB..#DATA1')IS NOT NULL) BEGIN DROP TABLE #DATA1 END

--IF(OBJECT_ID('TEMPDB..#EXP_DATA1')IS NOT NULL) BEGIN DROP TABLE #EXP_DATA1 END
--IF(OBJECT_ID('TEMPDB..#EXP_DATA2')IS NOT NULL) BEGIN DROP TABLE #EXP_DATA2 END
--IF(OBJECT_ID('TEMPDB..#EXP_DATA3')IS NOT NULL) BEGIN DROP TABLE #EXP_DATA3 END
--IF(OBJECT_ID('TEMPDB..#DTA_TEMP')IS NOT NULL) BEGIN DROP TABLE #DTA_TEMP END

--IF(OBJECT_ID('TEMPDB..#WW')IS NOT NULL) BEGIN DROP TABLE #WW END
IF(OBJECT_ID('TEMPDB..#Z98')IS NOT NULL) BEGIN DROP TABLE #Z98 END
--IF(OBJECT_ID('TEMPDB..#Z98_1')IS NOT NULL) BEGIN DROP TABLE #Z98_1 END
IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA3')IS NOT NULL) BEGIN DROP TABLE #CURSOR_CAFORM_DATA3 END

IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_DUP')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_DUP END
IF(OBJECT_ID('TEMPDB..#SUMMARY_ML')IS NOT NULL) BEGIN DROP TABLE #SUMMARY_ML END
--IF(OBJECT_ID('TEMPDB..#ML')IS NOT NULL) BEGIN DROP TABLE #ML END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_01')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_01 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_02')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_02 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_03')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_03 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_04')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_04 END
IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_05')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_05 END
--IF(OBJECT_ID('TEMPDB..#KKK')IS NOT NULL) BEGIN DROP TABLE #KKK END

--IF(OBJECT_ID('TEMPDB..#LST_ACCT')IS NOT NULL) BEGIN DROP TABLE #LST_ACCT END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_06')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_06 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_07')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_07 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_07_0')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_07_0 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_07_1')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_07_1 END
--IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_08')IS NOT NULL) BEGIN DROP TABLE #NONLEADING_SUMMARY_08 END

--IF(OBJECT_ID('TEMPDB..#APCM1')IS NOT NULL) BEGIN DROP TABLE #APCM1 END
--IF(OBJECT_ID('TEMPDB..#PRE_SUMMARY')IS NOT NULL) BEGIN DROP TABLE #PRE_SUMMARY END
--IF(OBJECT_ID('TEMPDB..#DEL_CHECKZ98')IS NOT NULL) BEGIN DROP TABLE #DEL_CHECKZ98 END
--IF(OBJECT_ID('TEMPDB..#CHK_APDEBTLIST')IS NOT NULL) BEGIN DROP TABLE #CHK_APDEBTLIST END
--IF(OBJECT_ID('TEMPDB..#HIST1')IS NOT NULL) BEGIN DROP TABLE #HIST1 END
--IF(OBJECT_ID('TEMPDB..#CHECK0')IS NOT NULL) BEGIN DROP TABLE #CHECK0 END
--IF(OBJECT_ID('TEMPDB..#CHECK1')IS NOT NULL) BEGIN DROP TABLE #CHECK1 END
--IF(OBJECT_ID('TEMPDB..#CHECK2')IS NOT NULL) BEGIN DROP TABLE #CHECK2 END
--IF(OBJECT_ID('TEMPDB..#EXP_ACCTNMBR')IS NOT NULL) BEGIN DROP TABLE #EXP_ACCTNMBR END
--IF(OBJECT_ID('TEMPDB..#DEL_MAPBLTODAY')IS NOT NULL) BEGIN DROP TABLE #DEL_MAPBLTODAY END

--IF(OBJECT_ID('tempdb..#CARDS')IS NOT NULL) BEGIN DROP TABLE #CARDS END
--IF(OBJECT_ID('tempdb..#BUDTRAN')IS NOT NULL) BEGIN DROP TABLE #BUDTRAN END
--IF(OBJECT_ID('tempdb..#REC')IS NOT NULL) BEGIN DROP TABLE #REC END
--IF(OBJECT_ID('tempdb..#REC_2')IS NOT NULL) BEGIN DROP TABLE #REC_2 END
IF(OBJECT_ID('TEMPDB..#RW_ACCTLIST')IS NOT NULL) BEGIN DROP TABLE #RW_ACCTLIST END
--IF(OBJECT_ID('TEMPDB..#CHK_APDEBTLIST')IS NOT NULL) BEGIN DROP TABLE #CHK_APDEBTLIST END
IF(OBJECT_ID('TEMPDB..#HIST1')IS NOT NULL) BEGIN DROP TABLE #HIST1 END

IF(OBJECT_ID('TEMPDB..#APCM1') IS NULL)
BEGIN
  CREATE TABLE #APCM1(
 	  IDNO      VARCHAR(10) --UIDRP_DE_IDRP_DEBTDTL
	, ACCTNMBR  VARCHAR(16) --UIDRP_DE_IDRP_DEBTDTL
	, CARDNMBR  VARCHAR(16) --UIDRP_DE_IDRP_DEBTDTL
	, ACCTTYPE  VARCHAR(3)  --UIDRP_DE_IDRP_DEBTDTL.PRODTYPE
	, APCM      VARCHAR(1)  --SPACE(1)
	, CDC       INT         --/BUDTRN.CDC CARDS.CDC tinyint    
    )    
END
ELSE
BEGIN
	TRUNCATE TABLE #APCM1
END
IF(OBJECT_ID('TEMPDB..#NONLEADING_SUMMARY_08') IS NULL)
BEGIN
CREATE TABLE #NONLEADING_SUMMARY_08(
	--  SN            INT           --ROW_NUMBER()
	  IDNO          VARCHAR(10)   --UIDRP_DE_IDRP_DEBTDTL.IDNO
	, [NAME]        NVARCHAR(12)
	, OPEN_D        DATE          --Z98_ZZS260.FIRST_DATE to DATA
	, CDC           INT           --BUDTRN.CDC CARDS.CDC tinyint       
	, IFWO          VARCHAR(1)    --WO_FLAG N /Y  
	, FIRST_DATE    VARCHAR(7)    --Z98_ZZS260
	, [PERIOD]      DECIMAL(3)    --Z98_ZZS260 
	, RATE          DECIMAL(5, 2) --Z98_ZZS260  
	, PAYAMOUNT     DECIMAL(9)    --Z98ZZM260.DISP_AMT
	, EXP_LOAN      DECIMAL(9)    --SUM(Z98ZZM260.EXP_LOAN)
	, CASH_CARD     DECIMAL(9)    --SUM(Z98ZZM260.CASH_CARD)
	, CREDITCARD    DECIMAL(9)    --SUM(Z98ZZM260.CREDITCARD)
	, TTL_DEBT      DECIMAL(9)    --SUM(Z98ZZM260.EXP_LOAN+Z98ZZM260.CASH_CARD+Z98ZZM260.CREDITCARD)
	, ACCTTYPE      VARCHAR(3)    --SPACE(3)
	, CARDNMBR      VARCHAR(14)   --SPACE(14)
	, IFTWOSTAGE    VARCHAR(1)    --UIDRP_IDRP_NONLEADING_BASE.IFTWOSTAGE 
	, RW_FLAG       VARCHAR(1)    --SPACE(1) Y /N
	, RW_ACCTBR     VARCHAR(24)   --SPACE(14)
	, CARDLOAN      VARCHAR(1)    --SPACE(1)
	, BOOC          VARCHAR(3)    --'CTL' = BUSINESS
	, TAIL          VARCHAR(10)   --ROW_NUMBER + @RW_NUMBER2 ->VARCHAR
	, APCM          VARCHAr(1)    --MARGE #PRE_SUMMARY TABLE to ONE
    )
END
ELSE
BEGIN
	TRUNCATE TABLE #NONLEADING_SUMMARY_08
END

 
IF(OBJECT_ID('TEMPDB..#ACCTDTL') IS NULL)
BEGIN
CREATE TABLE #ACCTDTL(
      CASENO        VARCHAR(20)
    , IDNO          VARCHAR(10)
    , BANKCODE      VARCHAR(3)     --'021' BANKCODE
	, CARDNMBR      VARCHAR(16)    --UIDRP_DE_IDRP_DEBTDTL.CARDNMBR
	, ACCOUNTTYPE   VARCHAR(3)     --UIDRP_DE_IDRP_DEBTDTL.PRODTYPE
	, OS1           DECIMAL(18,2)  --UIDRP_DE_IDRP_DEBTDTL.TTL_DEBT_I  numeric(8, 0)
	, PRINCIPALA    DECIMAL(18,2)  --UIDRP_DE_IDRP_DEBTDTL.CURR_P numeric(8, 0)
	, INTEREST      DECIMAL(18,2)  --UIDRP_DE_IDRP_DEBTDTL.CURR_INT numeric(8, 0)
	, LATEFEE       DECIMAL(18,2)  --UIDRP_DE_IDRP_DEBTDTL.CURR_FEE numeric(8, 0)
	, LEGALFEE      DECIMAL(18,2)  --UIDRP_DE_IDRP_DEBTDTL.CURR_OTH numeric(8, 0)
	, PENALTY       VARCHAR(1)     --SPACE(1)
	, DELQBKT       VARCHAR(1)     --UIDRP_DE_IDRP_DEBTDTL.CDC
	, WO            VARCHAR(1)     --UIDRP_DE_IDRP_DEBTDTL.WO_FLAG  'Y'/'N'
	, CYCLEID_2     INT            --BUDTRN.CYCLEID  CARDS.CYCLEID tinyint
	, CDC_2         INT            --BUDTRN.CDC CARDS.CDC tinyint
	, WO_FLAG_2     VARCHAR(1)     --'0'/'1'
	, DPD           VARCHAR(3)     --SPACE(3) 
    )              
END
ELSE
BEGIN
	TRUNCATE TABLE #ACCTDTL
END
 

IF(OBJECT_ID('TEMPDB..#IDRP_CAFORM_NONLEADING_BASE_4') IS NULL)
BEGIN
CREATE TABLE #IDRP_CAFORM_NONLEADING_BASE_4(
	  CASENO        VARCHAR(20)     --UIDRP_DE_IDRP_CUSTINFO   bigint
	, IDNO          VARCHAR(10)     --UIDRP_DE_IDRP_CUSTINFO
	, BIRTHDAY      VARCHAR(10)     --UIDRP_DE_IDRP_CUSTINFO CONVERT(varchar)
	, [NAME]        NVARCHAR(12)    --UIDRP_DE_IDRP_CUSTINFO
	, LEAD_BNK_N    VARCHAR(100)     --UIDRP_DE_IDRP_CUSTINFO
	, LEAD_BANK     NVARCHAR(100)   --UIDRP_DE_IDRP_CUSTINFO
	, REQ_DEBT_D    VARCHAR(10)     --UIDRP_DE_IDRP_CUSTINFO CONVERT(Varchar(10),REQ_DEBT_D,111)
	, RE_DEBT_D     DATETIME        --UIDRP_DE_IDRP_CUSTINFO
	, FIRST_DATE    VARCHAR(7)      --Z98_ZZS260.FIRST_DATE
	, [PERIOD]      DECIMAL(3, 0)   --Z98_ZZS260.PERIOD    
	, RATE          DECIMAL(5, 2)   --Z98_ZZS260.RATE      
	, PAYAMOUNT     DECIMAL(9, 0)   --Z98_ZZS260.PAYAMOUNT 
	, CHANGE_ID     VARCHAR(1)      -- 'Y' / 'N'	 
    )              
END
ELSE
BEGIN
	TRUNCATE TABLE #IDRP_CAFORM_NONLEADING_BASE_4
END

--EXPORT EXCEL OLE
	DECLARE @EXCEL TABLE
	(
		[GROUPGUID] uniqueidentifier
		,[GUID] uniqueidentifier
		,TEMPLATE VARCHAR(100)
		,FOLDER VARCHAR(20)
		,[FILENAME] VARCHAR(200)
		,SHEETNAME VARCHAR(200)
	)

	DECLARE @EXCELCELLS TABLE
	(
		PARENTID uniqueidentifier		
		,CELL_Y INT
		,CELL_X INT
		,CELLVALUE NVARCHAR(100)
		,CELLTYPE NVARCHAR(10)
	)
----------------------------------------------
-- 執行區
----------------------------------------------
BEGIN TRY
    SET @THEDATE = CAST(GETDATE() AS DATE)
	IF @THIS_DATE IS NOT NULL AND LEN(@THIS_DATE) >= 10 
	BEGIN
		SET @THEDATE = CONVERT(DATE, @THIS_DATE, 111)
	END
	
	 -- SELECT 1/0;  

	-- SELECT *  FROM UIDRP_IDRP_NONLEADING_BASE_VW  WHERE LTRIM(RTRIM(LEAD_BNK_N)) NOT IN ('021','976')

    -- Wait By Sage Start
    -- 前置作業 See Source Code --> GET_CAFORM_NONLEADING_V10.PR
    -- Wait By Sage END

    -- Z98是否更新，是藉由讀取檔案是否存在，移至C#
    --#TEMP1來源需再確認 FoxPro -> DE_IDRP_CUSTINFO_VIEW
    --目前的CUSTINFO資料量比NONLEADING_BASE大，且欄位型態也有差異
    --SELECT * 
    --INTO #TEMP1
    --FROM UIDRP_DE_IDRP_CUSTINFO
    --WHERE LEAD_BNK_N NOT IN ('021','976')

    --DELETE FROM UIDRP_IDRP_NONLEADING_BASE
    --WHERE LEAD_BNK_N IS NOT NULL

    --INSERT INTO UIDRP_IDRP_NONLEADING_BASE
    --(
    --    [CASENO],[CASENO_OLD],[IDNO],[CUSTID]
    --    ,[USERID],[USEREXT],[OLDID],[NAME],[CUSTNAME],[BIRTHDAY]
    --    ,[TEL1],[TEL2],[TEL3]
    --    ,[ADDRESS1_1],[ADDRESS1_2],[ADDRESS2_1],[ADDRESS2_2]
    --    ,[MEMO],[DEBT_REAS]
    --    ,[DEC1],[DEC2],[DEC3],[DEC4],[DEC5],[DEC6],[DEC7]
    --    ,[IFLEAD],[IFQZ91],[IF021DEBT],[IF976DEBT]
    --    ,[LEAD_BNK_N],[LEAD_BANK]
    --    ,[TRANSIN_D],[TRANS_BANK],[TRANSOUT_D]
    --    ,[RECEIVE_D],[REQ_DOC1_D],[REQ_DOC2_D],[REQ_DEBT_D]
    --    ,[DOCU_D],[RE_DEBT_D],[GET_DEBT_D],[START_D],[INT_D]
    --    ,[CONTACT_D],[NEGOTI_D],[INTEVE_D],[GET_APRO_D],[AGREE_D]
    --    ,[SEN_CONT_D],[SIGN_D],[FAIL_D],[FAIL_RESN]
    --    ,[CITI_AGREE],[DSGRE_RESN],[FIRSTPAY_D]
    --    ,[ACCOUNT_NO]
    --    ,[PMT_TENOR],[PMT_APR],[PMT_INST]
    --    ,[JCICMARK_D],[NONF_DBAMT]
    --    ,[LOAN_IN],[LOAN_OUT]
    --    ,[CASH_IN],[CASH_OUT]
    --    ,[CARD_IN],[CARD_OUT]
    --    ,[IN_TOTAL],[OUT_TOTAL]
    --    ,[COURT_ADDR]
    --    ,[UPD_ID],[UPD_COM],[UPD_TIME],[UPD_BATCH],[UPD_BTIME]
    --    ,[IFEXPINCOK],[IFDEBTOK]
    --    ,[DEBT_MEMO]
    --    ,[IFTWOSTAGE],[IFCAFORM],[IFNODEBT],[IF_RW],[IF_GRT]
    --    ,[GRT_AGREE],[RW_ACCTBR],[CA_APPLY_D],[SOURCE]
    --    ,[IF_COMM],[COMM_TYPE],[COMM_CODE],[COMMITTEE],[DEBT_COMM],[COMM_DIS],[COMM_DATE],[COMM_R_D],[COMM_AGR_D]
    --    ,[IF_OTH_RPT]
    --)
    
    --SELECT 
    --    [CASENO],[CASENO_OLD],[IDNO],[CUSTID]
    --    ,[USERID],[USEREXT],[OLDID],[NAME],[CUSTNAME],[BIRTHDAY]
    --    ,[TEL1],[TEL2],[TEL3]
    --    ,[ADDRESS1_1],[ADDRESS1_2],[ADDRESS2_1],[ADDRESS2_2]
    --    ,[MEMO],[DEBT_REAS]
    --    ,[DEC1],[DEC2],[DEC3],[DEC4],[DEC5],[DEC6],[DEC7]
    --    ,[IFLEAD],[IFQZ91],[IF021DEBT],[IF976DEBT]
    --    ,[LEAD_BNK_N],[LEAD_BANK]
    --    ,[TRANSIN_D],[TRANS_BANK],[TRANSOUT_D]
    --    ,[RECEIVE_D],[REQ_DOC1_D],[REQ_DOC2_D],[REQ_DEBT_D]
    --    ,[DOCU_D],[RE_DEBT_D],[GET_DEBT_D],[START_D],[INT_D]
    --    ,[CONTACT_D],[NEGOTI_D],[INTEVE_D],[GET_APRO_D],[AGREE_D]
    --    ,[SEN_CONT_D],[SIGN_D],[FAIL_D],[FAIL_RESN]
    --    ,[CITI_AGREE],[DSGRE_RESN],[FIRSTPAY_D]
    --    ,[ACCOUNT_NO]
    --    ,[PMT_TENOR],[PMT_APR],[PMT_INST]
    --    ,[JCICMARK_D],[NONF_DBAMT]
    --    ,[LOAN_IN],[LOAN_OUT]
    --    ,[CASH_IN],[CASH_OUT]
    --    ,[CARD_IN],[CARD_OUT]
    --    ,[IN_TOTAL],[OUT_TOTAL]
    --    ,[COURT_ADDR]
    --    ,[UPD_ID],[UPD_COM],[UPD_TIME],[UPD_BATCH],[UPD_BTIME]
    --    ,[IFEXPINCOK],[IFDEBTOK]
    --    ,[DEBT_MEMO]
    --    ,[IFTWOSTAGE],[IFCAFORM],[IFNODEBT],[IF_RW],[IF_GRT]
    --    ,[GRT_AGREE],[RW_ACCTBR],[CA_APPLY_D],[SOURCE]
    --    ,[IF_COMM],[COMM_TYPE],[COMM_CODE],[COMMITTEE],[DEBT_COMM],[COMM_DIS],[COMM_DATE],[COMM_R_D],[COMM_AGR_D]
    --    ,[IF_OTH_RPT]
    --FROM  #TEMP1
    --WHERE LEAD_BNK_N<>'021' 
    --AND LEAD_BNK_N<>'976' 
    --ORDER BY IDNO, CASENO 
    --GROUP BY IDNO 

	--USE CHECKDEBT IN 0
	--SELECT CHECKDEBT
	--ZAP
	 DELETE FROM UIDRP_CHECKDEBT
	 --USE MAX_CDC IN 0
	 --SELECT MAX_CDC
	 --ZAP
	 DELETE FROM UIDRP_MAX_CAFORM_CDC

	 --USE WAIVE_S98_NOW IN 0
	 --SELECT WAIVE_S98_NOW
	 --ZAP
	 DELETE FROM UIDRP_WAIVE_S98_NOW 

	  --USE DATA1 IN 0
	 --SELE DATA1
	 --ZAP
	 DELETE FROM UIDRP_CA_DATA1
	 --USE DATA2 IN 0
	 --SELE DATA2
	 --ZAP
     DELETE FROM UIDRP_CA_DATA2

	 --FA
	 DELETE FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST WHERE NOTIS_D=CONVERT(VARCHAR(10),@THEDATE,111)

	 SELECT RWA.* INTO #RW_ACCTLIST
	 FROM 
	     ( SELECT ID_TAG,RW_ACCT,LOCATION,ACCTNMBR,CARDNMBR FROM UIDRP_RW_MAPPING WHERE RW_ACCT NOT IN (SELECT RW_ACCT FROM WK_RWX_S91)
	        UNION 
	       SELECT id_tag, new_acct AS RW_ACCT, location, acctnmbr, cardnmbr FROM WK_RWX_S91) AS RWA
	
	 --FIRST TIME UPDATE UIDRP_IDRP_CAFORM_NONLEADING_HIST
	--TRUNCATE TABLE UIDRP_IDRP_CAFORM_NONLEADING_HIST
	--INSERT INTO UIDRP_IDRP_CAFORM_NONLEADING_HIST
	--SELECT distinct A.CASENO, A.IDNO, A.NAME, A.LEAD_BNK_N,A.LEAD_BANK, CONVERT(Varchar(10),A.REQ_DEBT_D,111) AS REQ_DEBT_D, A.RE_DEBT_D, B.FIRST_DATE, B.PERIOD, B.RATE, B.PAYAMOUNT, SPACE(1) AS RW_FLAG,SPACE(14) AS RW_ACCTBR,CONVERT(VARCHAR(10),DATEADD(day,-1,GETDATE()),111) AS NOTIS_D, SPACE(3) AS ACCTTYPE, 'Y' AS IF_COMM
	--FROM UIDRP_IDRP_NONLEADING_BASE_VW A 
	--LEFT JOIN UIDRP_Z98_ZZS260 B ON B.IDN_BAN = A.IDNO  AND A.LEAD_BNK_N=B.MAIN_CODE AND [dbo].[TRANS_ROCDATE](CAST(A.REQ_DEBT_D AS DATE)) = B.REC_DATE
	--WHERE B.FIRST_DATE IS NOT NULL AND B.PERIOD IS NOT NULL AND B.RATE IS NOT NULL AND B.PAYAMOUNT IS NOT NULL  AND A.REQ_DEBT_D < '2019/02/01' 

    --SELECT CASENO, IDNO, DTOC(BIRTHDAY) AS BIRTHDAY, NAME, LEAD_BNK_N, LEAD_BANK, DTOC(REQ_DEBT_D) AS REQ_DEBT_D, RE_DEBT_D,IIF(ISNULL(OLDID),'N','Y') AS CHANGE_ID FROM IDRP_NONLEADING_BASE WHERE !ISNULL(SIGN_D) AND (ISNULL(IFNODEBT) OR IFNODEBT<>'Y' ) AND IDNO<>'A1xxx78';
    --INTO DBF IDRP_CAFORM_NONLEADING_BASE_1

    SELECT CASENO, IDNO, CONVERT(VARCHAR(10),BIRTHDAY,111) AS BIRTHDAY, [NAME], LEAD_BNK_N, LEAD_BANK,CONVERT(Varchar(10),REQ_DEBT_D,111) AS REQ_DEBT_D, RE_DEBT_D,IIF(OLDID IS NULL,'N','Y') AS CHANGE_ID 
    INTO #IDRP_CAFORM_NONLEADING_BASE_1
    FROM UIDRP_IDRP_NONLEADING_BASE_VW
    WHERE SIGN_D IS NOT NULL AND (IFNODEBT IS NULL OR IFNODEBT<>'Y' ) AND IDNO<>'A132093978'


    --SELECT CUSTID AS CUSTID, STRTRAN(STRTRAN(STRTRAN(CUSTNAME,'先生',''),'小姐',''),'(WAU)','') AS SYS_NAME, MAX(DATEOPEN) AS OPEN_DATE FROM CARDS;
    --WHERE ALLTRIM(CUSTID) IN (SELE ALLTRIM(IDNO) FROM IDRP_CAFORM_NONLEADING_BASE_1) GROUP BY CUSTID INTO DBF  CARDS_NAME
    --SELECT CUSTID AS CUSTID, STRTRAN(STRTRAN(STRTRAN(CUSTNAME,'先生',''),'小姐',''),'(WAU)','') AS SYS_NAME, MAX(OPENDATE) AS OPEN_DATE FROM BUDTRAN;
    --WHERE ALLTRIM(CUSTID) IN (SELE ALLTRIM(IDNO) FROM IDRP_CAFORM_NONLEADING_BASE_1) GROUP BY CUSTID INTO DBF  BUDTRAN_NAME
    --SELECT BUDTRAN_NAME
    --APPEND FROM CARDS_NAME
	--SELECT CUSTID, SYS_NAME, MAX(OPEN_DATE) AS OPEN_DATE FROM BUDTRAN_NAME GROUP BY CUSTID INTO DBF SYS_NAME

	--DECLARE @WHERE VARCHAR(500)
	--DECLARE @DATEAS DATETIME = GETDATE()-1

	--SELECT TOP 0 * INTO #CARDS FROM dbo.DS_CARDS_VW
	--SET @WHERE = 'INNER JOIN #IDRP_CAFORM_NONLEADING_BASE_1 B ON DS.CUSTID = B.IDNO  WHERE  MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #CARDS EXECUTE dbo.GET_DS_SP 'CARDS',@DATEAS,@WHERE ,N''

	--SELECT TOP 0 * INTO #BUDTRAN FROM dbo.DS_BUDTRAN_VW
	--SET @WHERE = 'INNER JOIN #IDRP_CAFORM_NONLEADING_BASE_1 B ON DS.CUSTID = B.IDNO  WHERE  MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #BUDTRAN EXECUTE dbo.GET_DS_SP 'BUDTRAN',@DATEAS,@WHERE ,N''


   
	SELECT CBX.* INTO #SYS_NAME  
	FROM (
		SELECT CUSTID AS CUSTID, REPLACE(REPLACE(REPLACE(CUSTNAME,'先生',''),'小姐',''),'(WAU)','') AS SYS_NAME--, MAX(DATEOPEN) AS OPEN_DATE 		 
		FROM dbo.DS_CARDS_VW
		WHERE LTRIM(RTRIM(CUSTID)) IN (SELECT LTRIM(RTRIM(IDNO)) FROM #IDRP_CAFORM_NONLEADING_BASE_1) 
		GROUP BY CUSTID, CUSTNAME
		UNION
		SELECT CUSTID AS CUSTID, REPLACE(REPLACE(REPLACE(CUSTNAME,'先生',''),'小姐',''),'(WAU)','') AS SYS_NAME--, MAX(OPENDATE) AS OPEN_DATE		 
		FROM dbo.DS_BUDTRAN_VW
		WHERE LTRIM(RTRIM(CUSTID)) IN (SELECT LTRIM(RTRIM(IDNO)) FROM #IDRP_CAFORM_NONLEADING_BASE_1) 		 
		GROUP BY CUSTID, CUSTNAME
	) AS CBX
	 
 
   
    --SELECT CUSTID, CARDNMBR, CYCLEID AS CYCLEID_2, CDC AS CDC_2, '0' AS WO_FLAG_2, SPACE(3)AS DPD, LOGO AS ACCTTYPE, BUSINESS FROM CARDS;
    --WHERE ALLTRIM(CUSTID) IN (SELE ALLTRIM(IDNO) FROM IDRP_CAFORM_NONLEADING_BASE_1) INTO DBF CURRENT_CDC1
    --SELECT CUSTID AS CUSTID, CARDNMBR, CYCLEID AS CYCLEID_2, CDC AS CDC_2, '0' AS WO_FLAG_2, ALLTRIM(STR(DPD)) AS DPD, ACCTTYPE, BUSINESS FROM BUDTRAN;
    --WHERE ALLTRIM(CUSTID) IN (SELE ALLTRIM(IDNO) FROM IDRP_CAFORM_NONLEADING_BASE_1) INTO DBF CURRENT_CDC2
    --SELECT CURRENT_CDC1
    --APPEND FROM CURRENT_CDC2

 
     SELECT CDCX.CUSTID,CDCX.CARDNMBR,CDCX.CYCLEID_2,CDCX.CDC_2,IIF(B.CARDNMBR IS NOT NULL,'1','0') AS WO_FLAG_2,CDCX.DPD,CDCX.ACCTTYPE,CDCX.BUSINESS,CDCX.LOCATION INTO #CURRENT_CDC1
	 FROM (
			SELECT CUSTID, CARDNMBR, CYCLEID AS CYCLEID_2, CDC AS CDC_2,'' AS DPD, LOGO AS ACCTTYPE, BUSINESS, LOCATION  
			FROM  dbo.DS_CARDS_VW
			WHERE LTRIM(RTRIM(CUSTID)) IN (SELECT LTRIM(RTRIM(IDNO)) FROM #IDRP_CAFORM_NONLEADING_BASE_1) 
			UNION
			SELECT CUSTID AS CUSTID, CARDNMBR, CYCLEID AS CYCLEID_2, CDC AS CDC_2, LTRIM(RTRIM(CAST(DPD as VARCHAR))) AS DPD, ACCTTYPE, BUSINESS, LOCATION
			FROM dbo.DS_BUDTRAN_VW
			WHERE LTRIM(RTRIM(CUSTID)) IN (SELECT LTRIM(RTRIM(IDNO)) FROM #IDRP_CAFORM_NONLEADING_BASE_1) 
	 ) AS CDCX
	 LEFT JOIN dbo.DS_REC_COMBO_VW B ON B.CARDNMBR = CDCX.cardnmbr
	 

    --SELECT A.*, B.CARDNMBR  AS CARDNMBR_B  FROM CURRENT_CDC1 A LEFT OUTER JOIN COMBO B ON A.CARDNMBR=B.CARDNMBR INTO DBF  CURRENT_CDC3
    --UPDATE CURRENT_CDC3 SET WO_FLAG_2='1' WHERE !ISNULL(CARDNMBR_B)
    --SELE*FROM CURRENT_CDC3 WHERE INLIST(ACCTTYPE,'757','755','749') INTO DBF CARD_LOAN
    --SELE*FROM CURRENT_CDC3 WHERE BUSINESS='CTL' INTO DBF NONLEAD_BOOC
    --SELE IDNO, CARDNMBR, TTL_DEBT_I, 'CTL' AS BUSINESS FROM IDRP_DEBTDTL WHERE CARDNMBR IN (SELE CARDNMBR FROM NONLEAD_BOOC) AND TTL_DEBT_I>0 AND CATERGORY<>'有擔' INTO DBF CTL_NONRW

	--SELECT TOP 0 * INTO #REC FROM dbo.DS_REC_COMBO_VW
	--SET @WHERE = 'INNER JOIN #CURRENT_CDC1 B ON DS.CARDNMBR = B.CARDNMBR  WHERE  MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #REC EXECUTE dbo.GET_DS_SP 'REC_COMBO',@DATEAS,@WHERE ,N''
		
    --SELECT A.*, B.CARDNMBR  AS CARDNMBR_B
    --INTO #CURRENT_CDC3  
    --FROM #CURRENT_CDC1 A 
    --LEFT  JOIN dbo.DS_REC_COMBO_VW B 
    --ON A.CARDNMBR=B.CARDNMBR 



    --UPDATE #CURRENT_CDC3 
    --SET WO_FLAG_2='1' 
    --WHERE CARDNMBR_B IS NOT NULL

   -- SELECT CUSTID INTO #CARD_LOAN  FROM #CURRENT_CDC3  WHERE ACCTTYPE IN ('757','755','749') 
  --  SELECT CARDNMBR  INTO #NONLEAD_BOOC  FROM #CURRENT_CDC3   WHERE BUSINESS='CTL' 

    SELECT IDNO, CARDNMBR, TTL_DEBT_I, 'CTL' AS BUSINESS 
	INTO #CTL_NONRW
    FROM UIDRP_DE_IDRP_DEBTDTL 
    WHERE CARDNMBR IN (SELECT CARDNMBR FROM #CURRENT_CDC1 WHERE BUSINESS='CTL') AND TTL_DEBT_I > 0  AND CATEGORY <> '有擔' 



    --SELECT A.*, B.FIRST_DATE, B.PERIOD, B.RATE, B.PAYAMOUNT FROM IDRP_CAFORM_NONLEADING_BASE_1 A LEFT OUTER JOIN Z98_ZZS260 B ;
    --ON A.IDNO=B.IDN_BAN AND A.LEAD_BNK_N=B.MAIN_CODE AND TRANS_ROCDATE(A.REQ_DEBT_D)=B.REC_DATE INTO DBF IDRP_CAFORM_NONLEADING_BASE_2
    --&& 有可能有SIGN_D 但還沒下載Z98 SIGN_D又不可與DATE()比較 因為有可能BACK DATE 所以直接比對Z98
    --SELECT * FROM  IDRP_CAFORM_NONLEADING_BASE_2 WHERE !ISNULL(FIRST_DATE) AND !ISNULL(PERIOD) AND !ISNULL(RATE) AND !ISNULL(PAYAMOUNT) INTO DBF IDRP_CAFORM_NONLEADING_BASE_3
    --SELECT A.*, B.CASENO AS CASENO_B FROM IDRP_CAFORM_NONLEADING_BASE_3 A LEFT OUTER JOIN IDRP_CAFORM_NONLEADING_HIST B ON A.CASENO=B.CASENO INTO DBF IDRP_CAFORM_NONLEADING_COMPARE
    --SELECT  CASENO, IDNO, BIRTHDAY, NAME, LEAD_BNK_N, LEAD_BANK, REQ_DEBT_D, RE_DEBT_D, FIRST_DATE, PERIOD, RATE, PAYAMOUNT,CHANGE_ID FROM  IDRP_CAFORM_NONLEADING_COMPARE WHERE ISNULL(CASENO_B) INTO DBF  IDRP_CAFORM_NONLEADING_BASE_4
    --SELECT A.*, B.REG_ADDR, B.COM_ADDR, B.MOBIL_NO, B.COM_TELNO FROM IDRP_CAFORM_NONLEADING_BASE_4 A LEFT OUTER JOIN Z98_ZZS240 B ;
    --ON A.IDNO = B.IDN_BAN AND A.LEAD_BNK_N=B.MAIN_CODE AND TRANS_ROCDATE(A.REQ_DEBT_D)=B.REC_DATE INTO DBF IDRP_CAFORM_NONLEADING_MAPZZS240
    --SELECT A.*, B.STAGE_NOTE FROM IDRP_CAFORM_NONLEADING_MAPZZS240 A LEFT OUTER JOIN Z98_ZZS262 B ;
    --ON A.IDNO=B.IDN_BAN AND A.LEAD_BNK_N=B.MAIN_CODE AND TRANS_ROCDATE(A.REQ_DEBT_D)=B.REC_DATE INTO DBF IDRP_CAFORM_NONLEADING_MAPZZS262
    --SELECT A.*, B.INCOME_NOW FROM  IDRP_CAFORM_NONLEADING_MAPZZS262 A LEFT OUTER JOIN Z96_ZZS241 B ;
    --ON A.IDNO = B.IDN AND A.LEAD_BNK_N=B.MAIN_CODE AND TRANS_ROCDATE(A.REQ_DEBT_D)=B.RC_DATE INTO DBF IDRP_CAFORM_NONLEADING_MAPZZS241
    --SELECT A.*, B.DISP_AMT FROM IDRP_CAFORM_NONLEADING_MAPZZS241 A LEFT OUTER JOIN Z98_ZZM260 B ON A.IDNO=B.IDN_BAN AND A.REQ_DEBT_D=TRANS_YMD(B.REC_DATE) AND A.LEAD_BNK_N=B.MAIN_CODE  ;
    --WHERE  B.BANK_CODE IN ('021','976') INTO DBF IDRP_CAFORM_NONLEADING_MAPZZM260_1
    --SELE*, '0' AS DISP_AMT FROM IDRP_CAFORM_NONLEADING_MAPZZS241 WHERE IDNO NOT IN (SELE IDNO FROM IDRP_CAFORM_NONLEADING_MAPZZM260_1 ) INTO DBF IDRP_CAFORM_NONLEADING_MAPZZM260_N
    --SELE IDRP_CAFORM_NONLEADING_MAPZZM260_1
    --APPEND FROM IDRP_CAFORM_NONLEADING_MAPZZM260_N
	  
     INSERT INTO #IDRP_CAFORM_NONLEADING_BASE_4
     SELECT A.CASENO,A.IDNO,A.BIRTHDAY,A.NAME,A.LEAD_BNK_N,A.LEAD_BANK,A.REQ_DEBT_D,A.RE_DEBT_D, B.FIRST_DATE, B.PERIOD, B.RATE, B.PAYAMOUNT ,A.CHANGE_ID
     FROM #IDRP_CAFORM_NONLEADING_BASE_1 A 
     LEFT JOIN UIDRP_Z98_ZZS260 B ON A.IDNO=B.IDN_BAN AND A.LEAD_BNK_N=B.MAIN_CODE AND [dbo].[TRANS_ROCDATE](CAST(A.REQ_DEBT_D AS DATE)) = B.REC_DATE
	 LEFT JOIN UIDRP_IDRP_CAFORM_NONLEADING_HIST C ON A.CASENO=C.CASENO 	
	 WHERE B.FIRST_DATE IS NOT NULL AND B.PERIOD IS NOT NULL AND B.RATE IS NOT NULL AND B.PAYAMOUNT IS NOT NULL AND C.CASENO IS NULL 


    --&& 有可能有SIGN_D 但還沒下載Z98 SIGN_D又不可與DATE()比較 因為有可能BACK DATE 所以直接比對Z98
  	;WITH IDRP_CAFORM_NONLEADING_MAPZZS241 
	AS
	(
        SELECT A.*, B.REG_ADDR, B.COM_ADDR, B.MOBIL_NO, B.COM_TELNO,C.STAGE_NOTE, D.INCOME_NOW	   
		FROM #IDRP_CAFORM_NONLEADING_BASE_4 A 
		LEFT JOIN UIDRP_Z98_ZZS240 B ON A.IDNO = B.IDN_BAN AND A.LEAD_BNK_N=B.MAIN_CODE AND dbo.TRANS_ROCDATE(CAST(A.REQ_DEBT_D AS DATE))=B.REC_DATE
		LEFT JOIN UIDRP_Z98_ZZS262 C ON A.IDNO = C.IDN_BAN AND A.LEAD_BNK_N=C.MAIN_CODE AND dbo.TRANS_ROCDATE(CAST(A.REQ_DEBT_D AS DATE))=C.REC_DATE
		LEFT JOIN UIDRP_Z96_ZZS241 D ON A.IDNO = D.IDN AND A.LEAD_BNK_N=D.MAIN_CODE AND dbo.TRANS_ROCDATE(CAST(A.REQ_DEBT_D AS DATE))=D.RC_DATE 
	)
	,IDRP_CAFORM_NONLEADING_MAPZZM260_2
	AS
	(	
		SELECT A.CASENO,A.IDNO,A.BIRTHDAY,A.NAME,A.LEAD_BNK_N,A.LEAD_BANK,A.REQ_DEBT_D,A.RE_DEBT_D,A.FIRST_DATE,A.PERIOD,A.RATE,A.PAYAMOUNT,A.REG_ADDR,A.COM_ADDR,A.MOBIL_NO,A.COM_TELNO,A.INCOME_NOW,A.STAGE_NOTE, SUM(ISNULL(B.DISP_AMT,0)) AS DISP_AMT,A.CHANGE_ID
		FROM IDRP_CAFORM_NONLEADING_MAPZZS241 A 
		LEFT OUTER JOIN  UIDRP_Z98_ZZM260 B  ON A.IDNO=B.IDN_BAN AND dbo.TRANS_ROCDATE(CAST(A.REQ_DEBT_D AS DATE))=B.REC_DATE AND A.LEAD_BNK_N=B.MAIN_CODE AND B.BANK_CODE IN ('021','976') 
		GROUP BY CASENO,IDNO,BIRTHDAY,NAME,LEAD_BNK_N,LEAD_BANK,REQ_DEBT_D,RE_DEBT_D,FIRST_DATE,PERIOD,RATE,PAYAMOUNT,REG_ADDR,COM_ADDR, MOBIL_NO,COM_TELNO,INCOME_NOW,STAGE_NOTE,CHANGE_ID
	)
    SELECT A.CASENO,
	    'CTL' AS [OWNER], 
	    A.LEAD_BANK, 
		IIF(RTRIM(LTRIM(ISNULL(C.CA_CODE,''))) <>'',LTRIM(RTRIM(C.CA_CODE)),A.LEAD_BNK_N) AS LEAD_BNK_N, 
		A.NAME,
		A.IDNO, 
		A.BIRTHDAY,
		A.COM_ADDR,
		A.REG_ADDR,
		A.MOBIL_NO,
		A.COM_TELNO,
		A.REQ_DEBT_D,
		A.RE_DEBT_D, 
        LTRIM(RTRIM(A.FIRST_DATE)) AS FIRST_DATE,   
        DATEADD(MONTH,-1,dbo.TRANS_YMD(LTRIM(RTRIM(A.FIRST_DATE)))) AS OPENDATE,      
        DATEADD(MONTH,[PERIOD]-1,dbo.TRANS_YMD(LTRIM(RTRIM(A.FIRST_DATE)))) AS CLOSEDATE,
        A.INCOME_NOW, 
        A.PERIOD, 
        A.RATE, 
        A.PAYAMOUNT, 
        A.DISP_AMT, 
        SPACE(1) AS COLLECTOR, 
        A.STAGE_NOTE,
        A.CHANGE_ID,
		B.SYS_NAME,
		CAST(0 AS DECIMAL(18,2)) AS TTL_OS 
    INTO #NONLEADING_CAFORM1
    FROM IDRP_CAFORM_NONLEADING_MAPZZM260_2 A
	LEFT JOIN #SYS_NAME B ON A.IDNO=B.CUSTID
	LEFT JOIN UIDRP_IDRP_BANKCODE C ON A.LEAD_BNK_N=C.B_CODE
 

    -- ##NONLEADING_CAFORM2 = ##NONLEADING_CAFORM1 + CA_CODE
  --  SELECT A.*, B.CA_CODE
  --  INTO #NONLEADING_CAFORM2
  --  FROM #NONLEADING_CAFORM1 A 
  --  LEFT JOIN UIDRP_IDRP_BANKCODE B 
  --  ON A.LEAD_BNK_N=B.B_CODE 
	 
	 ----CA_CODE VARCHAR(100) -> LEAD_BNK_N varchar(3)
  --  UPDATE #NONLEADING_CAFORM2 
  --  SET LEAD_BNK_N=LTRIM(RTRIM(CA_CODE))
  --  WHERE CA_CODE IS NOT NULL

	 -- ##NONLEADING_CAFORM2 = #NONLEADING_CAFORM11
    --SELECT *  INTO #NONLEADING_CAFORM2 FROM #NONLEADING_CAFORM11


    -- FOXPRO 235 行之後....
	--SELECT TOP 0 * INTO #REC_2 FROM dbo.DS_REC_COMBO_VW
	--SET @WHERE = 'INNER JOIN UIDRP_DE_IDRP_DEBTDTL B ON DS.CARDNMBR = B.CARDNMBR  WHERE  MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #REC_2 EXECUTE dbo.GET_DS_SP 'REC_COMBO',@DATEAS,@WHERE ,N''



    --SELECT A.CASENO, A.IDNO, A.CARDNMBR, 'N' AS WO_FLAG, B.CARDNMBR AS CARDNMBR_B FROM IDRP_DEBTDTL A LEFT OUTER JOIN COMBO B ON A.CARDNMBR = B.CARDNMBR INTO DBF DEL_MAPBLTODAY
   ;WITH DEL_MAPBLTODAY
	AS
	(
		SELECT A.CASENO, A.IDNO, A.CARDNMBR, IIF(B.CARDNMBR IS NOT NULL,'Y','N') AS WO_FLAG, B.CARDNMBR AS CARDNMBR_B		 
		FROM UIDRP_DE_IDRP_DEBTDTL A 
		LEFT JOIN dbo.DS_REC_COMBO_VW B ON A.CARDNMBR = B.CARDNMBR
	) 
	, DEL_NONLEADING_IFWOFLG
	AS
	(
		SELECT CASENO, MAX(WO_FLAG) AS WO_FLAG     
		FROM DEL_MAPBLTODAY
		GROUP BY CASENO
	)	
	,NONLEADING_SUMMARY_TODAY1
	AS
	(
		SELECT A.CASENO, A.IDNO, A.NAME, A.PERIOD, B.WO_FLAG		 
		FROM #NONLEADING_CAFORM1 A 
		LEFT JOIN DEL_NONLEADING_IFWOFLG B ON A.CASENO=B.CASENO		
	)
	SELECT @THEDATE AS PROCDATE, B.IDNO, B.CASENO, B.NAME, B.[PERIOD], B.WO_FLAG, A.SUM_DEBT
    INTO #NONLEADING_SUMMARY_TODAY 
    FROM NONLEADING_SUMMARY_TODAY1 B 
	INNER JOIN (SELECT TTL_DEBT_I AS SUM_DEBT,IDNO FROM UIDRP_DE_IDRP_DEBTDTL WHERE CATEGORY <> '有擔') A ON A.IDNO = B.IDNO 
    GROUP BY B.IDNO, B.CASENO, B.NAME, B.[PERIOD], B.WO_FLAG, A.SUM_DEBT


    --SELECT SUM(TTL_DEBT_I) AS SUM_DEBT, *  FROM IDRP_DEBTDTL WHERE CATERGORY<>'有擔' GROUP BY CASENO, IDNO INTO DBF TEMP3
    -- SELECT SUM(TTL_DEBT_I) AS SUM_DEBT, *
    -- INTO #TEMP3
    -- FROM UIDRP_DE_IDRP_DEBTDTL
    -- WHERE CATEGORY <> '有擔'
    -- GROUP BY CASENO, IDNO

    --由於 CASENO 與 IDNO 在Table中是唯一鍵值，故修改為...
   

    --249
  
    --CREATE CURSOR ACCTDTL(CASENO C(20), IDNO C(10), BANKCODE C(3), CARDNMBR C(16), ACCOUNTTYP C(3), OS1 N(8,2), PRINCIPALA N(8,2), INTEREST N(8,2), LATEFEE N(8,2), LEGALFEE N(8,2), PENALTY C(1), DELQBKT C(1), WO C(1), CYCLEID_2 C(2), CDC_2 N(2), WO_FLAG_2 C(1), DPD C(3))

    --251
    -- SELECT NONLEADING_CAFORM1
    -- SCAN &&For inlist(idno, 'F22xx') &&,'F223xx89','F125xx2')
    -- SCATTER MEMVAR

    -- IF DATE()<{^2015/02/01}
    --     SELECT CASENO, IDNO, IIF(SUBSTR(ALLTRIM(CARDNMBR),1,2)='36', '976','021') AS BANKCODE, CARDNMBR, PRODTYPE AS ACCOUNTTYPE, TTL_DEBT_I AS OS1, CURR_P AS PRINCIPALAMOUNT,;
    --     CURR_INT AS INTEREST, CURR_FEE AS LATEFEE, CURR_OTH AS LEGALFEE, SPACE(1) AS PENALTY, CDC AS DELQBKT, WO_FLAG AS WO, CURR_P_I, CURR_I_I, CURR_F_I, CURR_O_I;
    --     FROM  IDRP_DEBTDTL WHERE IDNO=M.IDNO AND CASENO=M.CASENO AND CATERGORY<>'有擔' INTO DBF CURSOR_CAFORM_DATA21  &&取消AND TTL_DEBT_I>0
    --     ELSE
    --     SELECT CASENO, IDNO, '021' AS BANKCODE, CARDNMBR, PRODTYPE AS ACCOUNTTYPE, TTL_DEBT_I AS OS1, CURR_P AS PRINCIPALA,;
    --     CURR_INT AS INTEREST, CURR_FEE AS LATEFEE, CURR_OTH AS LEGALFEE, SPACE(1) AS PENALTY, CDC AS DELQBKT, WO_FLAG AS WO, CURR_P_I, CURR_I_I, CURR_F_I, CURR_O_I;
    --     FROM  IDRP_DEBTDTL WHERE IDNO=M.IDNO AND CASENO=M.CASENO AND CATERGORY<>'有擔' INTO DBF CURSOR_CAFORM_DATA21  &&取消AND TTL_DEBT_I>0
    -- ENDIF

    --SELECT TOP 0 * INTO #MAX_CDC FROM UIDRP_MAX_CAFORM_CDC
    --SELECT TOP 0 *, '' as RW_FLAG INTO #DATA1 FROM #NONLEADING_CAFORM1

	 
	UPDATE #NONLEADING_CAFORM1 
            SET LEAD_BANK='渣打國際商業銀行',  LEAD_BNK_N='052' 
            WHERE LEAD_BNK_N='083'

    DECLARE CSR_CAFORM1 CURSOR FOR
    SELECT  CASENO, IDNO, REQ_DEBT_D, LEAD_BNK_N FROM #NONLEADING_CAFORM1

    OPEN CSR_CAFORM1
    FETCH NEXT FROM CSR_CAFORM1 INTO @CSR1_CASENO ,@CSR1_IDNO, @CSR1_REQ_DEBT_D, @CSR1_LEAD_BNK_N

    WHILE(  @@FETCH_STATUS = 0 )
        BEGIN
            --DECLARE @CURSOR_CAFORM_DATA21 TABLE(
            --      CASENO BIGINT
            --    , IDNO varchar(10)
            --    , BANKCODE varchar(3)
            --    , CARDNMBR varchar(16)
            --    , ACCOUNTTYPE varchar(3)
            --    , OS1 decimal(18,2)
            --    , PRINCIPALA decimal(18,2)
            --    , INTEREST decimal(18,2)
            --    , LATEFEE decimal(18,2)
            --    , LEGALFEE decimal(18,2)
            --    , PENALTY varchar(1)
            --    , DELQBKT varchar(1)
            --    , WO varchar(1)
            --    , CURR_P_I decimal(18,2)
            --    , CURR_I_I decimal(18,2)
            --    , CURR_F_I decimal(18,2)
            --    , CURR_O_I decimal(18,2)
            --)
 
           -- INSERT INTO @CURSOR_CAFORM_DATA21
			IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA21')IS NOT NULL) 
			    DROP TABLE #CURSOR_CAFORM_DATA21

            SELECT  A.CASENO, A.IDNO, IIF(@THEDATE < CAST('2015/02/01' AS DATE) AND SUBSTRING(LTRIM(RTRIM(A.CARDNMBR)),1,2)='36', '976','021') AS BANKCODE
			, A.CARDNMBR, A.PRODTYPE AS ACCOUNTTYPE, A.TTL_DEBT_I AS OS1
			, A.CURR_P AS PRINCIPALA, A.CURR_INT AS INTEREST, A.CURR_FEE AS LATEFEE, A.CURR_OTH AS LEGALFEE
			, SPACE(1) AS PENALTY , A.CDC AS DELQBKT, A.WO_FLAG AS WO, A.CURR_P_I, A.CURR_I_I, A.CURR_F_I, A.CURR_O_I
			INTO #CURSOR_CAFORM_DATA21
            FROM UIDRP_DE_IDRP_DEBTDTL A
            WHERE A.IDNO= @CSR1_IDNO AND A.CASENO= @CSR1_CASENO AND A.CATEGORY <> '有擔'
			
            

            UPDATE #CURSOR_CAFORM_DATA21 SET PRINCIPALA=CURR_P_I, INTEREST=CURR_I_I, LATEFEE=CURR_F_I, LEGALFEE=CURR_O_I WHERE CURR_P_I>0
            UPDATE #CURSOR_CAFORM_DATA21 SET PRINCIPALA=OS1, INTEREST=0, LATEFEE=0, LEGALFEE=0 WHERE CURR_P_I=0 AND OS1<>INTEREST+LATEFEE+LEGALFEE AND WO='Y'
            UPDATE #CURSOR_CAFORM_DATA21 SET PRINCIPALA=ROUND(PRINCIPALA,0),INTEREST=ROUND(INTEREST,0),LATEFEE=ROUND(LATEFEE,0),LEGALFEE=ROUND(LEGALFEE,0) WHERE WO='N'

            --CHECK Z98 AND 債金檔 看是否 MATCH
            -- SELECT IDNO , ROUND(SUM(TTL_DEBT_I),0) AS  TTL_DEBT_I  FROM IDRP_DEBTDTL WHERE CATERGORY<>'有擔' AND IDNO=M.IDNO AND CASENO=M.CASENO  INTO DBF  CAFORM_CHECKDEBT_1
            -- SELECT A.*, B.EXP_LOAN+B.CASH_CARD+B.CREDITCARD AS Z98_DEBT FROM CAFORM_CHECKDEBT_1 A LEFT OUTER JOIN  Z98_ZZM260 B ON A.IDNO=B.IDN_BAN WHERE B.BANK_CODE IN ('021','976') INTO DBF CAFORM_CHECKDEBT_2
            -- SELECT IDNO, SUM(Z98_DEBT) AS Z98_DEBT, TTL_DEBT_I FROM CAFORM_CHECKDEBT_2 GROUP BY IDNO INTO DBF CAFORM_CHECKDEBT_3 

			;WITH CAFORM_CHECKDEBT_1
			AS
			(
				SELECT IDNO , ROUND(SUM(OS1),0) AS  TTL_DEBT_I            
				FROM #CURSOR_CAFORM_DATA21 				 
				GROUP BY IDNO
			)
			,CAFORM_CHECKDEBT_2
			AS
			(
				SELECT A.*, B.EXP_LOAN+B.CASH_CARD+B.CREDITCARD AS Z98_DEBT				 
				FROM CAFORM_CHECKDEBT_1 A 
				LEFT JOIN UIDRP_Z98_ZZM260 B ON A.IDNO=B.IDN_BAN 
				WHERE B.BANK_CODE IN ('021','976')			
			)
			,CAFORM_CHECKDEBT_3
			AS
			(				
				SELECT IDNO, SUM(Z98_DEBT) AS Z98_DEBT, TTL_DEBT_I 				
				FROM CAFORM_CHECKDEBT_2 GROUP BY IDNO,TTL_DEBT_I 
			)
			INSERT INTO UIDRP_CHECKDEBT  SELECT * FROM CAFORM_CHECKDEBT_3
		
		    IF(OBJECT_ID('TEMPDB..#CAFORM_DATA4')IS NOT NULL) 
			    DROP TABLE #CAFORM_DATA4

            SELECT A.*, B.CYCLEID_2, B.CDC_2, B.WO_FLAG_2, B.DPD 
            INTO #CAFORM_DATA4
            FROM #CURSOR_CAFORM_DATA21 A 
            LEFT OUTER JOIN #CURRENT_CDC1 B ON A.CARDNMBR=B.CARDNMBR

            -- 20080926 GRACE 要求將CURRENT WO 的情形丟到 DATA跑CAFORM
            UPDATE #CAFORM_DATA4 SET WO='N' WHERE WO_FLAG_2='0'
            UPDATE #CAFORM_DATA4 SET WO='Y' WHERE WO_FLAG_2='1'

            --SELECT *    INTO #CAFORM_DATA60    FROM #CAFORM_DATA4            
            

            -- SELE BANK_TAG, SUM(OS1) AS TOTAL_OS1 FROM CAFORM_DATA6_1 GROUP BY BANK_TAG INTO DBF CAFORM_DATA6_2
            -- SELE*FROM CAFORM_DATA6_2 WHERE TOTAL_OS1<5000 INTO DBF CAFORM_DATA6_3	&&SMALL BALANCE
            -- SELE CARDNMBR FROM CAFORM_DATA6_1 WHERE BANK_TAG IN (SELE BANK_TAG FROM CAFORM_DATA6_3) INTO DBF CAFORM_DATA6_4
            -- SELECT IDNO ,BANKCODE, CARDNMBR, ACCOUNTTYP, OS1, PRINCIPALA, INTEREST, LATEFEE, LEGALFEE, PENALTY, DELQBKT, WO, CYCLEID_2, CDC_2, WO_FLAG_2, DPD FROM CAFORM_DATA6 WHERE CARDNMBR NOT IN (SELE CARDNMBR FROM CAFORM_DATA6_4) AND  CARDNMBR NOT IN (SELE CARDNMBR FROM G99)  INTO DBF CAFORM_DATA5
            -- SELECT BANKCODE, CARDNMBR, ACCOUNTTYP, OS1, PRINCIPALA, INTEREST, LATEFEE, LEGALFEE, PENALTY, DELQBKT, WO, CYCLEID_2, CDC_2, WO_FLAG_2, DPD FROM CAFORM_DATA5  INTO DBF CAFORM_DATA7
            -- UPDATE CAFORM_DATA7 SET BANKCODE='021' WHERE BANKCODE='976'
			IF(OBJECT_ID('TEMPDB..#CAFORM_DATA5')IS NOT NULL) 
			    DROP TABLE #CAFORM_DATA5
            IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6')IS NOT NULL) 
			    DROP TABLE #CAFORM_DATA6
			IF(OBJECT_ID('TEMPDB..#CAFORM_DATA6_2')IS NOT NULL) 
			    DROP TABLE #CAFORM_DATA6_2
	               
			SELECT *, CASE WHEN @THEDATE < CONVERT(DATE, '2015/02/01', 111) AND SUBSTRING(CARDNMBR,1,2)='36' THEN '976' ELSE '021' END AS BANK_TAG     
			INTO #CAFORM_DATA6        
			FROM #CAFORM_DATA4
			WHERE SUBSTRING(LTRIM(RTRIM(WO_FLAG_2)),1,1) NOT IN ('D', 'A', '9' ) 
				OR SUBSTRING(LTRIM(RTRIM(WO_FLAG_2)),1,2) IN ('96', '97' ) 
				OR SUBSTRING(LTRIM(RTRIM(WO_FLAG_2)),1,3) IN ('941', '993' ) 
				OR WO_FLAG_2 IS NOT NULL
			 
	 	 
			SELECT BANK_TAG, SUM(OS1) AS TOTAL_OS1  
			INTO #CAFORM_DATA6_2          
			FROM #CAFORM_DATA6 GROUP BY BANK_TAG
			 			 
		    
			UPDATE #NONLEADING_CAFORM1 SET TTL_OS=(SELECT TOP 1 TOTAL_OS1 FROM #CAFORM_DATA6_2)
			WHERE CURRENT OF CSR_CAFORM1
			--WHERE IDNO= @CSR1_IDNO AND CASENO= @CSR1_CASENO
			 
			--#NONLEADING_CAFORM1
			-- UPDATE TTL_OS = TOTAL_OS1
			--CAFORM_DATA7 =#EXP_DATA2 =ACCTDTL
			      
            SELECT CASENO,IDNO ,BANKCODE, CARDNMBR, ACCOUNTTYPE, OS1, PRINCIPALA, INTEREST, LATEFEE, LEGALFEE, PENALTY, DELQBKT, WO, CYCLEID_2, CDC_2, WO_FLAG_2, DPD
            INTO #CAFORM_DATA5
            FROM #CAFORM_DATA6 
            WHERE BANK_TAG NOT IN (SELECT BANK_TAG FROM #CAFORM_DATA6_2 WHERE TOTAL_OS1 < 5000) 
            AND CARDNMBR NOT IN (SELECT CARDNMBR FROM UIDRP_NA_G99_HIST)

         	
            INSERT INTO #ACCTDTL SELECT CASENO,IDNO,(CASE WHEN BANKCODE='976' THEN '021' ELSE BANKCODE END) AS BANKCODE, CARDNMBR, ACCOUNTTYPE, OS1, PRINCIPALA, INTEREST, LATEFEE, LEGALFEE
            , PENALTY, DELQBKT, WO, CYCLEID_2, CDC_2, WO_FLAG_2, DPD  FROM #CAFORM_DATA5 WHERE CYCLEID_2 IS NOT NULL AND ISNULL(CDC_2,0) > 0

            --DATA2 EXPORT
            --COPY TO 'M:\RESULT\IDRP\NA\CAFORM\NONLEADING\'+M.IDNO+'_'+DTOS(THEDATE)+'_DATA2' XL5

            --313****DECIDE ACCOUNT TYPE****
			--IF(OBJECT_ID('TEMPDB..#RW_TYPE')IS NOT NULL)   DROP TABLE #RW_TYPE
	        IF(OBJECT_ID('TEMPDB..#RW_TYPE1')IS NOT NULL)   DROP TABLE #RW_TYPE1
            --IF(OBJECT_ID('TEMPDB..#RW_TYPE2')IS NOT NULL)   DROP TABLE #RW_TYPE2

			--****DECIDE ACCOUNT TYPE*********************************************************************************************************
            --SELECT * INTO #RW_TYPE FROM #CAFORM_DATA5 WHERE LEN(ISNULL(CARDNMBR,'')) > 0 
           -- UPDATE #RW_TYPE SET DELQBKT='0' WHERE LEN(ISNULL(DELQBKT,'')) = 0

            SELECT A.IDNO, A.CARDNMBR, CONVERT(INT, IIF(LEN(ISNULL(DELQBKT,''))=0,'0',DELQBKT)) AS DELQBKT, A.OS1, A.CDC_2, A.ACCOUNTTYPE, ISNULL(B.BUSINESS,'NA') AS BUSINESS, B.LOCATION
            INTO #RW_TYPE1
            FROM #CAFORM_DATA5 A
            LEFT JOIN #CURRENT_CDC1 B ON A.CARDNMBR=B.CARDNMBR
			WHERE LEN(ISNULL(A.CARDNMBR,'')) > 0 

            --UPDATE #RW_TYPE1 SET BUSINESS='NA' WHERE BUSINESS IS NULL

            IF ((SELECT count(*) FROM #RW_TYPE1) > 0)
                BEGIN
                    IF CONVERT(DATETIME, @CSR1_REQ_DEBT_D, 111) >= CONVERT(DATETIME ,'2011/09/01', 111)
                        BEGIN
                            --DO ACCTTYPE2

                         	--SELECT * FROM #RW_TYPE1 GROUP BY IDNO INTO CURSOR CHK_RW
							IF ((SELECT COUNT(DISTINCT IDNO) FROM #RW_TYPE1) = 1)
							BEGIN
							    --M.IDNO=@CHK_BAL1_IDNO

								DECLARE @M_RW_TYPE VARCHAR(3),@CHK_BAL1_IDNO VARCHAR(10),@PCL_COUNT INT
                                
								--SELECT * FROM #RW_TYPE1 GROUP BY IDNO INTO ARRAY CHK_BAL1
								SELECT DISTINCT TOP 1 @CHK_BAL1_IDNO=IDNO FROM #RW_TYPE1

								;WITH CHK_RW
								AS
								(
									SELECT IDNO,CARDNMBR,OS1 FROM #RW_TYPE1 WHERE SUBSTRING(CARDNMBR,1,2) < '36' AND OS1 > 0
								)
								,RW_PCL_1
								AS
								(
									--1. ALS Acct and PCL_RW_hist
									SELECT IDNO FROM CHK_RW
									WHERE CARDNMBR IN (SELECT RW_ACCT FROM #RW_ACCTLIST)
									  AND CARDNMBR IN (SELECT CARDNMBR FROM #RW_ACCTLIST WHERE SUBSTRING(LOCATION,1,6) IN ('020007','020107') OR SUBSTRING(LOCATION,1,2) IN ('86','88'))						 
								 
								)
								,CHK_DEBT     --2.  ALS Acct and NO PCL_RW_HIST-->CHECK S91
								AS
								(
								   SELECT IDNO FROM CHK_RW  
								   WHERE CARDNMBR IN (SELECT RW_ACCT FROM #RW_ACCTLIST)							
								)						 
								,RW_PCL_2
								AS
								(
									SELECT IDNO FROM CHK_DEBT A 
									INNER JOIN dbo.DS_CARDS_VW DS ON DS.ID_TAG = A.IDNO AND SUBSTRING(DS.LOCATION,1,6) IN ('020007','020107') AND SUBSTRING(DS.CACS_STATE,1,2)='S9' 								 
								)
								,RW_BK_1
								AS
								(
									SELECT IDNO FROM CHK_DEBT A 
									INNER JOIN dbo.DS_CARDS_VW DS ON DS.ID_TAG = A.IDNO AND SUBSTRING(DS.LOCATION,1,6) NOT IN ('020007','020107') AND SUBSTRING(DS.CACS_STATE,1,2)='S9' 
								)					
								,RW_PCL_3 --3.  ALS Acct and NO RW_HIST and no S9 and No BK acct
								AS
								(
									SELECT A.IDNO FROM CHK_RW A
									WHERE A.IDNO NOT IN (SELECT IDNO FROM RW_PCL_1)
									  AND A.IDNO NOT IN (SELECT IDNO FROM RW_PCL_2)
									  AND A.IDNO NOT IN (SELECT ID_TAG FROM #RW_ACCTLIST D WHERE SUBSTRING(D.LOCATION,1,6) NOT IN ('020007','020107') AND SUBSTRING(D.LOCATION,1,2) NOT IN ('86','88')) 
									  AND A.IDNO NOT IN (SELECT IDNO FROM RW_BK_1)								 							 
								)
								,RW_PCL_4 --4. 只有純ECMS Acct
								AS
								(
									SELECT IDNO FROM #RW_TYPE1 
									WHERE SUBSTRING(LOCATION,1,6) IN ('020007','020107','860107') 
									  AND IDNO NOT IN (SELECT IDNO FROM CHK_RW) AND OS1>0  
								)
								SELECT @PCL_COUNT= COUNT(*) FROM 
								(   SELECT IDNO FROM RW_PCL_1
									UNION
									SELECT IDNO FROM RW_PCL_2
									UNION 
									SELECT IDNO FROM RW_PCL_3
									UNION 
									SELECT IDNO FROM RW_PCL_4  ) AS PCL

								IF @PCL_COUNT > 0
									 SET @M_RW_TYPE='373'
								ELSE
									 SET @M_RW_TYPE='350'  --純BK Account客戶

							    INSERT INTO UIDRP_CA_DATA2  VALUES( @CHK_BAL1_IDNO, @M_RW_TYPE)
							END
                        END
                    ELSE
                        BEGIN
                            --DO ACCTTYPE1
							
							--IF(OBJECT_ID('TEMPDB..#RW_TYPE2')IS NOT NULL) BEGIN DROP TABLE #RW_TYPE2 END
                            --IF(OBJECT_ID('TEMPDB..#TEMP_RW')IS NOT NULL) BEGIN DROP TABLE #TEMP_RW END
							--IF(OBJECT_ID('TEMPDB..#TEMP_RW_1')IS NOT NULL) BEGIN DROP TABLE #TEMP_RW_1 END

                           -- CREATE TABLE #RW_TYPE2( IDNO varchar(10), RW_TYPE varchar(3) )

                           -- SELECT IDNO INTO #TEMP_RW FROM #RW_TYPE1 WHERE BUSINESS='CTL'
                            SET @G1= (SELECT count(*) FROM #RW_TYPE1 WHERE BUSINESS='CTL')
                           -- SELECT IDNO INTO #TEMP_RW_1 FROM #RW_TYPE1 WHERE BUSINESS='NA'
                            SET @G2= (SELECT count(*) FROM #RW_TYPE1 WHERE BUSINESS='NA')
                                        
                             IF @G1>0 AND @G2>0
                             BEGIN
                                    SET @NA_DQ = (SELECT MAX(DELQBKT) as DELQBKT FROM #RW_TYPE1 WHERE BUSINESS='NA') --ARRAY NA
                                    SET @CTL_DQ = (SELECT MAX(DELQBKT) as DELQBKT FROM #RW_TYPE1 WHERE BUSINESS='CTL') -- ARRAY CTL
                                    SET @NA1_OS1 = (SELECT MAX(OS1) as OS1 FROM #RW_TYPE1 WHERE BUSINESS='NA') -- ARRAY NA1
                                    SET @CTL1_OS1 = (SELECT MAX(OS1) as OS1 FROM #RW_TYPE1 WHERE BUSINESS='CTL') -- ARRAY CTL1

									 
									INSERT INTO UIDRP_CA_DATA2
									SELECT IDNO,CASE WHEN  @NA_DQ > @CTL_DQ THEN '350' WHEN @NA_DQ < @CTL_DQ THEN '370' WHEN @NA1_OS1 >= @CTL1_OS1 THEN '350' ELSE '370' END
                                    FROM #RW_TYPE1 
                                    GROUP BY IDNO
                                     
							 END
						 
							 IF @G1>0 AND @G2=0
							 BEGIN
							    
								INSERT INTO UIDRP_CA_DATA2
									SELECT IDNO,'370' 	
                                    FROM #RW_TYPE1 
                                    GROUP BY IDNO							 
							 END
                                     
							 IF @G1=0 AND @G2>0
							 BEGIN
							   INSERT INTO UIDRP_CA_DATA2
									SELECT IDNO,'350' 	
                                    FROM #RW_TYPE1 
                                    GROUP BY IDNO		
							 END	
							 
                        END
                END

            -- *********** CHECK 是否可以REWRITE************
            -- SELECT *, {//} AS CYCDATE, SPACE(1) AS IFREWRITE, SPACE(1) AS RW_FLAG  FROM CAFORM_DATA5 INTO DBF CHK_IFRW0
            -- SELE A.*, B.STAGE_NOTE,CHANGE_ID FROM CHK_IFRW0 A LEFT OUTER JOIN NONLEADING_CAFORM2 B ON A.IDNO=B.IDNO INTO DBF CHK_IFRW
			IF(OBJECT_ID('TEMPDB..#CHK_IFRW')IS NOT NULL)   DROP TABLE #CHK_IFRW
	      
            SELECT A.*, CAST(NULL as DATE) AS CYCDATE, SPACE(1) AS IFREWRITE, SPACE(1) AS RW_FLAG ,B.STAGE_NOTE, B.CHANGE_ID 
            INTO #CHK_IFRW
            FROM #CAFORM_DATA5 AS A
			LEFT JOIN #NONLEADING_CAFORM1 B ON A.IDNO=B.IDNO
		 

			----------------------------------------------------------------------------------------------------------------------------------------------------------------
			--CYCLEID_2 tinyint,CDC_2 tinyint, ACCOUNTTYPE varchar(3),CYCDATE DATE,WO_FLAG_2 varchar,DPD varchar(3),IFREWRITE varchar,STAGE_NOTE varchar,CARDNMBR varchar(16)
           
            -- **CARD LOAN**                             yyyy/mm/dd 		
            UPDATE #CHK_IFRW SET CYCDATE = CAST(DATEADD(day,CYCLEID_2,GETDATE()) AS DATE) WHERE  CYCLEID_2 IS NOT NULL
            UPDATE #CHK_IFRW SET CYCDATE = NULL WHERE CYCLEID_2 IS NULL
				-- 2017/5/4 如果CYCDATE 小於今天，就改成帶下一個CYCDATE 
			UPDATE #CHK_IFRW SET CYCDATE = DATEADD(month,1,CYCDATE) WHERE CYCLEID_2 IS NOT NULL AND CYCDATE IS NOT NULL AND CYCDATE < CAST(GETDATE() AS DATE)	
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE CDC_2 IS NOT NULL AND CDC_2>=5 AND ACCOUNTTYPE IN ('757','755','749') AND CYCDATE IS NOT NULL
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE CDC_2 IS NOT NULL AND CDC_2=4 AND ACCOUNTTYPE IN ('757','755','749') AND CYCDATE IS NOT NULL AND DATEDIFF(day,@THEDATE, CYCDATE)<=5 AND CYCDATE>DATEADD(day,-4, @THEDATE)           
            UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE CDC_2 IS NOT NULL AND CDC_2=4 AND ACCOUNTTYPE IN ('757','755','749') AND CYCDATE IS NOT NULL AND ((DATEDIFF(day,@THEDATE, CYCDATE)<=5 AND CYCDATE<@THEDATE) OR DATEDIFF(day,@THEDATE, CYCDATE)>5 OR  DATEDIFF(day,@THEDATE, CYCDATE)<0)
            UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE CDC_2 IS NOT NULL AND CDC_2<4 AND ACCOUNTTYPE IN ('757','755','749') AND CYCDATE IS NOT NULL AND WO_FLAG_2='0' 
        

            --**NON CARD LOAN**r
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE CDC_2 IS NOT NULL AND CDC_2>=7 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE CDC_2 IS NOT NULL AND CDC_2=6  AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND DATEDIFF(day,@THEDATE, CYCDATE)<=5 AND CYCDATE>DATEADD(day,-4, @THEDATE)
            UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE CDC_2 IS NOT NULL AND CDC_2=6 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND (DATEDIFF(day,@THEDATE, CYCDATE) < 0  OR  DATEDIFF(day,@THEDATE, CYCDATE) > 5)
			UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE CDC_2 IS NOT NULL AND CDC_2<6 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND WO_FLAG_2='0' 


            UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE DPD IS NOT NULL AND LEN( LTRIM( RTRIM( DPD ) ) ) > 0 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND ((CAST(DPD AS INT)>=120 AND WO_FLAG_2='0') OR CAST(DPD AS INT)<120)  
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE DPD IS NOT NULL AND LEN( LTRIM( RTRIM( DPD ) ) ) > 0 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND CAST(DPD AS INT)+DAY(EOMONTH(GETDATE()))-DAY(@THEDATE)>=120 AND DAY(@THEDATE)>19 
            UPDATE #CHK_IFRW SET IFREWRITE ='Y' WHERE DPD IS NOT NULL AND LEN( LTRIM( RTRIM( DPD ) ) ) > 0 AND ACCOUNTTYPE NOT IN ('757','755','749') AND CYCDATE IS NOT NULL AND LEN( LTRIM( RTRIM( IFREWRITE ) ) ) = 0 
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE STAGE_NOTE='1' 
            UPDATE #CHK_IFRW SET IFREWRITE =' ' WHERE CYCDATE IS NULL
            UPDATE #CHK_IFRW SET IFREWRITE ='N' WHERE WO_FLAG_2='1' OR CARDNMBR IN (SELECT CARDNMBR FROM DS_REC_COMBO_VW)
         

            -- SELECT * INTO #CHK_IFRW2 FROM #CHK_IFRW WHERE IFREWRITE = 'N'
			SET @RW_FLAG=''
            --364
               IF EXISTS (SELECT IFREWRITE FROM #CHK_IFRW WHERE IFREWRITE = 'N')
                BEGIN
                    SET @RW_FLAG='N'                    
                END
            ELSE
                BEGIN
                    SET @RW_FLAG='Y'                
                END						
			UPDATE #CHK_IFRW SET RW_FLAG=@RW_FLAG		

            IF @RW_FLAG='Y'
                BEGIN
                    INSERT INTO UIDRP_WAIVE_S98_NOW --P.s FoxPro原始碼中，是將CARDNMBR資料寫入Table中的ACCTNMBR欄位
                    SELECT IDNO, CARDNMBR, OS1 AS CARD_BAL, PRINCIPALA AS IDRP_P, 'S98' AS WAIVE_KIND  
                    FROM #CAFORM_DATA5 WHERE CDC_2 IS NOT NULL 
                    AND LEN(LTRIM(RTRIM(ISNULL(DPD,'')))) = 0 
                END
 
			----------------------------------------------------------------------------------------------------------------------------------------------------------------

            --*********** CHECK 是否可以REWRITE************381
            --UPDATE #NONLEADING_CAFORM1 
            --SET LEAD_BANK='渣打國際商業銀行',  LEAD_BNK_N='052' 
           -- WHERE LEAD_BNK_N='083'

			--IF(OBJECT_ID('TEMPDB..#WW')IS NOT NULL)   DROP TABLE #WW

           -- SELECT RW_FLAG AS W INTO #WW FROM #CHK_IFRW


            --創建空Table以供 INSERT
			--IF(OBJECT_ID('TEMPDB..#DTA_TEMP')IS NOT NULL)   DROP TABLE #DTA_TEMP
           -- IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA100')IS NOT NULL)   DROP TABLE #CURSOR_CAFORM_DATA100


           -- SELECT TOP 0 * INTO #CURSOR_CAFORM_DATA1 FROM #NONLEADING_CAFORM2
           -- SELECT *, '' as RW_FLAG INTO #DTA_TEMP FROM #NONLEADING_CAFORM1
           -- SELECT TOP 0 * INTO #CURSOR_CAFORM_DATA100 FROM #DTA_TEMP
            --#DATA1移至 CURSOR 外先做好
            --SELECT TOP 0 * INTO #DATA1 FROM #CURSOR_CAFORM_DATA100

           -- DROP TABLE #DTA_TEMP

            --IF (SELECT TOP 1 W FROM #WW)='Y'
			 IF @RW_FLAG='Y'
                BEGIN
				  	/*
                    INSERT INTO #CURSOR_CAFORM_DATA1
                    SELECT 
                        OWNER AS PROCESSOWNER,
                        LEAD_BANK  AS 最大債權銀行,
                        LEAD_BNK_N AS 最大債權代號,
                        NAME AS 客戶名稱,
                        IDNO AS 客戶身分證字號,
                        BIRTHDAY AS 生日,
                        COM_ADDR AS 通訊住址,
                        REG_ADDR AS 戶籍地址,
                        MOBIL_NO AS KV ,
                        COM_TELNO AS PV,
                        REQ_DEBT_D AS 協商申請日,
                        CONVERT(VARCHAR, RE_DEBT_D) AS 呈報債權日,
                        FIRST_DATE AS 首期繳款日 ,
                        OPENDATE,
                        CLOSEDATE,
                        (CAST(INCOME_NOW as INT)*12) AS 年收入,
                        PERIOD AS TENOR,
                        RATE AS  APR,
                        PAYAMOUNT AS  INSTALMENT,
                        DISP_AMT AS MONTHLYPAYMENT,
                        COLLECTOR AS   COLLECTORID,
                        SYS_NAME AS 系統姓名,
                        STAGE_NOTE AS 二階段註記,
                        'Y' AS RW_FLAG,
                        CHANGE_ID
                    FROM #NONLEADING_CAFORM2 
                    WHERE @CSR1_IDNO=IDNO  AND @CSR1_REQ_DEBT_D=REQ_DEBT_D
					*/
				 
                
                    INSERT INTO UIDRP_CA_DATA1
                    SELECT [OWNER],[LEAD_BANK],[LEAD_BNK_N]
					      ,[NAME],[IDNO],[BIRTHDAY],[COM_ADDR],[REG_ADDR],[MOBIL_NO],[COM_TELNO]
					      ,[REQ_DEBT_D],[RE_DEBT_D],[FIRST_DATE],[OPENDATE],[CLOSEDATE]
						  ,(CAST(INCOME_NOW as INT)*12) AS INCOME_NOW
						  ,[PERIOD],[RATE],[PAYAMOUNT],[DISP_AMT]
						  ,[COLLECTOR],[SYS_NAME],[STAGE_NOTE]
						  ,'Y' AS RW_FLAG
						  ,[CHANGE_ID]
                    FROM #NONLEADING_CAFORM1 
                    WHERE @CSR1_IDNO=IDNO AND @CSR1_REQ_DEBT_D=REQ_DEBT_D

                   -- INSERT INTO UIDRP_CA_DATA1
                   -- SELECT * FROM #CURSOR_CAFORM_DATA100
                    -- SELECT #CURSOR_CAFORM_DATA100
                    -- SCAN
                    --     SCATTER MEMVAR
                    --     SELECT DATA1
                    --     APPEND BLANK
                    --     GATHER MEMVAR
                    -- ENDSCAN
                END
            ELSE
                BEGIN
					/*
                    INSERT INTO #CURSOR_CAFORM_DATA1
                    SELECT 
                        OWNER AS PROCESSOWNER,
                        LEAD_BANK  AS 最大債權銀行,
                        LEAD_BNK_N AS 最大債權代號,
                        NAME AS 客戶名稱,
                        IDNO AS 客戶身分證字號,
                        BIRTHDAY AS 生日,
                        COM_ADDR AS 通訊住址,
                        REG_ADDR AS 戶籍地址,
                        MOBIL_NO AS KV ,
                        COM_TELNO AS PV,
                        REQ_DEBT_D AS 協商申請日,
                        CONVERT(VARCHAR, RE_DEBT_D) AS 呈報債權日,
                        FIRST_DATE AS 首期繳款日 ,
                        OPENDATE,
                        CLOSEDATE,
                        (CAST(INCOME_NOW as INT)*12) AS 年收入,
                        PERIOD AS TENOR,
                        RATE AS  APR,
                        PAYAMOUNT AS  INSTALMENT,
                        DISP_AMT AS MONTHLYPAYMENT,
                        COLLECTOR AS   COLLECTORID, 
                        SYS_NAME AS 系統姓名,
                        STAGE_NOTE AS 二階段註記,
                        'N' AS RW_FLAG,
                        CHANGE_ID
                    FROM #NONLEADING_CAFORM2 
                    WHERE @CSR1_IDNO=IDNO AND @CSR1_REQ_DEBT_D=REQ_DEBT_D
					*/
					
                    INSERT INTO UIDRP_CA_DATA1
                    SELECT [OWNER],[LEAD_BANK],[LEAD_BNK_N]
					      ,[NAME],[IDNO],[BIRTHDAY],[COM_ADDR],[REG_ADDR],[MOBIL_NO],[COM_TELNO]
					      ,[REQ_DEBT_D],[RE_DEBT_D],[FIRST_DATE],[OPENDATE],[CLOSEDATE]
						  ,(CAST(INCOME_NOW as INT)*12) AS INCOME_NOW
						  ,[PERIOD],[RATE],[PAYAMOUNT],[DISP_AMT]
						  ,[COLLECTOR],[SYS_NAME],[STAGE_NOTE]
						  ,'N' AS RW_FLAG
						  ,[CHANGE_ID]
                    FROM #NONLEADING_CAFORM1 
                    WHERE @CSR1_IDNO=IDNO AND @CSR1_REQ_DEBT_D=REQ_DEBT_D

                    
                    --INSERT INTO #CURSOR_CAFORM_DATA100
                    --SELECT *, 'N' AS RW_FLAG
                    --FROM #NONLEADING_CAFORM1 
                    --WHERE @CSR1_IDNO=IDNO AND @CSR1_REQ_DEBT_D=REQ_DEBT_D
                    
                    --INSERT INTO UIDRP_CA_DATA1
                    --SELECT * FROM #CURSOR_CAFORM_DATA100
                    -- SELECT #CURSOR_CAFORM_DATA100
                    -- SCAN
                    --     SCATTER MEMVAR
                    --     SELECT DATA1
                    --     APPEND BLANK
                    --     GATHER MEMVAR
                    -- ENDSCAN
                END

			 --IF(OBJECT_ID('TEMPDB..#CA_DATA1')IS NOT NULL)  DROP TABLE #CA_DATA1
    --         SELECT 
    --            [OWNER],
    --            LEAD_BANK,-- 最大債權銀行
    --            LEAD_BNK_N,-- 最大債權代號
    --            NAME,--客戶名稱
    --            IDNO,--客戶身分證字號
    --            BIRTHDAY,--生日
    --            COM_ADDR,--通訊住址
    --            REG_ADDR,--戶籍地址
    --            MOBIL_NO,--KV
    --            COM_TELNO,--PV,
    --            REQ_DEBT_D,--協商申請日
    --            RE_DEBT_D,-- 呈報債權日
    --            FIRST_DATE,-- 首期繳款日 
    --            OPENDATE,
    --            CLOSEDATE,
    --            CAST(INCOME_NOW AS INT) AS INCOME_NOW,--年收入
    --            PERIOD,
    --            RATE,
    --            PAYAMOUNT,
    --            DISP_AMT,
    --            COLLECTOR,
    --            SYS_NAME,-- 系統姓名,
    --            STAGE_NOTE,--二階段註記,
    --            RW_FLAG,
    --            CHANGE_ID--是否更改ID
    --        INTO #CA_DATA1					
    --        FROM #CURSOR_CAFORM_DATA100

            --INSERT INTO #EXP_DATA1 SELECT * FROM #CA_DATA1
            --DATA1 EXPORT
            --COPY TO 'M:\RESULT\IDRP\NA\CAFORM\NONLEADING\PRE_DATA1\'+M.IDNO+'_'+DTOS(THEDATE)+'_DATA1' XL5

            IF(OBJECT_ID('TEMPDB..#MAX_CAFORM_CDC')IS NOT NULL) BEGIN DROP TABLE #MAX_CAFORM_CDC END

            SELECT IDNO, ISNULL(MAX(CDC_2),0) AS CDC INTO #MAX_CAFORM_CDC
            FROM #CAFORM_DATA4 WHERE CDC_2 IS NOT NULL
            GROUP BY IDNO 
            
            --** 取參加者最大之CDC
            IF (SELECT count(*) FROM #MAX_CAFORM_CDC)>0
                BEGIN
                    --SELECT UIDRP_MAX_CAFORM_CDC
                    --UPDATE #MAX_CAFORM_CDC SET CDC=0 WHERE CDC IS NULL
                    
                    INSERT INTO UIDRP_MAX_CAFORM_CDC
                    SELECT * FROM #MAX_CAFORM_CDC
                END

            --** WHERE CONDITION NEED MAIN_CODE AND R DATE
			IF(OBJECT_ID('TEMPDB..#Z98')IS NOT NULL)  DROP TABLE #Z98
			--IF(OBJECT_ID('TEMPDB..#Z98_1')IS NOT NULL)  DROP TABLE #Z98_1


            SELECT *,SPACE(10) AS MAINCODE INTO #Z98 FROM UIDRP_Z98_ZZS260 WHERE IDN_BAN=@CSR1_IDNO AND REC_DATE= IIF( LEN(dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE))) = 6
            ,'0'+ dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE)) 
            ,dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE)))

            UPDATE A SET 
			 A.MAINCODE = (CASE WHEN B.CA_CODE IS NOT NULL THEN LTRIM(RTRIM(B.CA_CODE))  WHEN A.MAIN_CODE='083' THEN '052' ELSE A.MAIN_CODE END) ,
			 A.MAIN_NAME= (CASE WHEN A.MAIN_CODE='083' THEN '渣打國際商業銀行' ELSE A.MAIN_NAME END)
			FROM #Z98 A
			LEFT JOIN UIDRP_IDRP_BANKCODE B ON A.MAIN_CODE=B.B_CODE
			 

            --SELECT A.*, A.MAIN_CODE +SPACE(97) AS MAINCODE , B.CA_CODE 
            --INTO #Z98_1
            --FROM #Z98 A 
            --LEFT OUTER JOIN UIDRP_IDRP_BANKCODE B ON A.MAIN_CODE=B.B_CODE

            --UPDATE #Z98_1 
            --SET MAINCODE=LTRIM(RTRIM(CA_CODE)) WHERE (CA_CODE) IS NOT NULL

			IF(OBJECT_ID('TEMPDB..#CURSOR_CAFORM_DATA3')IS NOT NULL)  DROP TABLE #CURSOR_CAFORM_DATA3

            SELECT 
                 SPACE(4) AS COLL_ID
                , IDN_BAN --AS 債務人身分證號
                , MAINCODE --AS 債權銀行代號
                , MAIN_NAME --AS 債權銀行
                , SPACE(1) AS SPACE_1 --對外信貸金額
                , SPACE(1) AS SPACE_2 --對外現金卡金額
                , SPACE(1) AS SPACE_3 --對外信用卡金額
                , EXP_LOAN --AS 對內信貸金額
                , CASH_CARD --AS 對內現金卡金額
                , CREDITCARD --AS 對內信用卡
                , TOTAL_AMT --AS  對內總金額 
            INTO #CURSOR_CAFORM_DATA3
            FROM #Z98
            WHERE IDN_BAN=@CSR1_IDNO AND MAIN_CODE= @CSR1_LEAD_BNK_N 
            AND REC_DATE= IIF( LEN(dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE))) = 6
            ,'0'+ dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE)) --補0
            ,dbo.TRANS_ROCDATE(CAST(@CSR1_REQ_DEBT_D AS DATE)))

            --INSERT INTO #EXP_DATA3 SELECT * FROM #CURSOR_CAFORM_DATA3
            --DATA3 EXPORT
            --COPY TO 'M:\RESULT\IDRP\NA\CAFORM\NONLEADING\'+M.IDNO+'_'+DTOS(THEDATE)+'_DATA3' XL5

            FETCH NEXT FROM CSR_CAFORM1 INTO
            @CSR1_CASENO ,@CSR1_IDNO,  @CSR1_REQ_DEBT_D, @CSR1_LEAD_BNK_N
        END

    CLOSE CSR_CAFORM1
    DEALLOCATE CSR_CAFORM1


    --#CA_DATA1
	--INSERT INTO #EXP_DATA1 SELECT * FROM UIDRP_CA_DATA1
 
    --515
    SELECT 
        A.IDNO, A.NAME, A.WO_FLAG AS IFWO
        , B.EXP_LOAN, B.CASH_CARD, B.CREDITCARD
        , B.EXP_LOAN+B.CASH_CARD+B.CREDITCARD AS TTL_DEBT
        , B.DISP_AMT AS  PAYAMOUNT
    INTO #NONLEADING_SUMMARY_DUP
    FROM #NONLEADING_SUMMARY_TODAY  A 
    LEFT JOIN UIDRP_Z98_ZZM260 B ON A.IDNO=B.IDN_BAN
    WHERE BANK_CODE IN ('021' ,'976')
    

    SELECT IDNO, NAME, WO_FLAG AS IFWO, 0 AS EXP_LOAN
        , 0 AS CASH_CARD, 0 AS CREDITCARD, 0 AS TTL_DEBT, 0 AS PAYAMOUNT
    INTO #SUMMARY_ML
    FROM #NONLEADING_SUMMARY_TODAY 
    WHERE IDNO NOT IN (SELECT IDNO FROM #NONLEADING_SUMMARY_DUP)

    
   INSERT INTO #NONLEADING_SUMMARY_DUP
    SELECT * FROM #SUMMARY_ML


	 --537 *******GIVING RW ACCTNMBR*********
    UPDATE UIDRP_CA_DATA1 SET RW_FLAG='N' WHERE STAGE_NOTE='1'
    
    DECLARE @RW_NUMBER2 INT
  
    SET @RW_NUMBER2= ISNULL((SELECT TOP 1 CONVERT(INT, RIGHT(RW_ACCTBR,5)) FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST WHERE RW_FLAG='Y' ORDER BY RW_ACCTBR DESC),0)


	;WITH NONLEADING_SUMMARY_01
	AS
	(
		SELECT  IDNO, NAME, IFWO, SUM(EXP_LOAN) AS EXP_LOAN, SUM(CASH_CARD) AS CASH_CARD, SUM(CREDITCARD) AS CREDITCARD, SUM(TTL_DEBT) AS TTL_DEBT, PAYAMOUNT    
		FROM #NONLEADING_SUMMARY_DUP
		GROUP BY IDNO, NAME, IFWO, PAYAMOUNT
	)
    , NONLEADING_SUMMARY_07
	AS
	(
       SELECT DISTINCT A.IDNO,A.NAME, DATEADD(MONTH,-1,dbo.TRANS_YMD(LTRIM(RTRIM(B.FIRST_DATE)))) AS OPEN_D,C.CDC ,A.IFWO,  B.FIRST_DATE, B.PERIOD, B.RATE,A.PAYAMOUNT,A.EXP_LOAN,A.CASH_CARD,A.CREDITCARD,A.TTL_DEBT,SPACE(3) AS ACCTTYPE, SPACE(14) AS CARDNMBR,ISNULL(D.IFTWOSTAGE,SPACE(1)) AS IFTWOSTAGE,E.RW_FLAG, SPACE(14) AS RW_ACCTBR,SPACE(1) AS CARDLOAN, ISNULL(F.BUSINESS,SPACE(3)) AS BOOC              
	   FROM NONLEADING_SUMMARY_01 A 
       LEFT JOIN UIDRP_Z98_ZZS260 B ON A.IDNO=B.IDN_BAN
	   LEFT JOIN UIDRP_MAX_CAFORM_CDC C ON A.IDNO=C.IDNO
	   LEFT JOIN (SELECT DISTINCT IDNO, IFTWOSTAGE FROM UIDRP_IDRP_NONLEADING_BASE_VW) D ON A.IDNO=D.IDNO 
	   LEFT JOIN UIDRP_CA_DATA1 E ON A.IDNO=E.IDNO 
	   LEFT JOIN #CTL_NONRW F ON A.IDNO=F.IDNO
    ) 
	--
	INSERT INTO #NONLEADING_SUMMARY_08
    SELECT *
        , LTRIM(RTRIM(CONVERT(VARCHAR, ( ROW_NUMBER() OVER(ORDER BY RW_FLAG DESC) + @RW_NUMBER2)))) AS TAIL    
		, SPACE(1) AS APCM
    FROM NONLEADING_SUMMARY_07
    
    UPDATE #NONLEADING_SUMMARY_08 SET RW_ACCTBR='130001551' + RIGHT('00000'+LTRIM(RTRIM(TAIL)),5) WHERE RW_FLAG='Y' 	 
    UPDATE #NONLEADING_SUMMARY_08 SET CARDLOAN='Y' WHERE IDNO IN (SELECT CUSTID FROM #CURRENT_CDC1 WHERE ACCTTYPE IN ('757','755','749'))

    -- SELE NONLEADING_SUMMARY_08
	-- SCAN FOR RW_FLAG='Y'
	-- 	SCATTER MEMVAR
	-- 	SELE DATA2
	-- 	LOCATE FOR ALLTRIM(IDNO)=ALLTRIM(M.IDNO)
	-- 	IF FOUND()
	-- 		STORE RW_TYPE TO M.ACCTTYPE
	-- 	ENDIF
	-- 	SELE NONLEADING_SUMMARY_08
	-- 	GATHER MEMVAR
	-- 	SCATTER MEMVAR BLANK
	-- ENDSCAN

    UPDATE NS
    SET NS.ACCTTYPE=UCD.RW_TYPE
	FROM #NONLEADING_SUMMARY_08 NS
	INNER JOIN UIDRP_CA_DATA2 UCD ON UCD.IDNO= NS.IDNO
	WHERE NS.RW_FLAG='Y'

    --WHERE RW_FLAG='Y' AND IDNO IN (SELECT IDNO FROM UIDRP_CA_DATA2)


    -- **************************************************************************************************************************
	-- ******************CA Form Re-format request to add ALS-"AMUA" APCM NON-ACCRUAL IND information in CA form******************
	-- ******************Requester: Gina Chen
	-- ******************AP coding: Ivan Chiang/ Andy Ma

    INSERT INTO #APCM1
    SELECT A.IDNO, A.ACCTNMBR, A.CARDNMBR, A.PRODTYPE AS ACCTTYPE, SPACE(1) AS APCM, ISNULL(CU.CDC_2,0) AS CDC
    --INTO #APCM1
    FROM UIDRP_DE_IDRP_DEBTDTL A
	LEFT JOIN #CURRENT_CDC1 CU ON CU.cardnmbr = A.CARDNMBR	
    WHERE A.IDNO IN (SELECT IDNO FROM #NONLEADING_SUMMARY_08 WHERE RW_FLAG='Y' ) 
    AND (SUBSTRING(A.ACCTNMBR,1,2) IN ('13','16','31') OR A.PRODTYPE IN ('749','755','757'))

	-- SELE APCM1
	-- SCAN
	-- 	SCATTER MEMVAR
	-- 	SELE  CURRENT_CDC1
	-- 	LOCATE FOR M.CARDNMBR=CARDNMBR
	-- 	IF FOUND()
	-- 		M.CDC=CDC_2
	-- 		SELE APCM1
	-- 		GATHER MEMVAR
	-- 	ENDIF
	-- ENDSCAN

    --UPDATE #APCM1
    --SET CDC = CU.CDC_2
	--FROM #APCM1
	--INNER JOIN #CURRENT_CDC1 CU ON CU.cardnmbr = #APCM1.CARDNMBR	 
  
    --WHERE CARDNMBR IN (SELECT CARDNMBR FROM #CURRENT_CDC1)

	UPDATE #APCM1 SET APCM='Y' WHERE SUBSTRING(ACCTNMBR,1,2) IN ('13','16','31') OR (ACCTTYPE IN ('749','755','757') AND CDC=4)
    -- 接續3270
    SET @STATUS = 1

 
--UIDRP_CA_MISRPT10300_SP2
 


	--FA20190612  #NONLEADING_SUMMARY_08 == #PRE_SUMMARY 

	 DELETE FROM UIDRP_PRE_SUMMARY WHERE PROCDATE = @THEDATE

	 INSERT UIDRP_PRE_SUMMARY ([PROCDATE],[SN],[IDNO],[NAME],[OPEN_D],[CDC],[IFWO],[FIRST_DATE],[PERIOD],[RATE],[PAYAMOUNT],[EXP_LOAN],[CASH_CARD],[CREDITCARD],[TTL_DEBT],[ACCTTYPE],[CARDNMBR],[IFTWOSTAGE],[RW_FLAG],[RW_ACCTBR],[CARDLOAN],[BOOC],[TAIL],[APCM])
	 SELECT @THEDATE,ROW_NUMBER() OVER(ORDER BY (SELECT NULL)),IDNO,NAME,OPEN_D,CDC,IFWO,FIRST_DATE,PERIOD,RATE,PAYAMOUNT,EXP_LOAN,CASH_CARD,CREDITCARD,TTL_DEBT,ACCTTYPE,CARDNMBR,IFTWOSTAGE,RW_FLAG,RW_ACCTBR,CARDLOAN,BOOC,TAIL,APCM
	 FROM #NONLEADING_SUMMARY_08
	 
	 --SELECT *, SPACE(1) AS APCM INTO #PRE_SUMMARY FROM #NONLEADING_SUMMARY_08
    --EXEC('SELECT *, SPACE(1) AS APCM INTO #PRE_SUMMARY FROM #NONLEADING_SUMMARY_08')
	--UPDATE #PRE_SUMMARY SET APCM='Y' WHERE IDNO IN (SELECT IDNO FROM #APCM1 WHERE APCM='Y')
	--UPDATE #PRE_SUMMARY SET APCM=''  WHERE RW_FLAG <>'Y'

	  --SELECT * FROM #PRE_SUMMARY
	--COPY TO 'M:\RESULT\IDRP\NA\CAFORM\NONLEADING\DBF_SUMMARY\SUMMARY_'+DTOS(THEDATE)

	--SELECT * FROM CHECKDEBT  WHERE Z98_DEBT<>TTL_DEBT_I GROUP BY IDNO  INTO DBF DEL_CHECKZ98  	
    --SELECT DISTINCT * INTO #CHK_APDEBTLIST FROM UIDRP_CHECKDEBT  WHERE Z98_DEBT <> TTL_DEBT_I 
    --Check_APDEBTLIST EXPORT
	--COPY TO 'M:\RESULT\IDRP\NA\CAFORM\NONLEADING\CHECK_APDEBTLIST_'+DTOS(THEDATE)  XL5

    --647
    SELECT 
      A.CASENO
    , A.IDNO
    , A.NAME
    , A.LEAD_BNK_N
    , A.LEAD_BANK
    , A.REQ_DEBT_D
    , A.RE_DEBT_D
    , A.FIRST_DATE
    , A.PERIOD
    , A.RATE
    , A.PAYAMOUNT
    , B.RW_FLAG
    , B.RW_ACCTBR
    , CONVERT(VARCHAR(10),@THEDATE,111) AS NOTIS_D
    , B.ACCTTYPE
    , SPACE(1) AS IF_COMM
    INTO #HIST1
    FROM #IDRP_CAFORM_NONLEADING_BASE_4 A 
    LEFT JOIN #NONLEADING_SUMMARY_08 B ON A.IDNO=B.IDNO


	DECLARE @CHECK0_COUNT INT,@NEWAC INT, @HISAC INT, @CHECK2_COUNT INT,@EXP_ACCTNMBR INT

    SELECT @CHECK0_COUNT=COUNT(RW_ACCTBR)    
    FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST 
    WHERE RW_ACCTBR IN (SELECT RW_ACCTBR FROM #HIST1) AND LEN(ISNULL(RW_ACCTBR,'')) > 0

	IF @CHECK0_COUNT > 0
        BEGIN
        --    SET @STATUS = 0
            SET @MESSAGE+=(CHAR(10) + '請注意HISTORY有重複的RW ACCTNMBR ASSIGNED，請檢查 ')
	    END

	INSERT INTO UIDRP_IDRP_CAFORM_NONLEADING_HIST
	SELECT * FROM #HIST1
 
	SET @NEWAC = (SELECT count(*) FROM #HIST1)
    
   -- SELECT * INTO #CHECK1 FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST WHERE IDNO IN (SELECT IDNO FROM #HIST1)
    --2017/1/25 為防止 IDNO相同但CASENO不同造成誤判筆數不同多MAPPING CASENO
	SELECT @HISAC = COUNT(*) FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST A --WHERE IDNO IN (SELECT IDNO FROM #HIST1) AND CASENO IN (SELECT CASENO FROM #HIST1)
	INNER JOIN #HIST1 B ON B.IDNO=A.IDNO AND B.CASENO=A.CASENO

	--SET @HISAC = (SELECT count(*) FROM #CHECK1)

	IF @NEWAC <> @HISAC
        BEGIN
           -- SET @STATUS = 0
		    SET @MESSAGE += (CHAR(10) + '請注意歷史檔中新增資料筆數有誤，請詳查 ');
	    END

	SELECT @CHECK2_COUNT =COUNT(*)  
    FROM #HIST1 
    WHERE RW_ACCTBR NOT IN (SELECT RW_ACCTBR FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST)
	
	IF @CHECK2_COUNT > 0
        BEGIN
         --   SET @STATUS = 0
            SET @MESSAGE += (CHAR(10) + '請注意歷史檔中RW LOAN NUMBER 與今日新增檔案內容不符，請詳查 ')
        END


	SELECT @EXP_ACCTNMBR=COUNT(*)     
    FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST 
    WHERE RW_FLAG='Y' 
    GROUP BY RW_ACCTBR
	HAVING COUNT(*) > 1

	IF @EXP_ACCTNMBR > 0
        BEGIN
           -- SET @STATUS = 0
		    SET @MESSAGE += (CHAR(10) + '請注意重複的RW ACCTNMBR ASSIGNED，請檢查 ')
	    END

    --回傳訊息(如果有中止的必要，可由STATUS = 0處控制，目前只有拋錯會為0)
    SET @STATUS = 1
    SET @MESSAGE =  CHAR(10)+ @MESSAGE + CHAR(10) + '已完成上傳CA送件日'

	DECLARE @GROUPID UNIQUEIDENTIFIER,@GUID UNIQUEIDENTIFIER,@FFOUT VARCHAR(200),@ROWCNT INT

	 
	DECLARE   @ALL_CASENO        VARCHAR(20)     --UIDRP_DE_IDRP_CUSTINFO   bigint
			, @ALL_IDNO          VARCHAR(10)     --UIDRP_DE_IDRP_CUSTINFO
			, @ALL_NAME          NVARCHAR(12)    --UIDRP_DE_IDRP_CUSTINFO  
			, @ALL_SYS_NAME      NVARCHAR(30)
			, @ALL_OPENDATE      DATE
			, @ALL_CLOSEDATE     DATE
			, @ALL_PERIOD        DECIMAL(3)  
			, @ALL_RATE          DECIMAL(5,2)
			, @ALL_TTL_OS        DECIMAL(18,2)
			, @ALL_DISP_AMT      DECIMAL(9, 0)
			, @ALL_LEAD_BANK     NVARCHAR(100) 
			, @ALL_LEAD_BNK_N    VARCHAR(100) 
			, @ALL_RW_FLAG       VARCHAR(1)
			, @ALL_RW_ACCTBR     VARCHAR(20)
			, @ALL_ACCTTYPE      VARCHAR(3)    
			, @ALL_REQ_DEBT_D    VARCHAR(10)  	
			, @ALL_RE_DEBT_D     DATETIME
			, @ALL_COM_ADDR      VARCHAR(76) 
			, @ALL_COM_TELNO     VARCHAR(16)     
			, @ALL_BIRTHDAY      VARCHAR(10)     --UIDRP_DE_IDRP_CUSTINFO CONVERT(varchar)
			, @ALL_REG_ADDR      VARCHAR(76)	
			, @ALL_MOBIL_NO      VARCHAR(16)       
			, @ALL_INCOME_NOW    INT 
			, @ALL_IFDINERS      VARCHAR(1)
	 
	
	

    DECLARE ALL_CAFORM CURSOR FOR 
	SELECT A.CASENO, A.IDNO, A.NAME, B.SYS_NAME, B.OPENDATE, B.CLOSEDATE, A.PERIOD, A.RATE, B.TTL_OS, B.DISP_AMT, B.LEAD_BANK, B.LEAD_BNK_N, A.RW_FLAG, 
	       A.RW_ACCTBR, A.ACCTTYPE, B.REQ_DEBT_D, B.RE_DEBT_D, B.COM_ADDR, B.COM_TELNO, B.BIRTHDAY, B.REG_ADDR, B.MOBIL_NO, B.INCOME_NOW, IIF(C.CASENO IS NOT NULL,'Y','N') AS IFDINERS
	FROM #HIST1 A 
	LEFT JOIN #NONLEADING_CAFORM1 B ON A.CASENO=B.CASENO  
	LEFT JOIN #ACCTDTL C ON C.CASENO = A.CASENO AND SUBSTRING(C.CARDNMBR,1,2) ='36'
 

    OPEN ALL_CAFORM
    FETCH NEXT FROM ALL_CAFORM INTO @ALL_CASENO ,@ALL_IDNO, @ALL_NAME, @ALL_SYS_NAME,@ALL_OPENDATE,@ALL_CLOSEDATE,@ALL_PERIOD,@ALL_RATE,@ALL_TTL_OS,@ALL_DISP_AMT,@ALL_LEAD_BANK,@ALL_LEAD_BNK_N,@ALL_RW_FLAG,
	                               @ALL_RW_ACCTBR,@ALL_ACCTTYPE,@ALL_REQ_DEBT_D,@ALL_RE_DEBT_D,@ALL_COM_ADDR,@ALL_COM_TELNO,@ALL_BIRTHDAY,@ALL_REG_ADDR,@ALL_MOBIL_NO,@ALL_INCOME_NOW,@ALL_IFDINERS

    WHILE(  @@FETCH_STATUS = 0 )
    BEGIN
		SET @GROUPID = NEWID()
		SET @GUID = NEWID()
		SET @ALL_NAME= REPLACE(@ALL_NAME,'　','');
		SET @FFOUT = SUBSTRING(dbo.ALLTRIM(@ALL_IDNO),1,3)+'XXXX'+SUBSTRING(dbo.ALLTRIM(@ALL_IDNO),7,3)+'_'+LEFT(dbo.ALLTRIM(@ALL_NAME),1)+'X'+RIGHT(dbo.ALLTRIM(@ALL_NAME),1)+'.xls'

		INSERT INTO @EXCEL 	SELECT @GROUPID	,@GUID ,'CA_TEMPLATE_NEW1.XLS','TEMPLATE',@FFOUT,'CA1'
		--OLE1.CELLS(1,2).VALUE=DTOC(R_DATE)
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 2 , 3 , @ALL_IDNO , 'STRING')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 2 , 6 , dbo.ALLTRIM(@ALL_NAME) , 'STRING')	
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 2 , 9 , dbo.ALLTRIM(@ALL_SYS_NAME) , 'STRING')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 3 , 3 , @ALL_OPENDATE , 'DATETIME')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 3 , 6 , @ALL_CLOSEDATE , 'DATETIME')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 3 , 9 , @ALL_PERIOD , 'DECIMAL')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 4 , 9 , @ALL_RATE , 'DECIMAL')

	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 5 , 3 , @ALL_TTL_OS , 'DECIMAL')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 5 , 9 , @ALL_DISP_AMT , 'DECIMAL')
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 6 , 3 , dbo.ALLTRIM(@ALL_LEAD_BANK) , 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 6 , 6 , @ALL_LEAD_BNK_N , 'STRING')
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 7 , 3 , @ALL_IFDINERS , 'STRING')
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 7 , 6 , @ALL_ACCTTYPE , 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 7 , 9 ,@ALL_RW_ACCTBR, 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 8 , 3 ,@ALL_RW_FLAG, 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 8 , 6 ,@ALL_REQ_DEBT_D, 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 8 , 9 ,CONVERT(VARCHAR(10),@ALL_RE_DEBT_D,111), 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 9 , 6 ,dbo.ALLTRIM(@ALL_COM_ADDR), 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 9 , 9 ,dbo.ALLTRIM(@ALL_MOBIL_NO), 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 10 , 3 ,@ALL_BIRTHDAY, 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 10 , 6 ,dbo.ALLTRIM(@ALL_REG_ADDR), 'STRING')
        INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 10 , 9 ,dbo.ALLTRIM(@ALL_COM_TELNO), 'STRING')
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 11 , 3 , ISNULL(@ALL_INCOME_NOW,0), 'INT')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 12 , 4 , IIF(@ALL_PERIOD > 120 AND @ALL_RW_FLAG='Y','Y','N'), 'STRING')
      

		SET @ROWCNT = 0
		DECLARE @CHK_BANKCODE  VARCHAR(3) ,@CHK_CARDNMBR VARCHAR(16) ,@CHK_ACCOUNTTYPE VARCHAR(3),@CHK_OS1  DECIMAL(18,2),@CHK_PRINCIPALA  DECIMAL(18,2),@CHK_INTEREST  DECIMAL(18,2),@CHK_LATEFEE  DECIMAL(18,2),
		        @CHK_LEGALFEE  DECIMAL(18,2),@CHK_PENALTY VARCHAR(1),@CHK_DELQBKT VARCHAR(1),@CHK_WO_FLAG_2 VARCHAR(1)

		DECLARE CHK_ACCT CURSOR FOR 
		SELECT BANKCODE, CARDNMBR, ACCOUNTTYPE, OS1, PRINCIPALA, INTEREST, LATEFEE, LEGALFEE, PENALTY, DELQBKT, IIF(WO_FLAG_2='Y' OR WO_FLAG_2='1','1','0') AS WO_FLAG_2 
		FROM #ACCTDTL 
		WHERE IDNO=@ALL_IDNO AND CASENO=@ALL_CASENO  
		ORDER BY BANKCODE, CARDNMBR

	    OPEN CHK_ACCT
		  
        FETCH NEXT FROM CHK_ACCT INTO @CHK_BANKCODE ,@CHK_CARDNMBR, @CHK_ACCOUNTTYPE, @CHK_OS1, @CHK_PRINCIPALA ,@CHK_INTEREST,@CHK_LATEFEE, @CHK_LEGALFEE, @CHK_PENALTY,@CHK_DELQBKT,@CHK_WO_FLAG_2
		WHILE( @@FETCH_STATUS = 0 )
		BEGIN
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 1 , @CHK_BANKCODE , 'STRING')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 2 , @CHK_CARDNMBR , 'STRING')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 3 , @CHK_ACCOUNTTYPE , 'STRING')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 4 , @CHK_OS1 , 'DECIMAL')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 5 , @CHK_PRINCIPALA , 'DECIMAL')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 6 , @CHK_INTEREST , 'DECIMAL')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 7 , @CHK_LATEFEE , 'DECIMAL')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 8 , @CHK_LEGALFEE , 'DECIMAL')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 9 , @CHK_PENALTY , 'STRING')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 10 , @CHK_DELQBKT , 'STRING')
		   INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , @ROWCNT+15 , 11, @CHK_WO_FLAG_2 , 'STRING')

		   SET @ROWCNT =@ROWCNT+1
		   FETCH NEXT FROM CHK_ACCT INTO @CHK_BANKCODE ,@CHK_CARDNMBR, @CHK_ACCOUNTTYPE, @CHK_OS1, @CHK_PRINCIPALA ,@CHK_INTEREST,@CHK_LATEFEE, @CHK_LEGALFEE, @CHK_PENALTY,@CHK_DELQBKT,@CHK_WO_FLAG_2
		END
	 
	    CLOSE CHK_ACCT
        DEALLOCATE CHK_ACCT

	    FETCH NEXT FROM ALL_CAFORM INTO @ALL_CASENO ,@ALL_IDNO, @ALL_NAME, @ALL_SYS_NAME,@ALL_OPENDATE,@ALL_CLOSEDATE,@ALL_PERIOD,@ALL_RATE,@ALL_TTL_OS,@ALL_DISP_AMT,@ALL_LEAD_BANK,@ALL_LEAD_BNK_N,@ALL_RW_FLAG,
	                               @ALL_RW_ACCTBR,@ALL_ACCTTYPE,@ALL_REQ_DEBT_D,@ALL_RE_DEBT_D,@ALL_COM_ADDR,@ALL_COM_TELNO,@ALL_BIRTHDAY,@ALL_REG_ADDR,@ALL_MOBIL_NO,@ALL_INCOME_NOW,@ALL_IFDINERS

	END
	CLOSE ALL_CAFORM
    DEALLOCATE ALL_CAFORM

	--	2018/7/17 新增Partial Reserve	
	DECLARE NEW_PI CURSOR FOR 
	SELECT A.IDNO, A.NAME, C.TTL_OS, A.PERIOD , A.RATE , A.RW_ACCTBR, A.ACCTTYPE, B.DISP_AMT 
	FROM (SELECT * FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST WHERE IF_COMM<> 'Y' AND RW_FLAG='Y' AND PERIOD > 120 AND NOTIS_D = CONVERT(VARCHAR(10),@THEDATE,111)) A 
	INNER JOIN UIDRP_Z98_ZZM260 B ON A.IDNO= B.IDN_BAN 
	INNER JOIN (SELECT IDNO, TTL_OS FROM #NONLEADING_CAFORM1 WHERE PERIOD > 120) C ON A.IDNO=C.IDNO WHERE B.BANK_CODE = '021' 

	--SELECT A.IDNO, A.NAME, C.TTL_OS, A.PERIOD , A.RATE , A.RW_ACCTBR, A.ACCTTYPE, B.DISP_AMT 
	--FROM (SELECT * FROM UIDRP_IDRP_CAFORM_NONLEADING_HIST WHERE IF_COMM<> 'Y' AND RW_FLAG='Y' AND PERIOD > 120 AND NOTIS_D = CONVERT(VARCHAR(10),@THEDATE,111)) A 
	--LEFT JOIN UIDRP_Z98_ZZM260 B ON A.IDNO= B.IDN_BAN AND B.BANK_CODE = '021' 
	--LEFT JOIN (SELECT IDNO, TTL_OS FROM #NONLEADING_CAFORM1 WHERE PERIOD > 120) C ON A.IDNO=C.IDNO 

    

	OPEN NEW_PI
    FETCH NEXT FROM NEW_PI INTO @ALL_IDNO, @ALL_NAME, @ALL_TTL_OS,@ALL_PERIOD ,@ALL_RATE, @ALL_RW_ACCTBR,@ALL_ACCTTYPE,@ALL_DISP_AMT 

    WHILE(  @@FETCH_STATUS = 0 )
    BEGIN
		SET @GROUPID = NEWID()
		SET @GUID = NEWID()
		SET @ALL_NAME= REPLACE(@ALL_NAME,'　','');
		SET @FFOUT ='PI_' + SUBSTRING(dbo.ALLTRIM(@ALL_IDNO),1,3)+'XXXX'+SUBSTRING(dbo.ALLTRIM(@ALL_IDNO),7,3)+'_'+LEFT(dbo.ALLTRIM(@ALL_NAME),1)+'X'+RIGHT(dbo.ALLTRIM(@ALL_NAME),1)+'.xlsx'

		INSERT INTO @EXCEL 	SELECT @GROUPID	,@GUID ,'Partial_Reserve_Template.xlsx','TEMPLATE',@FFOUT,'RESERVE'

		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 0 , 4 , @ALL_IDNO , 'STRING')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 0 , 10 , @ALL_NAME , 'STRING')	
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 3 , 1 , @ALL_TTL_OS , 'DECIMAL')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 5 , 1 , @ALL_PERIOD , 'DECIMAL')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 7 , 1 , @ALL_RATE / 100, 'DECIMAL')
	    INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 11, 1 , ISNULL(@ALL_DISP_AMT,0) , 'DECIMAL')
	   
	    SET @GUID = NEWID()
		INSERT INTO @EXCEL 	SELECT @GROUPID	,@GUID ,'Partial_Reserve_Template.xlsx','TEMPLATE',@FFOUT,'MEMO'

		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID , 3, 2 , 'PL - IDRP Partial Write-Off  Memo (IN NT$)' , 'STRING')
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID ,27, 1 , @ALL_IDNO , 'STRING')	
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID ,27, 2 , @ALL_RW_ACCTBR , 'STRING')	
		INSERT INTO @EXCELCELLS (PARENTID,CELL_Y,CELL_X,CELLVALUE,CELLTYPE) VALUES (@GUID ,27, 4 , @ALL_ACCTTYPE , 'STRING')	

  	    FETCH NEXT FROM NEW_PI INTO @ALL_IDNO, @ALL_NAME, @ALL_TTL_OS,@ALL_PERIOD ,@ALL_RATE, @ALL_RW_ACCTBR,@ALL_ACCTTYPE,@ALL_DISP_AMT 
	END
	CLOSE NEW_PI
    DEALLOCATE NEW_PI


END TRY
BEGIN CATCH
    SET @STATUS = 0
    SET @MESSAGE = ERROR_MESSAGE() + ' LINE='+ CAST(ERROR_LINE() AS VARCHAR)
    RAISERROR(@MESSAGE,16,1)
END CATCH
----------------------------------------------
-- 回傳區
----------------------------------------------
--M.IDNO+'_'+DTOS(THEDATE)+DATA 1~3.XLS
--DTOS(THEDATE)+SUM & APD.XLS
SELECT @STATUS as [Status],@MESSAGE as [Message]

SELECT * FROM #APCM1
SELECT * FROM #NONLEADING_SUMMARY_08
SELECT DISTINCT * FROM UIDRP_CHECKDEBT WHERE Z98_DEBT <> TTL_DEBT_I 
SELECT * FROM @EXCEL
SELECT * FROM @EXCELCELLS


END
