USE [COGDB2]
GO
/****** Object:  StoredProcedure [dbo].[UIDRP_BPKP10101_SP]    Script Date: 2019/6/3 下午 04:22:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		Dylan
-- Create date: 
-- Description:	月付金不足額名單產出(BPKP/BPKP10101)
-- SOURCE : idrp_bp.scx & idrp_bp.prg
-- =============================================
ALTER PROCEDURE [dbo].[UIDRP_BPKP10101_SP]
	@MY_COLL_DATE VARCHAR(10) = ''
AS

--DEBUG
--DECLARE @MY_COLL_DATE VARCHAR(10) = '2019/01/21'
--END DEBUG

DECLARE @STATUS BIT = 0
,@MESSAGE NVARCHAR(200) = ''

DECLARE @DATE4 DATE

/*
USE M:\DATASET\CUS_DATA\NA\CUSTINFO IN 0 SHARED
USE M:\DATASET\CHANGEID\CHANGEIDBASE_GROUP IN 0 ALIAS CHGID SHARED
USE M:\DATASET\CUS_DATA\NA\PAYMENTREC IN 0 SHARED
USE M:\RESULT\IDRP\NA\CACS_ROUTING\GONOW\FORBEARANCE\IDRP_GRACE2 IN 0 SHARED
USE M:\DATASet\IDRP_BASE\IDRP_BASE IN 0 ALIAS IBASE SHARED
USE 'M:\DATASET\CARDS_DBF\'+DTOS(DATE4-1)+'\CARDS' IN 0 ALIAS CARDS SHARED 
USE 'M:\DATASET\CARDS_DBF\'+DTOS(DATE4-1)+'\BUDTRAN' IN 0 ALIAS BTRAN  SHARED 
USE 'M:\DATASET\REC_COMBO\REC_COMBO_'+SUBSTR(DTOS(DATE4-1),3,6) IN 0 ALIAS REC SHARED 
USE M:\DATASET\CUS_DATA\NA\CITIDETAIL IN 0 SHARED
USE 'M:\DATASET\ALSEOM\ALSEOM'+SUBS(DTOS(DATE4-1),3,6) IN 0 ALIAS ALSEOM SHARE
USE 'M:\RESULT\IDRP\APDATA\IDRP_RENGTI_BACKUP' IN 0 SHARE ALIAS IDRP_RENGTI
USE 'M:\DAtASET\CUS_DATA\NA\ALLBANKDETAIL.DBF' IN 0 SHARE ALIAS ALLBANKDETAIL
*/

--IF(OBJECT_ID('TEMPDB..#TEMP1')IS NOT NULL) BEGIN DROP TABLE #TEMP1 END
--IF(OBJECT_ID('TEMPDB..#TEMP2')IS NOT NULL) BEGIN DROP TABLE #TEMP2 END
IF(OBJECT_ID('TEMPDB..#IDRP_CONTRACT_BASE')IS NOT NULL) BEGIN DROP TABLE #IDRP_CONTRACT_BASE END
IF(OBJECT_ID('TEMPDB..#CITIDETAIL_IDTAG')IS NOT NULL) BEGIN DROP TABLE #CITIDETAIL_IDTAG END
IF(OBJECT_ID('TEMPDB..#IDRP_CONTRACT_BASE_IDTAG')IS NOT NULL) BEGIN DROP TABLE #IDRP_CONTRACT_BASE_IDTAG END
IF(OBJECT_ID('TEMPDB..#CUSTINFO_IDTAG')IS NOT NULL) BEGIN DROP TABLE #CUSTINFO_IDTAG END
IF(OBJECT_ID('TEMPDB..#PAYMENTREC_IDTAG')IS NOT NULL) BEGIN DROP TABLE #PAYMENTREC_IDTAG END
IF(OBJECT_ID('TEMPDB..#GRACE_IDTAG')IS NOT NULL) BEGIN DROP TABLE #GRACE_IDTAG END
IF(OBJECT_ID('TEMPDB..#CONTRACT_BASE_MAP_CUS')IS NOT NULL) BEGIN DROP TABLE #CONTRACT_BASE_MAP_CUS END
IF(OBJECT_ID('TEMPDB..#SHOULDPAY_BASE')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_BASE END
IF(OBJECT_ID('TEMPDB..#CUS_CITIDETAIL')IS NOT NULL) BEGIN DROP TABLE #CUS_CITIDETAIL END
IF(OBJECT_ID('TEMPDB..#CUS_PAYMENT')IS NOT NULL) BEGIN DROP TABLE #CUS_PAYMENT END
IF(OBJECT_ID('TEMPDB..#CUS_GRACE')IS NOT NULL) BEGIN DROP TABLE #CUS_GRACE END
--IF(OBJECT_ID('TEMPDB..#SECURE_DEBT')IS NOT NULL) BEGIN DROP TABLE #SECURE_DEBT END
IF(OBJECT_ID('TEMPDB..#SECURE_DEBT_IDTAG')IS NOT NULL) BEGIN DROP TABLE #SECURE_DEBT_IDTAG END
--IF(OBJECT_ID('TEMPDB..#SHOULDPAY_CITIDETAIL')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_CITIDETAIL END
--IF(OBJECT_ID('TEMPDB..#SHOULDPAY_MLDEBT')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_MLDEBT END
--IF(OBJECT_ID('TEMPDB..#SHOULDPAY_PAYMENT')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_PAYMENT END
--IF(OBJECT_ID('TEMPDB..#SHOULDPAY_INFO')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_INFO END
IF(OBJECT_ID('TEMPDB..#SHOULDPAY_CHECK')IS NOT NULL) BEGIN DROP TABLE #SHOULDPAY_CHECK END
IF(OBJECT_ID('TEMPDB..#RENGTI_SIGN_OK')IS NOT NULL) BEGIN DROP TABLE #RENGTI_SIGN_OK END
IF(OBJECT_ID('TEMPDB..#RENGTI_ING')IS NOT NULL) BEGIN DROP TABLE #RENGTI_ING END
IF(OBJECT_ID('TEMPDB..#RENGTI_FAIL')IS NOT NULL) BEGIN DROP TABLE #RENGTI_FAIL END
IF(OBJECT_ID('TEMPDB..#PAYOFFLIST')IS NOT NULL) BEGIN DROP TABLE #PAYOFFLIST END
IF(OBJECT_ID('TEMPDB..#PAY_OVER4')IS NOT NULL) BEGIN DROP TABLE #PAY_OVER4 END
IF(OBJECT_ID('TEMPDB..#IDRP_BPID')IS NOT NULL) BEGIN DROP TABLE #IDRP_BPID END
--IF(OBJECT_ID('TEMPDB..#CACS')IS NOT NULL) BEGIN DROP TABLE #CACS END
IF(OBJECT_ID('TEMPDB..#BP_ACCT_MAP_CACS')IS NOT NULL) BEGIN DROP TABLE #BP_ACCT_MAP_CACS END
IF(OBJECT_ID('TEMPDB..#NOT_IN_CACS')IS NOT NULL) BEGIN DROP TABLE #NOT_IN_CACS END
IF(OBJECT_ID('TEMPDB..#CPMB_ACCT')IS NOT NULL) BEGIN DROP TABLE #CPMB_ACCT END
IF(OBJECT_ID('TEMPDB..#BP_ACCT_MAP_IBASE_ALL')IS NOT NULL) BEGIN DROP TABLE #BP_ACCT_MAP_IBASE_ALL END
IF(OBJECT_ID('TEMPDB..#BP_ACCT_MAP_IBASE')IS NOT NULL) BEGIN DROP TABLE #BP_ACCT_MAP_IBASE END
IF(OBJECT_ID('TEMPDB..#NOT_IN_IBASE')IS NOT NULL) BEGIN DROP TABLE #NOT_IN_IBASE END
IF(OBJECT_ID('TEMPDB..#BP_ACCT_MAP_ALSEOM')IS NOT NULL) BEGIN DROP TABLE #BP_ACCT_MAP_ALSEOM END
IF(OBJECT_ID('TEMPDB..#BP_ACCT')IS NOT NULL) BEGIN DROP TABLE #BP_ACCT END
IF(OBJECT_ID('TEMPDB..#BPAC_MTD')IS NOT NULL) BEGIN DROP TABLE #BPAC_MTD END
IF(OBJECT_ID('TEMPDB..#IDRP_BPBASE')IS NOT NULL) BEGIN DROP TABLE #IDRP_BPBASE END
IF(OBJECT_ID('TEMPDB..#IDRP_BPBASE_1')IS NOT NULL) BEGIN DROP TABLE #IDRP_BPBASE_1 END
IF(OBJECT_ID('TEMPDB..#RENEGTI3_UPDPMTPLAN3')IS NOT NULL) BEGIN DROP TABLE #RENEGTI3_UPDPMTPLAN3 END
IF(OBJECT_ID('TEMPDB..#RENGTI_GRACE2')IS NOT NULL) BEGIN DROP TABLE #RENGTI_GRACE2 END
IF(OBJECT_ID('TEMPDB..#CURRCCH')IS NOT NULL) BEGIN DROP TABLE #CURRCCH END
IF(OBJECT_ID('TEMPDB..#MYTEMP1')IS NOT NULL) BEGIN DROP TABLE #MYTEMP1 END
IF(OBJECT_ID('TEMPDB..#MYTEMP2')IS NOT NULL) BEGIN DROP TABLE #MYTEMP2 END
IF(OBJECT_ID('TEMPDB..#REC')IS NOT NULL) BEGIN DROP TABLE #REC END
IF(OBJECT_ID('TEMPDB..#CARDS')IS NOT NULL) BEGIN DROP TABLE #CARDS END
IF(OBJECT_ID('TEMPDB..#BUDTRAN')IS NOT NULL) BEGIN DROP TABLE #BUDTRAN END
 
--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\CHECK_PAYOFF_'+ALLT(DTOS(DATE())) XL5
DECLARE @PAYOFFLIST TABLE
(
	ID_TAG varchar(10)
	,CASENO bigint
	,IDNO varchar(10)
	,OLDID varchar(10)
	,NAME nvarchar(20)
	,LEAD_BNK_N varchar(3)
	,REQ_DEBT_D varchar(10)
	,FIRSTPAY_D varchar(10)
	,PMT_TENOR smallint
	,PMT_APR decimal
	,PMT_INST bigint
	,IN_TOTAL bigint
	,IFTWOSTAGE varchar(1)
	,IF_RW varchar(1)
	,OPENDATE varchar(10)
	,NARW_ACCT varchar(14)
	,CTLRW_ACCT varchar(14)
	,UNSCU_CNT int
	,UNSCU_AMT decimal
	,SCU_CNT int
	,SCU_AMT decimal
	,TTL_PAY decimal
	,LASTPAY_D datetime
	,GTIME int
	,SHOULD_TEN int
	,SHOULD_PAY numeric(10,0)
	,PAY_STATUS numeric(10,0)
	,IFKP varchar(2)
	,CHKML varchar(1)
	,RE_NEGTI varchar(1)
)

--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\CHECK_PAY_OVER4_'+ALLT(DTOS(DATE())) XL5
DECLARE @PAY_OVER4 TABLE
(
	ID_TAG varchar(10)
	,CASENO bigint
	,IDNO varchar(10)
	,OLDID varchar(10)
	,NAME nvarchar(20)
	,LEAD_BNK_N varchar(3)
	,REQ_DEBT_D varchar(10)
	,FIRSTPAY_D varchar(10)
	,PMT_TENOR smallint
	,PMT_APR decimal
	,PMT_INST bigint
	,IN_TOTAL bigint
	,IFTWOSTAGE varchar(1)
	,IF_RW varchar(1)
	,OPENDATE varchar(10)
	,NARW_ACCT varchar(14)
	,CTLRW_ACCT varchar(14)
	,UNSCU_CNT int
	,UNSCU_AMT decimal
	,SCU_CNT int
	,SCU_AMT decimal
	,TTL_PAY decimal
	,LASTPAY_D datetime
	,GTIME int
	,SHOULD_TEN int
	,SHOULD_PAY numeric(10,0)
	,PAY_STATUS numeric(10,0)
	,IFKP varchar(2)
	,CHKML varchar(1)
	,RE_NEGTI varchar(1)
)

--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\CHECK_PAYOFF_'+ALLT(DTOS(DATE()))+'_ALLBANK' XL5 
DECLARE @PAYOFFLIST_ALLBANK TABLE
(
	CUSTID VARCHAR(10)
	,NAME VARCHAR(16)
	,BANKCODE VARCHAR(100) --3
	,BANKNAME VARCHAR(100) --24
	,OSBAL NUMERIC(8,0)
	,CACS_STATE VARCHAR(3)
)

--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\IDRP_BPBASE_'+ALLT(DTOS(DATE())) XL5 
DECLARE @IDRP_BPBASE_1 TABLE
(
	ID_TAG varchar(10)
	,CASENO bigint
	,IDNO varchar(10)
	,OLDID varchar(10)
	,NAME nvarchar(20)
	,LEAD_BNK_N varchar(3)
	,REQ_DEBT_D varchar(10)
	,FIRSTPAY_D varchar(10)
	,PMT_TENOR smallint
	,PMT_APR decimal
	,PMT_INST bigint
	,IN_TOTAL bigint
	,IFTWOSTAGE varchar(1)
	,IF_RW varchar(1)
	,OPENDATE varchar(10)
	,NARW_ACCT varchar(14)
	,CTLRW_ACCT varchar(14)
	,UNSCU_CNT int
	,UNSCU_AMT decimal
	,SCU_CNT int
	,SCU_AMT decimal
	,TTL_PAY decimal
	,LASTPAY_D datetime
	,GTIME int
	,SHOULD_TEN int
	,SHOULD_PAY numeric(10,0)
	,PAY_STATUS numeric(10,0)
	,IFKP varchar(2)
	,CHKML varchar(1)
	,RE_NEGTI varchar(1)
	,CARDNMBR varchar(30)
	,ACCTTYPE varchar(3)
	,CURRSTATE varchar(3)
	,LOCATION varchar(6)
	,SOURCE varchar(9)
	,WODATE date NULL
	,STATUS1 varchar(3)
	,OA varchar(4)
	,DEL_RESN varchar(1)
	,RCODE varchar(10)
	,REMARK varchar(80)
)

--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\ROUTING\MANUAL_CHECK_BP_'+ALLT(DTOS(DATE())) XL5
DECLARE @MYTEMP4 TABLE
(
	PRG varchar(7)
	,PRCDATE date
	,IDNO varchar(10)
	,LEADBK_N varchar(3)
	,APPLY_D varchar(10)
	,CARDNMBR varchar(16)
	,TX_CODE varchar(13)
	,CACS_STATE varchar(3)
	,ORI_STATE varchar(3)
	,F9MEMO varchar(49)
	,FUN_CODE varchar(1)
	,ROUTE_TYPE varchar(1)
	,ACCTTYPE varchar(3)
	,LOCATION varchar(6)
	,tel3 int
	,letter1 int
)


BEGIN TRY
SET @DATE4 = GETDATE()

IF @MY_COLL_DATE <> ''
BEGIN
	--SET @MESSAGE = @MESSAGE + 'Check CCH data....'
/*	SOURCE CODE
----BEGIN SAGE
        CCH_DATA        = "M:\DATASET\CCH_DBF\cch"+SUBSTR(ALLTRIM(DTOS(MY_COLL_DATE)),3,4)+'.dbf'
        IF RFILE(CCH_DATA)>=1
                RELEASE MYCCH
                ADIR(MYCCH,CCH_DATA)
                IF MYCCH(1,3)=DATE()
                        USE &CCH_DATA ALIAS CURRCCH IN 0 SHARED
                ELSE
                        CLOSE TABLES
                        MESSAGEBOX('今日的 CCH 資料尚未備妥,請稍後在執行!!!')
                        CANCEL
                ENDIF
        ELSE
                CLOSE TABLES
                MESSAGEBOX('今日的 CCH 資料尚未備妥,請稍後在執行!!!')
                CANCEL
        ENDIF
----END SAGE
*/
	IF ISNULL(@MY_COLL_DATE,'') <> ''
	BEGIN
	    DECLARE @CCH_CNT INT
		DECLARE @CCH_DATE DATE = DATEADD(day,-1,CAST(@MY_COLL_DATE AS DATE))
	    EXECUTE [dbo].[GET_CCH_COUNT_SP] @CCH_DATE,@CCH_CNT OUTPUT

		--IF (SELECT COUNT(*) FROM dbo.GET_CCH_FN(CONVERT(DATE , @MY_COLL_DATE , 111))) = 0
		IF ISNULL(@CCH_CNT,0) = 0
		BEGIN
			SET @MESSAGE= '今日的 CCH 資料尚未備妥,請稍後在執行!!!'
			RAISERROR(@MESSAGE,16,1)
		END
	END
	--20190111 對照完Table後調整
	TRUNCATE TABLE UIDRP_CACS_ROUTING_BP
	TRUNCATE TABLE UIDRP_CACS_ROUTING_KP
	TRUNCATE TABLE UIDRP_IDRP_BPBASE

--**** STEP 1 : 篩選ID資料   CONVERT(VARCHAR(10),REQ_DEBT_D ,111)  = yyyy/MM/dd
	SELECT CASENO, IDNO, OLDID, NAME, LEAD_BNK_N,  CONVERT(VARCHAR(10),REQ_DEBT_D ,111) AS REQ_DEBT_D, CONVERT(VARCHAR(10),FIRSTPAY_D ,111) AS FIRSTPAY_D, PMT_TENOR, PMT_APR, PMT_INST, IN_TOTAL, IFTWOSTAGE,IF_RW
	INTO #IDRP_CONTRACT_BASE
	FROM UIDRP_DE_IDRP_CUSTINFO 
	WHERE IFLEAD='Y' AND SIGN_D IS NOT NULL AND ( LEAD_BNK_N='021' OR  LEAD_BNK_N='976')
	AND FAIL_D IS NULL
	
--&& leading 全部簽約成功且無FAILE_D 的BASE
 


--****STEP 2 : 矯正資料
	--#IDRP_CONTRACT_BASE_IDTAG
	SELECT ISNULL(B.[NEWID],A.[IDNO]) AS ID_TAG, A.* 
	INTO #IDRP_CONTRACT_BASE_IDTAG
	FROM #IDRP_CONTRACT_BASE A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.IDNO=B.OLDID 
	--#CUSTINFO_IDTAG
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, A.*, CAST(NULL as varchar(1)) as DINERORNOT 
	INTO #CUSTINFO_IDTAG
	FROM UIDRP_CUS_BADRP_CUSTINFO A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID

	INSERT INTO #CUSTINFO_IDTAG 
	(
	   ID_TAG,[SEQNO],[MIS_DATE],[CUSTID],[CUSTNAME],[TENOR],[OPENDATE],[CLOSEDATE],[APR],[L_TYPE],[T_CITI],[T_ALLBANK]
      ,[CITI_CARD],[CITI_BANK],[CITI_WO],[CMPAY_CARD],[CMPAY_BANK],[CMPAY_WO],[LB_NAME],[LB_CODE],[NOR_PMT],[RW_C],[RWTYPE_C]
      ,[RWACT_CARD],[RW_B],[RWTYPE_B],[RWACCT_B],[DOCDATE],[REPDATE],[CUS_STATUS],[UPD_STATUS],[CUR_MONTH],[TEN_PAID],[M_USER],[M_DATE],[DINERORNOT],[TEL],[ADDR]
	)
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, 
	   A.[SEQNO],A.[MIS_DATE],A.[CUSTID],A.[CUSTNAME],A.[TENOR],A.[OPENDATE],A.[CLOSEDATE],A.[APR],A.[L_TYPE],A.[T_CITI],A.[T_ALLBANK]
	  ,A.[CITI_CARD],A.[CITI_BANK],A.[CITI_WO],A.[CMPAY_CARD],A.[CMPAY_BANK],A.[CMPAY_WO],A.[LB_NAME],A.[LB_CODE] ,A.[NOR_PMT],A.[RW_C],A.[RWTYPE_C]
      ,A.[RWACT_CARD],A.[RW_B],A.[RWTYPE_B],A.[RWACCT_B],A.[DOCDATE],A.[REPDATE],A.[CUS_STATUS],A.[UPD_STATUS],A.[CUR_MONTH],A.[TEN_PAID],A.[M_USER],A.[M_DATE],A.[DINERORNOT] ,'' ,''
	FROM UIDRP_CUS_IDRP_CUSTINFO A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID
	--#PAYMENTREC_IDTAG
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, A.* 
	INTO #PAYMENTREC_IDTAG
	FROM UIDRP_CUS_IDRP_PAYMENTREC A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID

	INSERT INTO #PAYMENTREC_IDTAG
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, A.* 
	FROM UIDRP_CUS_BADRP_PAYMENTREC A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID
	--#GRACE_IDTAG
	SELECT ISNULL(B.[NEWID],A.[IDNO]) AS ID_TAG, A.* 
	INTO #GRACE_IDTAG
	FROM UIDRP_DE_IDRP_GRACE2 A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.IDNO=B.OLDID


----BEGIN SAGE
--SELECT IIF(B.[NEWID] is null,A.CUSTID, B.[NEWID]) AS ID_TAG, A.* 
--FROM CITIDETAIL A LEFT JOIN CHGID B ON A.CUSTID=B.OLDID 
--WHERE !RIGHT(ALLT(A.CUSTID),1) $'ABCDEFGHIJKLMNOPQRSTUVWXYZ' INTO DBF CITIDETAIL_IDTAG --&&CUS鍵錯的資料，會把ID末碼改為英文字母

    --#CITIDETAIL_IDTAG
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, A.* 
	INTO #CITIDETAIL_IDTAG
	FROM UIDRP_CUS_IDRP_CITIDETAIL_VW A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID 
	WHERE CHARINDEX(RIGHT(dbo.ALLTRIM(A.CUSTID),1) , 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') > 0

	INSERT INTO #CITIDETAIL_IDTAG
	SELECT ISNULL(B.[NEWID],A.[CUSTID]) AS ID_TAG, A.* 
	FROM UIDRP_CUS_BADRP_CITIDETAIL_VW A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.CUSTID=B.OLDID 
	WHERE CHARINDEX(RIGHT(dbo.ALLTRIM(A.CUSTID),1) , 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') > 0

----END SAGE


--****STEP 3 : Mapping CUS 資料
 
	--當月應繳的BASE 已扣除協商失敗(或結清)但未扣除喘息 (NA) 
	SELECT A.*,B.OPENDATE, B.RWACT_CARD AS NARW_ACCT, B.RWACCT_B AS CTLRW_ACCT 
	INTO #CONTRACT_BASE_MAP_CUS
	FROM #IDRP_CONTRACT_BASE_IDTAG A 
	LEFT JOIN #CUSTINFO_IDTAG B ON A.ID_TAG=B.ID_TAG AND A.REQ_DEBT_D=B.DOCDATE AND A.LEAD_BNK_N=B.LB_CODE
	WHERE SUBSTRING(A.FIRSTPAY_D,1,8) <= CONVERT(VARCHAR(8) , @DATE4 , 111)  

----BEGIN SAGE
/*	SOURCE CODE
SELE * FROM CONTRACT_BASE_MAP_CUS WHERE ISNULL(FIRSTPAY_D) INTO CURS TKDN_NO_CUS
IF RECCOUNT()>0
	MESSAGEBOX(' TAKE DOWN ACCOUNT NO CUS DATA，請詳察',64)
	SELE TKDN_NO_CUS
	BROW
ENDIF
*/
----END SAGE

	SELECT * 
	INTO #SHOULDPAY_BASE 
	FROM #CONTRACT_BASE_MAP_CUS 
	WHERE FIRSTPAY_D IS NOT NULL

--***本行剩餘的債權資料
	SELECT ID_TAG, COUNT(*) AS UNSCU_CNT, SUM(BAL) AS UNSCU_AMT 
	INTO #CUS_CITIDETAIL
	FROM #CITIDETAIL_IDTAG 
	GROUP BY ID_TAG

--***繳款資料
	SELECT ID_TAG, SUM(REM_AMT) AS TTL_PAY, MAX(REC_DATE) AS LASTPAY_D 
	INTO #CUS_PAYMENT
	FROM #PAYMENTREC_IDTAG GROUP BY ID_TAG 

--***喘息資料 (已經過去的喘息期數)
	SELECT ID_TAG, COUNT(*) AS GTIME 
	INTO #CUS_GRACE
	FROM #GRACE_IDTAG 
	WHERE GRACE_YM_1 < DATEADD(MONTH,1,CONVERT(DATE,CONVERT(VARCHAR(8),GETDATE() ,111) +'10',111)) 
	GROUP BY ID_TAG

--***因房貸成為最大債權銀行 #TEMP2	-SECURE_DEBT 
	;WITH SECURE_DEBT
	AS
	(
		SELECT IDNO, COUNT(*) AS SCU_CNT, SUM(TTL_DEBT) AS SCU_AMT 	 
		FROM UIDRP_DE_IDRP_DEBTDTL 
		WHERE LEFT(CARDNMBR,2) IN ('11','15','17','18','19','21','25','26','27') AND CATEGORY NOT IN ('無擔') AND TTL_DEBT>0
		GROUP BY IDNO
	)
	SELECT ISNULL(B.[NEWID],A.[IDNO]) AS ID_TAG, A.* 
	INTO #SECURE_DEBT_IDTAG
	FROM SECURE_DEBT A 
	LEFT JOIN CHANGEIDBASE_GROUP_VW B ON A.IDNO=B.OLDID

----*** MAPPING  LASTPAY_D ??
	SELECT A.*
	     ,ISNULL(B.UNSCU_CNT,0) AS UNSCU_CNT, ISNULL(B.UNSCU_AMT,0) AS UNSCU_AMT
		 ,ISNULL(C.SCU_CNT,0) AS SCU_CNT, ISNULL(C.SCU_AMT,0) AS SCU_AMT
		 ,ISNULL(D.TTL_PAY,0) AS TTL_PAY,D.LASTPAY_D
		 ,ISNULL(E.GTIME,0) AS GTIME   
		 ,999 AS SHOULD_TEN, 9999999999 AS SHOULD_PAY, 9999999999 AS PAY_STATUS, SPACE(2) AS IFKP,SPACE(1) AS CHKML,SPACE(1) AS RE_NEGTI 
	INTO #SHOULDPAY_CHECK
	FROM #SHOULDPAY_BASE A 
	LEFT JOIN #CUS_CITIDETAIL B ON A.ID_TAG=B.ID_TAG
	LEFT JOIN #SECURE_DEBT_IDTAG C  ON A.ID_TAG=C.ID_TAG
	LEFT JOIN #CUS_PAYMENT D ON A.ID_TAG=D.ID_TAG
	LEFT JOIN #CUS_GRACE E ON A.ID_TAG=E.ID_TAG

	--SELECT A.*, ISNULL(C.SCU_CNT,0) AS SCU_CNT, ISNULL(C.SCU_AMT,0) AS SCU_AMT 
	--INTO #SHOULDPAY_MLDEBT
	--FROM #SHOULDPAY_CITIDETAIL A 
	--LEFT JOIN #SECURE_DEBT_IDTAG C  ON A.ID_TAG=C.ID_TAG

	--SELECT A.*, ISNULL(D.TTL_PAY,0) AS TTL_PAY,D.LASTPAY_D 
	--INTO #SHOULDPAY_PAYMENT
	--FROM #SHOULDPAY_MLDEBT A 
	--LEFT JOIN #CUS_PAYMENT D ON A.ID_TAG=D.ID_TAG
	--SELECT * FROM #CUS_PAYMENT

	--SELECT A.*, ISNULL(E.GTIME,0) AS GTIME 
	--INTO #SHOULDPAY_INFO
	--FROM #SHOULDPAY_PAYMENT A 
	--LEFT JOIN #CUS_GRACE E ON A.ID_TAG=E.ID_TAG



/**** Caculation
	&&20110603 新增加，用”變更"的RENGTI TABLE中的欄位，來判斷"變更”件是否BP，並增加欄位（是否為變更)，喘息的記錄也重新用新的首繳日之後的喘息記錄
	&&20110614 新增加，客戶KP，且繳款金額超過應繳金額達到2期以上的名單 (CHECK_PAY_OVER2_yyyymmdd.xls)
****/
	--SELECT *, 999 AS SHOULD_TEN, 9999999999 AS SHOULD_PAY, 9999999999 AS PAY_STATUS, SPACE(2) AS IFKP,SPACE(1) AS CHKML,SPACE(1) AS RE_NEGTI 
	--INTO #SHOULDPAY_CHECK
	--FROM #SHOULDPAY_INFO
	
----**新增清分年月判斷，有清分年月代表文件已齊全，才算正式進入變更流程中
----**清分年月為當月者 --> 依原本方案檢查
----**清分年月為前月者 --> 本月得不用繳款
----**清分年月為前月之前者 --> 依變更後方案檢查

/*	SOURCE CODE
	SELECT * FROM IDRP_RENGTI ORDER BY RECEIVE_D INTO CURSOR RENGTI2
	SELECT * FROM RENGTI2 GROUP BY IDNO INTO DBF RENGTI3
	SELECT * FROM RENGTI2 WHERE !ISNULL(SIGN_D) INTO CURSOR SIGNED_RENGTI1
	SELECT * FROM SIGNED_RENGTI1 GROUP BY IDNO INTO CURSOR SIGNED_RENGTI2
	SELECT * FROM SIGNED_RENGTI2 WHERE (ISNULL(FAIL_D) OR EMPTY(FAIL_D)) AND !ISNULL(SIGN_D) AND !EMPTY (SIGN_D) AND !ISNULL(FIRSTPAY_D) AND !EMPTY(FIRSTPAY_D) AND ALLTRIM(IDNO)+ALLTRIM(DTOS(GOMONTH(FIRSTPAY_D, -1))) IN (SELECT ALLTRIM(custid)+ALLTRIM(DTOS(CTOD(OPENDATE))) FROM CUSTINFO) INTO DBF RENGTI_SIGN_OK &&變更完成
	SELECT * FROM RENGTI3 WHERE (ISNULL(FAIL_D) OR EMPTY(FAIL_D)) AND (ISNULL(SIGN_D) OR EMPTY (SIGN_D)) AND IDNO NOT IN (SELECT IDNO FROM RENGTI_SIGN_OK) AND GOMONTH(DOCU_D,1) >= DATE() INTO DBF RENGTI_ING  &&變更中的LIST
	SELECT * FROM RENGTI3 WHERE (!ISNULL(FAIL_D) AND !EMPTY(FAIL_D)) OR (GOMONTH(DOCU_D,1) < DATE() AND ISNULL(SIGN_D)) INTO DBF RENGTI_FAIL &&變更失敗的LIST (OR GOMONTH(DOCU_D,1) < DATE())
	
*/
	-- SELECT * FROM UIDRP_IDRP_RENGTI_BACKUP A
	-- INNER JOIN (SELECT IDNO,MAX(RECEIVE_D) AS RECEIVE_ID FROM UIDRP_IDRP_RENGTI_BACKUP GROUP BY IDNO) AS B ON B.IDNO= A.IDNO AND B.RECEIVE_ID = A.RECEIVE_D

     --SELECT DISTINCT  * INTO RENGTI3 FROM UIDRP_IDRP_RENGTI_BACKUP 	 
	 --ORDER BY RECEIVE_D
	 --變更完成
	 SELECT A.* INTO #RENGTI_SIGN_OK 
	 FROM UIDRP_IDRP_RENGTI_BACKUP A
	 INNER JOIN (SELECT IDNO,MAX(RECEIVE_D) AS RECEIVE_ID FROM UIDRP_IDRP_RENGTI_BACKUP GROUP BY IDNO) AS B ON B.IDNO= A.IDNO AND B.RECEIVE_ID = A.RECEIVE_D
	 INNER JOIN  UIDRP_CUSTINFO C ON dbo.ALLTRIM(A.IDNO) = C.CUSTID AND CONVERT(VARCHAR(10),DATEADD(MONTH ,-1,A.FIRSTPAY_D),111) = CONVERT(VARCHAR(10),C.OPENDATE,111)
	 WHERE A.SIGN_D IS NOT NULL  AND A.FAIL_D IS NULL  AND A.FIRSTPAY_D IS NOT NULL	 
	  

	--變更中的LIST
    SELECT A.* INTO #RENGTI_ING 
	FROM UIDRP_IDRP_RENGTI_BACKUP A
    INNER JOIN (SELECT IDNO,MAX(RECEIVE_D) AS RECEIVE_ID FROM UIDRP_IDRP_RENGTI_BACKUP GROUP BY IDNO) AS B ON B.IDNO= A.IDNO AND B.RECEIVE_ID = A.RECEIVE_D	 
	WHERE A.FAIL_D IS NULL AND A.SIGN_D IS NULL 
	AND A.IDNO NOT IN (SELECT IDNO FROM #RENGTI_SIGN_OK) AND DATEADD(MONTH,1,A.DOCU_D) >= GETDATE() --INTO DBF RENGTI_ING  &&變更中的LIST

	--變更失敗的LIST (OR GOMONTH(DOCU_D,1) < DATE())
	SELECT A.* INTO #RENGTI_FAIL 
	FROM UIDRP_IDRP_RENGTI_BACKUP A 	 
	INNER JOIN (SELECT IDNO,MAX(RECEIVE_D) AS RECEIVE_ID FROM UIDRP_IDRP_RENGTI_BACKUP GROUP BY IDNO) AS B ON B.IDNO= A.IDNO AND B.RECEIVE_ID = A.RECEIVE_D	 
	WHERE A.FAIL_D IS NOT NULL OR (DATEADD(MONTH,1,A.DOCU_D) < GETDATE() AND A.SIGN_D IS NULL)	
	
	ALTER TABLE #RENGTI_SIGN_OK ADD PRIMARY KEY (IDNO);
	ALTER TABLE #RENGTI_ING ADD PRIMARY KEY (IDNO);
	ALTER TABLE #RENGTI_FAIL ADD PRIMARY KEY (IDNO);
	
 
	UPDATE A
	SET A.RE_NEGTI = '1'	--&&Ivan to change indicator to 1/2/3 **1的表示是變更方案簽約完成的accounts, 如果是2就是簽約中, and 3就是變更失敗
	,A.REQ_DEBT_D = B.REQ_DEBT_D
	,A.FIRSTPAY_D = B.FIRSTPAY_D
	,A.PMT_TENOR = B.PMT_TENOR1
	,A.PMT_APR = B.PMT_APR1
	,A.PMT_INST = B.PMT_INST1
	FROM #SHOULDPAY_CHECK A
	INNER JOIN #RENGTI_SIGN_OK B ON A.IDNO = B.IDNO

	UPDATE A
	SET A.RE_NEGTI = '2'	-- &&Ivan to change indicator to 1/2/3
	FROM #SHOULDPAY_CHECK A
	INNER JOIN #RENGTI_ING B ON A.IDNO = B.IDNO
	WHERE ISNULL(A.RE_NEGTI,'') = ''


	UPDATE A
	SET A.RE_NEGTI = '3'	--&&Ivan to change indicator to 1/2/3
	FROM #SHOULDPAY_CHECK A
	INNER JOIN #RENGTI_FAIL B ON A.IDNO = B.IDNO
	WHERE ISNULL(A.RE_NEGTI,'') = ''
	
----&&Ivan 0711 抓failed case的上一個pmt plan from either 上一次變更or 在custinfo的pmt plan
	
/*	SOURCE CODE	BEGIN SAGE
	SELECT * FROM IDRP_RENGTI WHERE IDNO IN (SELECT IDNO FROM SHOULDPAY_CHECK WHERE RE_NEGTI='3') and (EMPTY(FAIL_D) OR ISNULL(FAIL_D)) OR FAIL_RESN='C' AND !ISNULL(FIRSTPAY_D) INTO DBF RENEGTI3_UPDPMTPLAN
	SELE * FROM RENEGTI3_UPDPMTPLAN ORDER BY RECEIVE_D INTO DBF RENEGTI3_UPDPMTPLAN1
	SELE * FROM RENEGTI3_UPDPMTPLAN1 GROUP BY IDNO INTO DBF RENEGTI3_UPDPMTPLAN2
	SELECT * FROM IDRP_CONTRACT_BASE WHERE  IDNO IN (SELECT IDNO FROM SHOULDPAY_CHECK WHERE RE_NEGTI='3') AND IDNO NOT IN (SELEC IDNO FROM RENEGTI3_UPDPMTPLAN2) INTO DBF RENEGTI3_UPDPMTPLAN3
	SELEC RENEGTI3_UPDPMTPLAN2
	APPEND FROM RENEGTI3_UPDPMTPLAN3
	
	SELEC RENEGTI3_UPDPMTPLAN3
	INDEX ON IDNO TAG IDNO
	
	SELE  SHOULDPAY_CHECK
	SCAN
		SCATTER MEMVAR
		SELE RENEGTI3_UPDPMTPLAN3
		IF SEEK(ALLTRIM(M.IDNO))
			M.REQ_DEBT_D=REQ_DEBT_D
			M.FIRSTPAY_D=FIRSTPAY_D
			M.PMT_TENOR=PMT_TENOR
			M.PMT_APR=PMT_APR	
			M.PMT_INST=PMT_INST
			SELE SHOULDPAY_CHECK
			GATHER MEMVAR
		ENDIF
	ENDSCAN
			
	SELE * FROM GRACE_IDTAG A LEFT JOIN SHOULDPAY_CHECK B ON ALLTRIM(A.ID_TAG)=ALLTRIM(B.ID_TAG) INTO DBF RENGTI_GRACE
	*SELE * FROM RENGTI_GRACE WHERE RE_NEGTI='Y' AND CTOD(TTOC(GRACE_YM_1))>=CTOD(FIRSTPAY_D) INTO DBF RENGTI_GRACE1
	SELE * FROM RENGTI_GRACE WHERE RE_NEGTI='1' AND TTOD(GRACE_YM_1)>=CTOD(FIRSTPAY_D) INTO DBF RENGTI_GRACE1
	
	SELE ID_TAG_A AS ID_TAG, COUNT(*) AS GTIME FROM RENGTI_GRACE1 GROUP BY ID_TAG INTO DBF RENGTI_GRACE2
	
	SELE RENGTI_GRACE2
	INDEX ON ALLTRIM(ID_TAG) TAG IDNO
	
	SELE  SHOULDPAY_CHECK
	SCAN FOR RE_NEGTI='1'
		SCATTER MEMVAR
		SELE RENGTI_GRACE2
		SEEK ALLTRIM(M.ID_TAG)
		IF FOUND()
			M.GTIME=GTIME
		ELSE
			M.GTIME=0
		ENDIF
		SELE SHOULDPAY_CHECK
		GATHER MEMVAR
	SELE SHOULDPAY_CHECK
	ENDSCAN		
*/

	--SELECT #SHOULDPAY_CHECK		
	--STARTDATE=CTOD(SUBSTR(DTOC(DATE4),1,8)+'10') 
	
	;WITH RENEGTI3_UPDPMTPLAN
	AS
	(
		SELECT DISTINCT IDNO FROM UIDRP_IDRP_RENGTI_BACKUP
		WHERE IDNO IN (SELECT IDNO FROM #SHOULDPAY_CHECK WHERE RE_NEGTI = '3')
		AND FAIL_D IS NULL OR FAIL_RESN = 'C' AND FIRSTPAY_D IS NOT NULL
	)
	SELECT * 
	INTO #RENEGTI3_UPDPMTPLAN3
	FROM #IDRP_CONTRACT_BASE 
	WHERE IDNO IN (SELECT IDNO FROM #SHOULDPAY_CHECK WHERE RE_NEGTI = '3')
	AND IDNO NOT IN (SELECT IDNO FROM RENEGTI3_UPDPMTPLAN)

	UPDATE A
	SET A.REQ_DEBT_D = B.REQ_DEBT_D
	,A.FIRSTPAY_D = A.FIRSTPAY_D
	,A.PMT_TENOR = B.PMT_TENOR
	,A.PMT_APR = B.PMT_APR
	,A.PMT_INST = B.PMT_INST
	FROM #SHOULDPAY_CHECK A
	INNER JOIN #RENEGTI3_UPDPMTPLAN3 B ON A.IDNO = B.IDNO
 

	SELECT dbo.ALLTRIM(A.ID_TAG) AS ID_TAG, COUNT(*) AS GTIME 
	INTO #RENGTI_GRACE2 
	FROM #GRACE_IDTAG A
	LEFT JOIN #SHOULDPAY_CHECK B ON dbo.ALLTRIM(A.ID_TAG) = dbo.ALLTRIM(B.ID_TAG)
	WHERE RE_NEGTI = '1' AND CONVERT(VARCHAR(10), A.GRACE_YM_1,111) >= CONVERT(VARCHAR(10), B.FIRSTPAY_D ,111)
	GROUP BY A.ID_TAG

	--SELECT * FROM #SHOULDPAY_CHECK
	--ALTER TABLE #RENGTI_GRACE2 ADD PRIMARY KEY (ID_TAG);

	UPDATE A
	SET A.GTIME =IIF(B.ID_TAG IS NOT NULL, 0,B.GTIME)
	FROM #SHOULDPAY_CHECK A
	LEFT JOIN #RENGTI_GRACE2 B ON A.IDNO = B.ID_TAG
	
	DECLARE @STARTDATE VARCHAR(10)
	SET @STARTDATE = CONVERT(VARCHAR(8), @DATE4 ,111)+'10'

	UPDATE #SHOULDPAY_CHECK SET CHKML='Y' WHERE UNSCU_CNT=0 AND SCU_CNT>0
	
----**更正於2011/7/27，之前計算從首繳日開始到這個月，經過幾個月是STARTDATE-CTOD(FIRSTPAY_D))/30+1，此計算公式會因為大小月，而導致繳款36期以上的客人的應繳期數和應繳金額會有誤
----**因此計算公式改成(year(STARTDATE)-year(CTOD(FIRSTPAY_D)))*12+(month(STARTDATE)-month(CTOD(FIRSTPAY_D)))+1
----**修改SHOULD_TEN計算方式(JURE 2011/8/31)	

	
	UPDATE #SHOULDPAY_CHECK
	SET SHOULD_TEN = (DATEDIFF(YEAR,  FIRSTPAY_D, @STARTDATE) * 12) + (DATEDIFF(MONTH, FIRSTPAY_D,@STARTDATE ) +1)
	WHERE ISNULL(FIRSTPAY_D,'') <> '' AND MONTH(CAST(@STARTDATE AS DATE)) >= MONTH(CAST(FIRSTPAY_D AS DATE))

	/*	SOURCE CODE
	UPDATE #SHOULDPAY_CHECK SET SHOULD_TEN=(YEAR(STARTDATE)-YEAR(CTOD(FIRSTPAY_D))-1)*12+((MONTH(STARTDATE)+12)-MONTH(CTOD(FIRSTPAY_D)))+1 WHERE !EMPTY(CTOD(FIRSTPAY_D)) AND MONTH(STARTDATE)<MONTH(CTOD(FIRSTPAY_D))
	*/
	UPDATE #SHOULDPAY_CHECK 
	SET SHOULD_TEN=((DATEDIFF(YEAR, FIRSTPAY_D,@STARTDATE) - 1) * 12) + (DATEDIFF(MONTH, FIRSTPAY_D,@STARTDATE) + 12 + 1) 
	WHERE ISNULL(FIRSTPAY_D,'') <> '' AND MONTH(CAST(@STARTDATE AS DATE)) < MONTH(CAST(FIRSTPAY_D AS DATE))

/* SOURCE CODE
	*********************************************************************************
	UPDATE SHOULDPAY_CHECK SET SHOULD_PAY=SHOULD_TEN*VAL(PMT_INST)
	UPDATE SHOULDPAY_CHECK SET SHOULD_TEN=SHOULD_TEN-GTIME
	UPDATE SHOULDPAY_CHECK SET SHOULD_PAY=SHOULD_TEN*VAL(PMT_INST)
	UPDATE SHOULDPAY_CHECK SET PAY_STATUS=IIF(ISNULL(TTL_PAY),0,TTL_PAY)-SHOULD_PAY
	UPDATE SHOULDPAY_CHECK SET IFKP='KP' WHERE PAY_STATUS>=0 AND RE_NEGTI <> '2' &&2014/01/28 將RE_NEGTI=3拿掉
	****************************************************************
*/

	--UPDATE #SHOULDPAY_CHECK SET SHOULD_PAY = SHOULD_TEN * PMT_INST
	UPDATE #SHOULDPAY_CHECK SET SHOULD_TEN = SHOULD_TEN - GTIME
	UPDATE #SHOULDPAY_CHECK SET SHOULD_PAY = SHOULD_TEN * PMT_INST
	UPDATE #SHOULDPAY_CHECK SET PAY_STATUS= ISNULL(TTL_PAY,0) - SHOULD_PAY
	UPDATE #SHOULDPAY_CHECK SET IFKP='KP' WHERE PAY_STATUS>=0 AND ISNULL(RE_NEGTI,'') <> '2'

	--select * from #SHOULDPAY_CHECK
/*	SOURCE CODE
	SELECT * FROM  SHOULDPAY_CHECK WHERE PMT_TENOR< SHOULD_TEN OR (PMT_TENOR= SHOULD_TEN AND IFKP='KP')  INTO DBF PAYOFFLIST
	COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\CHECK_PAYOFF_'+ALLT(DTOS(DATE())) XL5
*/
	INSERT INTO @PAYOFFLIST
	SELECT * FROM #SHOULDPAY_CHECK WHERE PMT_TENOR < SHOULD_TEN OR (PMT_TENOR= SHOULD_TEN AND IFKP='KP')
	--SELECT * FROM #PAYOFFLIST

	INSERT INTO @PAY_OVER4
	SELECT * FROM #SHOULDPAY_CHECK WHERE IFKP='KP' AND ((TTL_PAY-SHOULD_PAY)/PMT_INST)>=4
	--COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\CHECK_PAY_OVER4_'+ALLT(DTOS(DATE())) XL5
	--SELECT * FROM #PAY_OVER4
	
	DECLARE @Y21PAYOFF TABLE
	(
		CUSTID VARCHAR(10)
		,ID_TAG VARCHAR(10)
	)

	INSERT INTO @Y21PAYOFF
	SELECT A.CUSTID,A.ID_TAG FROM
	(  SELECT CUSTID, ID_TAG FROM DS_CARDS_VW WHERE CACS_STATE ='Y21' 
	   UNION ALL	
	   SELECT CUSTID, ID_TAG FROM DS_BUDTRAN_VW WHERE CACS_STATE ='Y21'
	) AS A
	
	INSERT INTO @PAYOFFLIST_ALLBANK
	SELECT A.ID_TAG AS CUSTID,A.NAME,B.BANKCODE,B.BANKNAME,B.OSBAL, IIF(C.CUSTID = A.ID_TAG OR C.ID_TAG = A.ID_TAG,'Y21','   ') AS CACS_STATE FROM @PAYOFFLIST A
	LEFT JOIN UIDRP_CUS_IDRP_ALLBANKDETAIL B ON dbo.ALLTRIM(A.ID_TAG)=dbo.ALLTRIM(B.CUSTID) --INTO DBF PAYOFFLIST_ALLBANK
	LEFT JOIN @Y21PAYOFF C ON C.CUSTID = A.ID_TAG OR C.ID_TAG = A.ID_TAG

	--INSERT INTO @PAYOFFLIST_ALLBANK
	--SELECT A.ID_TAG AS CUSTID,A.NAME,B.BANKCODE,B.BANKNAME,B.OSBAL, '   ' AS CACS_STATE FROM @PAYOFFLIST A
	--LEFT JOIN UIDRP_CUS_BADRP_ALLBANKDETAIL B ON dbo.ALLTRIM(A.ID_TAG)=dbo.ALLTRIM(B.CUSTID) --INTO DBF PAYOFFLIST_ALLBANK

	--UPDATE @PAYOFFLIST_ALLBANK SET CACS_STATE ='Y21' 
	--WHERE CUSTID IN (SELECT CUSTID FROM @Y21PAYOFF) OR CUSTID IN (SELECT ID_TAG FROM @Y21PAYOFF)

	DELETE FROM #SHOULDPAY_CHECK WHERE PMT_TENOR < SHOULD_TEN   --&& 當月期滿KP的先保留 只出PAYOFF CHECK 就好

----**** STEP 4 : 篩選BP資料

	SELECT *  
	INTO #IDRP_BPID 
	FROM #SHOULDPAY_CHECK 
	WHERE IFKP<>'KP'
	
	--DECLARE @WHERE VARCHAR(500)
	--DECLARE @DATEAS DATETIME = GETDATE() -1
	--SELECT TOP 0 * INTO #CARDS FROM DS_CARDS_VW
	--SET @WHERE ='INNER JOIN #IDRP_BPID B ON DS.ID_TAG=B.ID_TAG WHERE MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #CARDS   EXECUTE dbo.GET_DS_SP 'CARDS',@DATEAS,@WHERE ,N''

	--SELECT TOP 0 * INTO #BUDTRAN FROM DS_BUDTRAN_VW
	--SET @WHERE ='INNER JOIN #IDRP_BPID B ON DS.ID_TAG=B.ID_TAG WHERE MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #BUDTRAN   EXECUTE dbo.GET_DS_SP 'BUDTRAN',@DATEAS,@WHERE ,N''

----**** STEP 5 : MAPPING ACCTNMBR FROM CACS / IDRP_BASE / ALSEOM
	;WITH CACS
	AS
	(
		SELECT A.*  
		FROM (
			SELECT ID_TAG, LEFT(CUSTID+SPACE(8),10)  AS IDNO, CARDNMBR, LOCATION, CACS_STATE  AS CURRSTATE, LOGO AS ACCTTYPE 
			FROM dbo.DS_CARDS_VW 
			UNION ALL
			SELECT ID_TAG, LEFT(CUSTID+SPACE(8),10) AS IDNO, CARDNMBR, LOCATION, CACS_STATE AS CURRSTATE, ACCTTYPE 
			FROM dbo.DS_BUDTRAN_VW
			) AS A
	)
----&&FROM CACS  --CACS 中mapping 不到account 的ID 應為"因房貸成為最大債權行，而房貸本身無delq，或房貸本身已結清" or 企金的account
	SELECT A.*,B.CARDNMBR, B.ACCTTYPE,B.CURRSTATE,B.LOCATION,'FROM_CACS' AS SOURCE 
	INTO #BP_ACCT_MAP_CACS
	FROM #IDRP_BPID A 
	LEFT JOIN CACS B ON A.ID_TAG=B.ID_TAG

	SELECT ID_TAG
	INTO #NOT_IN_CACS
	FROM #BP_ACCT_MAP_CACS 
	WHERE CARDNMBR IS NULL OR CHKML='Y'

	SELECT ID_TAG, CARDNMBR, PRODTYPE, ACCTTYPE
	INTO #CPMB_ACCT
	FROM UIDRP_IDRP_BASE 
	WHERE ID_TAG IN (SELECT ID_TAG FROM #NOT_IN_CACS)

----&&FROM IDRP_BASE  --IDRP_BASE 中 又mapping 不到account 的ID 應為"因房貸成為最大債權行，而房貸本身已結清" or 企金的account
	SELECT A.*, B.CARDNMBR, B.ACCTTYPE, SPACE(3) AS CURRSTATE, SPACE(6) AS LOCATION,'FROM_IBAS' AS [SOURCE]
	INTO #BP_ACCT_MAP_IBASE_ALL 
	FROM #IDRP_BPID A 
	LEFT JOIN #CPMB_ACCT B ON A.ID_TAG=B.ID_TAG 
	WHERE A.ID_TAG IN (SELECT ID_TAG FROM #NOT_IN_CACS)

	SELECT * 
	INTO #BP_ACCT_MAP_IBASE
	FROM #BP_ACCT_MAP_IBASE_ALL 
	WHERE CARDNMBR NOT IN (SELECT CARDNMBR FROM #BP_ACCT_MAP_CACS) --&&為了抓出只有一張卡在CACS-G99 ,因後段程式會被踢掉 (CHKML='Y')
	
	SELECT * 
	INTO #NOT_IN_IBASE
	FROM #BP_ACCT_MAP_IBASE_ALL 
	WHERE CARDNMBR IS NULL

----&&FROM ALSEOM  --ALSEOM 中 又mapping 不到account 的ID 應為企金的account	
	SELECT A.*, LEFT(B.CARDNMBR+SPACE(16),16) AS CARDNMBR, B.ACCTTYPE, SPACE(3) AS CURRSTATE, SPACE(6) AS LOCATION,'FROM_AEOM' AS SOURCE 
	INTO #BP_ACCT_MAP_ALSEOM
	FROM #IDRP_BPID A 
	LEFT JOIN dbo.GET_ALSEOM_FN(DATEADD(DAY,-1,@DATE4)) B ON A.ID_TAG=B.ID_TAG 
	WHERE A.ID_TAG IN (SELECT ID_TAG FROM #NOT_IN_IBASE)

----&&合併所有的ACCOUNT
	SELECT A.* 
	INTO #BP_ACCT
	FROM (
		SELECT * FROM #BP_ACCT_MAP_CACS WHERE CARDNMBR IS NOT NULL
		UNION ALL
		SELECT * FROM #BP_ACCT_MAP_IBASE WHERE CARDNMBR IS NOT NULL
		UNION ALL
		SELECT * FROM #BP_ACCT_MAP_ALSEOM
		) A
	

	UPDATE #BP_ACCT SET LOCATION='020007' WHERE LOCATION = '' AND ACCTTYPE IN ('749','757','755')
	UPDATE #BP_ACCT SET LOCATION='020006' WHERE LOCATION = '' AND ACCTTYPE IN ('770')
	UPDATE #BP_ACCT SET LOCATION='860102' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,3) IN ('120')
	UPDATE #BP_ACCT SET LOCATION='860107' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,3) IN ('130','160','310','320')
	UPDATE #BP_ACCT SET LOCATION='860103' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,3) IN ('110','150','170','180','190')
	UPDATE #BP_ACCT SET LOCATION='860104' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,3) IN ('210','250','260','270')
	UPDATE #BP_ACCT SET LOCATION='860106' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,3) IN ('220','280')
	UPDATE #BP_ACCT SET LOCATION='020101' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,1) IN ('4','5') AND LEN(dbo.ALLTRIM(CARDNMBR))=16
	UPDATE #BP_ACCT SET LOCATION='510010' WHERE LOCATION = '' AND SUBSTRING(CARDNMBR,1,2)='36' AND LEN(dbo.ALLTRIM(CARDNMBR))=14


	--DECLARE @WHERE VARCHAR(500)
	--DECLARE @DATEAS DATETIME = GETDATE() -1

	--SELECT TOP 0 * INTO #REC FROM DS_REC_COMBO_VW
	--SET @WHERE = 'INNER JOIN #BP_ACCT B ON DS.CARDNMBR = B.CARDNMBR WHERE MIS_DATE='''+CONVERT(VARCHAR(10),@DATEAS,111)+''' '
	--INSERT INTO #REC   EXECUTE dbo.GET_DS_SP 'REC_COMBO',@DATEAS,@WHERE ,N''

	SELECT DISTINCT A.*
	--, IIF(B.WODATE IS NULL,'//', B.WODATE) AS WODATE
	,B.WODATE AS WODATE
	,ISNULL(B.STATUS1,SPACE(3)) AS STATUS1,ISNULL(B.OA,SPACE(4)) AS OA , SPACE(1) AS DEL_RESN,SPACE(10) AS RCODE, SPACE(80) AS REMARK 
	INTO #BPAC_MTD
	FROM #BP_ACCT A 
	--BEGIN SAGE 條件 B.CARDNMBR 缺欄位
	--LEFT JOIN DS_REC_COMBO_VW B ON A.CARDNMBR=B.CARDNMBR
	LEFT JOIN dbo.DS_REC_COMBO_VW B ON A.CARDNMBR=B.CARDNMBR
/*	SOURCE CODE
*!*	**** STEP 6 : 踢退account
UPDATE BPAC_MTD SET DEL_RESN='A' WHERE EMPTY(DEL_RESN) AND SUBS(CURRSTATE,1,1) NOT IN ('N','Y') AND (SUBSTR(ALLTRIM(STATUS1),1,1) IN ('D', 'A', '9' ) AND SUBSTR(ALLTRIM(STATUS1),1,2) NOT IN ('96', '97','D6','D7','A6','A7' ) AND SUBSTR(ALLTRIM(STATUS1),1,3) NOT IN ('941', '993'))
*UPDATE BPAC_MTD SET DEL_RESN='C' WHERE EMPTY(DEL_RESN) AND SUBS(CURRSTATE,1,2) IN ('S9','G9')
UPDATE BPAC_MTD SET DEL_RESN='C' WHERE EMPTY(DEL_RESN) AND SUBS(CURRSTATE,1,2) IN ('S9')
UPDATE BPAC_MTD SET DEL_RESN='X' WHERE EMPTY(DEL_RESN) AND SUBS(CARDNMBR,1,3) IN ('110','150','170','180','190','210','250','260','270') AND CARDNMBR NOT IN (SELE ACCTNMBR FROM CITIDETAIL_IDTAG ) &&未 FUNDING 於 CUS 的 ML
*/

----*!*	**** STEP 6 : 踢退account
	UPDATE #BPAC_MTD SET DEL_RESN='A' 
	WHERE DEL_RESN = '' AND SUBSTRING(CURRSTATE,1,1) NOT IN ('N','Y') AND (SUBSTRING(dbo.ALLTRIM(STATUS1),1,1) IN ('D', 'A', '9' ) AND SUBSTRING(dbo.ALLTRIM(STATUS1),1,2) NOT IN ('96', '97','D6','D7','A6','A7' ) AND SUBSTRING(dbo.ALLTRIM(STATUS1),1,3) NOT IN ('941', '993'))
	--*UPDATE BPAC_MTD SET DEL_RESN='C' WHERE EMPTY(DEL_RESN) AND SUBS(CURRSTATE,1,2) IN ('S9','G9')
	UPDATE #BPAC_MTD SET DEL_RESN='C' 
	WHERE DEL_RESN = '' AND SUBSTRING(CURRSTATE,1,2) IN ('S9')
	UPDATE #BPAC_MTD SET DEL_RESN='X' 
	WHERE DEL_RESN = '' AND SUBSTRING(CARDNMBR,1,3) IN ('110','150','170','180','190','210','250','260','270') 
		AND CARDNMBR NOT IN (SELECT ACCTNMBR FROM #CITIDETAIL_IDTAG ) ----&&未 FUNDING 於 CUS 的 ML

----**** STEP 7 : 註記ACCOUNT TYPE
	UPDATE #BPAC_MTD SET RCODE=dbo.ALLTRIM(RCODE)+'A', REMARK=IIF(dbo.ALLTRIM(REMARK) = '','',dbo.ALLTRIM(REMARK)+' /')+'本行已無無擔債權' WHERE UNSCU_AMT=0
	UPDATE #BPAC_MTD SET RCODE=dbo.ALLTRIM(RCODE)+'B', REMARK=IIF(dbo.ALLTRIM(REMARK) = '','',dbo.ALLTRIM(REMARK)+' /')+'因房貸成為最大債權行' WHERE UNSCU_CNT=0 AND SCU_CNT>0 AND CARDNMBR IS NOT NULL
	UPDATE #BPAC_MTD SET RCODE=dbo.ALLTRIM(RCODE)+'C', REMARK=IIF(dbo.ALLTRIM(REMARK) = '','',dbo.ALLTRIM(REMARK)+' /')+'本行已無有效帳戶' WHERE SOURCE='FROM_AEOM' AND CARDNMBR IS NOT NULL
	UPDATE #BPAC_MTD SET RCODE=dbo.ALLTRIM(RCODE)+'D', REMARK=IIF(dbo.ALLTRIM(REMARK) = '','',dbo.ALLTRIM(REMARK)+' /')+'Collection 無有效帳戶，請確認是否為企金戶' WHERE SOURCE='FROM_AEOM' AND CARDNMBR IS NULL

	SELECT * 
	INTO #IDRP_BPBASE 
	FROM #BPAC_MTD 
	WHERE (DEL_RESN = '' OR (DEL_RESN='X' AND RCODE <> '')) AND RE_NEGTI <> '2'

	INSERT INTO @IDRP_BPBASE_1
	SELECT * 
	FROM #BPAC_MTD 
	WHERE DEL_RESN = '' OR (DEL_RESN='X' AND RCODE <> '')

	INSERT INTO UIDRP_IDRP_BPBASE
	(
	 PRCDATE,ID_TAG ,CASENO,IDNO,OLDID,NAME,LEAD_BNK_N ,REQ_DEBT_D ,FIRSTPAY_D ,PMT_TENOR ,PMT_APR ,PMT_INST ,IN_TOTAL ,IFTWOSTAGE ,IF_RW 
	,OPENDATE ,NARW_ACCT ,CTLRW_ACCT ,UNSCU_CNT ,UNSCU_AMT ,SCU_CNT ,SCU_AMT ,TTL_PAY ,LASTPAY_D ,GTIME ,SHOULD_TEN ,SHOULD_PAY ,PAY_STATUS 
	,IFKP ,CHKML ,RE_NEGTI ,CARDNMBR ,ACCTTYPE,CURRSTATE,LOCATION,SOURCE ,WODATE ,STATUS1 ,OA,DEL_RESN ,RCODE ,REMARK 
	)
	SELECT CONVERT(VARCHAR(10) ,GETDATE(),111),ID_TAG ,CASENO ,IDNO,OLDID ,NAME,LEAD_BNK_N ,REQ_DEBT_D ,FIRSTPAY_D ,PMT_TENOR ,PMT_APR ,PMT_INST ,IN_TOTAL ,IFTWOSTAGE ,IF_RW 
	,OPENDATE ,NARW_ACCT ,CTLRW_ACCT ,UNSCU_CNT ,UNSCU_AMT ,SCU_CNT ,SCU_AMT ,TTL_PAY ,LASTPAY_D ,GTIME ,SHOULD_TEN ,SHOULD_PAY ,PAY_STATUS 
	,IFKP ,CHKML ,RE_NEGTI ,CARDNMBR ,ACCTTYPE,CURRSTATE,LOCATION,SOURCE ,WODATE ,STATUS1 ,OA,DEL_RESN ,RCODE ,REMARK 	
	FROM #BPAC_MTD 
	WHERE DEL_RESN = '' OR (DEL_RESN='X' AND RCODE <> '')


	/*
	
COPY TO 'DBF\IDRP_BPBASE_'+ALLT(DTOS(DATE()))  
*FOR ACCOUNT 皆為不繞STATE的CASE
SELECT * FROM BPAC_MTD WHERE IDNO NOT IN (SELECT IDNO FROM IDRP_BPBASE) INTO DBF TMP_BPBASE
SELECT IDRP_BPBASE_1
APPEND FROM TMP_BPBASE


*COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\DETAIL\IDRP_BPBASE_'+ALLT(DTOS(DATE())) XL5  
COPY TO 'DBF\IDRP_BPBASE_'+SUBS(DTOS(DATE()),1,6)  
&&DEL_RESN='X' AND !EMPTY(REMARK) 	應為未FUNDING於CUS的ML, 但只有這張卡可繞
&&DEL_RESN='X' AND !EMPTY(RCODE) 	應為在CACS 中的 SECURE ACCOUNT ，純下CCH
SELE IDRP_BPID
REC_ID=RECCOUNT()
SELE IDRP_BPBASE  
REC_AC=RECCOUNT()

MESSAGEBOX('今日IDRP 月付金未足額，共 '+ALLT(STR(REC_ID))+ ' 筆 ID；'+ALLT(STR(REC_AC))+ ' 筆 ACCOUNT',64)

SELE * FROM IDRP_BPBASE WHERE ISNULL(CARDNMBR) INTO DBF NO_ACCT
SELE NO_ACCT
IF RECCOUNT()>0
	MESSAGEBOX('今日IDRP 月付金未足額，有 '+ALLT(STR(RECCOUNT()))+ ' 筆查無帳號可執行',64)
	BROW
ENDIF

	*/
	--FOR ACCOUNT 皆為不繞STATE的CASE
	INSERT INTO @IDRP_BPBASE_1
	SELECT * FROM #BPAC_MTD WHERE IDNO NOT IN (SELECT IDNO FROM #IDRP_BPBASE)
	

	INSERT INTO UIDRP_IDRP_BPBASE
	(
	 PRCDATE,ID_TAG,CASENO ,IDNO,OLDID ,NAME,LEAD_BNK_N ,REQ_DEBT_D ,FIRSTPAY_D ,PMT_TENOR ,PMT_APR ,PMT_INST ,IN_TOTAL ,IFTWOSTAGE ,IF_RW 
	,OPENDATE ,NARW_ACCT ,CTLRW_ACCT ,UNSCU_CNT ,UNSCU_AMT ,SCU_CNT ,SCU_AMT ,TTL_PAY ,LASTPAY_D ,GTIME ,SHOULD_TEN ,SHOULD_PAY ,PAY_STATUS 
	,IFKP ,CHKML ,RE_NEGTI ,CARDNMBR ,ACCTTYPE,CURRSTATE,LOCATION,SOURCE ,WODATE ,STATUS1 ,OA,DEL_RESN ,RCODE ,REMARK 
	)
	SELECT CONVERT(VARCHAR(10) ,GETDATE(),111),ID_TAG ,CASENO ,IDNO,OLDID ,NAME,LEAD_BNK_N ,REQ_DEBT_D ,FIRSTPAY_D ,PMT_TENOR ,PMT_APR ,PMT_INST ,IN_TOTAL ,IFTWOSTAGE ,IF_RW 
	,OPENDATE ,NARW_ACCT ,CTLRW_ACCT ,UNSCU_CNT ,UNSCU_AMT ,SCU_CNT ,SCU_AMT ,TTL_PAY ,LASTPAY_D ,GTIME ,SHOULD_TEN ,SHOULD_PAY ,PAY_STATUS 
	,IFKP ,CHKML ,RE_NEGTI ,CARDNMBR ,ACCTTYPE,CURRSTATE,LOCATION,SOURCE ,WODATE ,STATUS1 ,OA,DEL_RESN ,RCODE ,REMARK 	
	FROM #BPAC_MTD 
	WHERE IDNO NOT IN (SELECT IDNO FROM #IDRP_BPBASE)


 


	DECLARE @REC_ID INT
	,@REC_AC INT

	SELECT @REC_ID = COUNT(*) FROM #IDRP_BPID
	SELECT @REC_AC = COUNT(*) FROM #IDRP_BPBASE
	SET @MESSAGE = @MESSAGE + CHAR(13) + '今日IDRP 月付金未足額，共 '+CAST(@REC_ID AS VARCHAR(10))+ ' 筆 ID；'+CAST(@REC_AC AS VARCHAR(10))+ ' 筆 ACCOUNT'
	
	DECLARE @NO_ACCT_CNT INT
	SELECT @NO_ACCT_CNT = COUNT(*) FROM #IDRP_BPBASE WHERE ISNULL(cardnmbr,'') = ''
	IF @NO_ACCT_CNT > 0
	BEGIN
		SET @MESSAGE = @MESSAGE + CHAR(13) + '今日IDRP 月付金未足額，有 '+ CAST(@NO_ACCT_CNT AS VARCHAR(10)) + ' 筆查無帳號可執行'
	END 

/* SOURCE CODE BEGIN SAGE
SELE 'IDRP_BP' AS PRG, DATE() AS PRCDATE, IDNO, LEAD_BNK_N AS LEADBK_N, REQ_DEBT_D AS APPLY_D, CARDNMBR, SPACE(13) AS TX_CODE, IIF(CURRSTATE='Y11', 'Y12',IIF(CURRSTATE='Y61','Y62',SPACE(3))) AS CACS_STATE, CURRSTATE AS ORI_STATE, '月付金不足額，總應付  '+ALLT(STR(SHOULD_PAY))+'，實收 '+ALLT(STR(TTL_PAY)) AS F9MEMO, 'F' AS FUN_CODE, '2' AS ROUTE_TYPE,ACCTTYPE,LOCATION FROM IDRP_BPBASE WHERE !ISNULL(CARDNMBR) INTO DBF CACS_ROUTING_BP
COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\ROUTING\CACS_ROUTING_BP_'+ALLT(DTOS(DATE())) FOX2X

IF VARTYPE(MY_COLL_DATE)<>'U' AND EMPTY(MY_COLL_DATE)=.F.
        MSG('Mapping CCH...')
        SELECT CURRCCH
        SET ORDER TO CARDNMBR
        SELECT cardnmbr,date_cch,ltr_cch,ac_cch FROM CURRCCH WHERE cardnmbr IN (SELECT cardnmbr FROM CACS_ROUTING_BP) INTO CURSOR MYTEMP1
        USE IN CURRCCH
        SELECT cardnmbr,date_cch,sum(IIF(inlist(ac_cch,'IC','OC')=.T.,1,0)) AS tel3,sum(IIF(inlist(ltr_cch,'LIE','BIE')=.T.,1,0)) AS letter1 ;
        FROM MYTEMP1 WHERE date_cch>=MY_COLL_DATE AND (inlist(ac_cch,'IC','OC')=.T. OR inlist(ltr_cch,'LIE','BIE')=.T.) ;
        GROUP BY cardnmbr,date_cch INTO CURSOR MYTEMP2
        SELECT cardnmbr,SUM(IIF(tel3>0,1,0)) AS tel3,SUM(IIF(letter1>0,1,0)) AS letter1 FROM MYTEMP2 GROUP BY cardnmbr INTO CURSOR MYTEMP3
        SELECT a.*,b.tel3,b.letter1 FROM CACS_ROUTING_BP a LEFT JOIN MYTEMP3 b ON a.cardnmbr=b.cardnmbr INTO CURSOR MYTEMP4
        SELECT MYTEMP4
        COPY TO 'M:\RESULT\IDRP\NA\三電一函名單\ROUTING\MANUAL_CHECK_BP_'+ALLT(DTOS(DATE())) XL5
        CLOSE TABLES        
ENDIF
MESSAGEBOX('程式執行完畢！',6)
*/
	INSERT INTO UIDRP_CACS_ROUTING_BP (PRG,PRCDATE,IDNO,LEADBK_N,APPLY_D,CARDNMBR,TX_CODE,CACS_STATE,ORI_STATE,F9MEMO,FUN_CODE,ROUTE_TYPE,ACCTTYPE,LOCATION)
	SELECT 
		'IDRP_BP' 
		,GETDATE()
		,IDNO
		,LEAD_BNK_N 
		,REQ_DEBT_D 
		,CARDNMBR
		,SPACE(13)
		,IIF(CURRSTATE='Y11', 'Y12',IIF(CURRSTATE='Y61','Y62','   '))
		,CURRSTATE
		,'月付金不足額，總應付  '+dbo.ALLTRIM((STR(SHOULD_PAY)))+'，實收 '+dbo.ALLTRIM((STR(TTL_PAY)))
		,'F'
		,'2' 
		,ACCTTYPE
		,LOCATION 	
	FROM #IDRP_BPBASE
	WHERE ISNULL(CARDNMBR,'') <> '' 



	IF @MY_COLL_DATE <> ''
	BEGIN

	    DECLARE @MYDATEAS DATE = @MY_COLL_DATE
		DECLARE @WHERE NVARCHAR(500)
		SET @WHERE ='CH.cardnmbr IN (SELECT cardnmbr FROM UIDRP_CACS_ROUTING_BP)'
	    SELECT TOP 0 * INTO #CURRCCH FROM dbo.DS_CCH_VW
		INSERT #CURRCCH  EXECUTE dbo.GET_CCH_SP @MYDATEAS,@WHERE
	 
	     SELECT ROW_NUMBER() OVER (PARTITION BY CARDNMBR ORDER BY CARDNMBR) AS SEQNO, cardnmbr,date_cch,ltr_cch,ac_cch INTO #MYTEMP1 FROM #CURRCCH 

		--SELECT * INTO #CURRCCH FROM GET_CCH_FN(@MY_COLL_DATE) ORDER BY cardnmbr
        --SELECT ROW_NUMBER() OVER (PARTITION BY CARDNMBR ORDER BY CARDNMBR) AS SEQNO, cardnmbr,date_cch,ltr_cch,ac_cch INTO #MYTEMP1 FROM #CURRCCH WHERE cardnmbr IN (SELECT cardnmbr FROM UIDRP_CACS_ROUTING_BP)
		/*
		SELECT cardnmbr,date_cch,sum(IIF(inlist(ac_cch,'IC','OC')=.T.,1,0)) AS tel3,sum(IIF(inlist(ltr_cch,'LIE','BIE')=.T.,1,0)) AS letter1 ;
        FROM MYTEMP1 WHERE date_cch>=MY_COLL_DATE AND (inlist(ac_cch,'IC','OC')=.T. OR inlist(ltr_cch,'LIE','BIE')=.T.) ;
        GROUP BY cardnmbr,date_cch INTO CURSOR MYTEMP2
		*/
		;WITH MYTEMP1_GROUP
		AS
		(
			SELECT cardnmbr , date_cch , MAX(SEQNO) AS M_SEQ 
			, SUM(IIF(AC_CCH IN ('IC','OC'),1,0)) AS tel3 
			, SUM(IIF(ltr_cch IN ('LIE','BIE'),1,0)) AS letter1
			FROM #MYTEMP1 GROUP BY cardnmbr , date_cch
		)
		SELECT A.cardnmbr,A.date_cch 
		,B.tel3
		,B.letter1
		INTO #MYTEMP2
		FROM #MYTEMP1 A
		INNER JOIN MYTEMP1_GROUP B ON A.cardnmbr = B.cardnmbr
		WHERE CONVERT(date , A.date_cch , 111) > CONVERT(DATE,@MY_COLL_DATE,111)
		AND (ac_cch IN ('IC','OC') OR ltr_cch IN ('LIE','BIE'))

		/*
		SELECT cardnmbr,SUM(IIF(tel3>0,1,0)) AS tel3,SUM(IIF(letter1>0,1,0)) AS letter1 FROM MYTEMP2 GROUP BY cardnmbr INTO CURSOR MYTEMP3
        SELECT a.*,b.tel3,b.letter1 FROM CACS_ROUTING_BP a LEFT JOIN MYTEMP3 b ON a.cardnmbr=b.cardnmbr INTO CURSOR MYTEMP4
		*/
		;WITH MYTEMP3
		AS
		(
			SELECT cardnmbr,SUM(IIF(tel3>0,1,0)) AS tel3,SUM(IIF(letter1>0,1,0)) AS letter1 FROM #MYTEMP2 GROUP BY cardnmbr
		)
		INSERT INTO @MYTEMP4
		SELECT A.* , B.tel3 , B.letter1 
		--INTO #MYTEMP4
		FROM UIDRP_CACS_ROUTING_BP A
		LEFT JOIN MYTEMP3 B ON A.CARDNMBR = B.cardnmbr
	END


	SET @STATUS = 1
	SET @MESSAGE = @MESSAGE + CHAR(13) + '程式執行完畢！'
END
END TRY
BEGIN CATCH
	SET @STATUS= 0
	SET @MESSAGE = ERROR_MESSAGE()
END CATCH

----------------------------------------------
--回傳區
----------------------------------------------
	SELECT @STATUS AS [Status] , @MESSAGE AS [Message]
	SELECT * FROM @PAYOFFLIST
	SELECT * FROM @PAY_OVER4
	SELECT * FROM @PAYOFFLIST_ALLBANK
	SELECT * FROM @IDRP_BPBASE_1
	SELECT * FROM @MYTEMP4

	

