	--覆催案件
	--前置協商
	;WITH ZZM203
	AS
	(
	    --若有多筆則取procdate最大一筆
		SELECT A.IDN,[dbo].TRANS_YMD(A.RC_DATE) RC_DATE FROM
		(SELECT IDN,RC_DATE, PROCDATE, ROW_NUMBER() OVER (PARTITION BY IDN ORDER BY PROCDATE DESC) AS SEQNO FROM UIDRP_Z92_ZZM203) A
		WHERE A.SEQNO =1 AND A.PROCDATE >= CAST(DATEADD(Day,-3,@R_DATE_CACS) AS DATE)	 
	)	
	,CARDS_BUDTRAN_RESUME
	AS
	(
		SELECT ID_TAG,CUSTID,CARDNMBR,CACS_STATE FROM dbo.DS_CARDS_VW WHERE (SUBSTRING(CACS_STATE,1,1) IN ('Y','N') OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8') OR CACS_STATE  IN ('G99')) AND CACS_STATE NOT IN ('G76','G86','Y21','N21','N41','Y41')
		UNION ALL 
		SELECT ID_TAG,CUSTID,CARDNMBR,CACS_STATE FROM dbo.DS_BUDTRAN_VW  WHERE (SUBSTRING(CACS_STATE,1,1) IN ('Y','N')  OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8') OR CACS_STATE IN ('G99')) AND CACS_STATE NOT IN ('G76','G86','Y21','N21','N41','Y41')
	) 	 
	INSERT INTO @FF (PRG,PROCDATE,IDNO,CARDNMBR,ORI_STATE,CACS_STATE)
	SELECT 'WCHK_RESUME_COLL' AS PRG,GETDATE(), A.IDN AS IDNO, B.CARDNMBR, B.CACS_STATE AS ORI_STATE,'' AS CACS_STATE
	FROM ZZM203 A  
	INNER JOIN CARDS_BUDTRAN_RESUME B ON A.IDN=B.custid OR A.IDN=B.id_tag

	--前置調解
	;WITH CARDS_BUDTRAN_RESUMEX
	AS
	(
		SELECT ID_TAG,CUSTID,CARDNMBR,CACS_STATE FROM dbo.DS_CARDS_VW WHERE (SUBSTRING(CACS_STATE,1,1) IN ('Y','N') OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8') OR CACS_STATE  IN ('G99')) AND CACS_STATE NOT IN ('G76','G86','Y21','N21','N41','Y41')
		UNION ALL 
		SELECT ID_TAG,CUSTID,CARDNMBR,CACS_STATE FROM dbo.DS_BUDTRAN_VW WHERE (SUBSTRING(CACS_STATE,1,1) IN ('Y','N')  OR SUBSTRING(CACS_STATE,1,2) IN ('G7','G8') OR CACS_STATE IN ('G99')) AND CACS_STATE NOT IN ('G76','G86','Y21','N21','N41','Y41')
	) 	 
	INSERT INTO @FF (PRG,PROCDATE,IDNO,CARDNMBR,ORI_STATE,CACS_STATE)
	SELECT 'WCHK_RESUME_COLL' AS PRG,GETDATE(), M.IDNO, B.CARDNMBR, B.CACS_STATE AS ORI_STATE,
	CASE WHEN SUBSTRING(CACS_STATE,1,2)='G7' AND  FAIL_RESN IN ('11','12','13','14','15','16','17','18','19','21','49') THEN 'G74'
	     WHEN SUBSTRING(CACS_STATE,1,2)='G7' THEN 'G76'
		 WHEN SUBSTRING(CACS_STATE,1,2)='G8' THEN 'G86'
		 WHEN SUBSTRING(CACS_STATE,1,1)='N' THEN 'N41' ELSE '' END AS CACS_STATE
    FROM  UIDRP_IDRP_FULL_BASE_VW M 	
	INNER JOIN CARDS_BUDTRAN_RESUMEX B ON M.IDNO=B.custid OR M.IDNO=B.id_tag
	WHERE M.IF_COMM='Y' AND FAIL_D IS NOT NULL 
	AND CAST(FAIL_D AS DATE) >= CAST(DATEADD(DAY,-3,@R_DATE_CACS) AS DATE)
	AND FAIL_RESN IS NOT NULL AND FAIL_RESN <> '99' 
	  
